// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: endpoints/apps.proto

package endpoint

import (
	fmt "fmt"
	github_com_MicroOps_cn_idas_pkg_service_models "github.com/MicroOps-cn/idas/pkg/service/models"
	models "github.com/MicroOps-cn/idas/pkg/service/models"
	github_com_go_openapi_spec "github.com/go-openapi/spec"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AppProxyUrl struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name" gorm:"type:varchar(50);"`
	Method               string   `protobuf:"bytes,4,opt,name=method,proto3" json:"method" gorm:"type:varchar(8);"`
	Url                  string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url" gorm:"type:varchar(50);"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppProxyUrl) Reset()         { *m = AppProxyUrl{} }
func (m *AppProxyUrl) String() string { return proto.CompactTextString(m) }
func (*AppProxyUrl) ProtoMessage()    {}
func (*AppProxyUrl) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{0}
}
func (m *AppProxyUrl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppProxyUrl.Unmarshal(m, b)
}
func (m *AppProxyUrl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppProxyUrl.Marshal(b, m, deterministic)
}
func (m *AppProxyUrl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppProxyUrl.Merge(m, src)
}
func (m *AppProxyUrl) XXX_Size() int {
	return xxx_messageInfo_AppProxyUrl.Size(m)
}
func (m *AppProxyUrl) XXX_DiscardUnknown() {
	xxx_messageInfo_AppProxyUrl.DiscardUnknown(m)
}

var xxx_messageInfo_AppProxyUrl proto.InternalMessageInfo

func (m *AppProxyUrl) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppProxyUrl) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppProxyUrl) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *AppProxyUrl) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type AppProxy struct {
	Domain                string       `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain" gorm:"type:varchar(50);" valid:"required"`
	Upstream              string       `protobuf:"bytes,4,opt,name=upstream,proto3" json:"upstream" gorm:"type:varchar(50);" valid:"required"`
	Urls                  AppProxyUrls `protobuf:"bytes,5,opt,name=urls,proto3,customtype=AppProxyUrls" json:"urls" gorm:"foreignKey:AppProxyId"`
	InsecureSkipVerify    bool         `protobuf:"varint,6,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecureSkipVerify"`
	TransparentServerName bool         `protobuf:"varint,7,opt,name=transparent_server_name,json=transparentServerName,proto3" json:"transparentServerName"`
	XXX_NoUnkeyedLiteral  struct{}     `json:"-"`
	XXX_unrecognized      []byte       `json:"-"`
	XXX_sizecache         int32        `json:"-"`
}

func (m *AppProxy) Reset()         { *m = AppProxy{} }
func (m *AppProxy) String() string { return proto.CompactTextString(m) }
func (*AppProxy) ProtoMessage()    {}
func (*AppProxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{1}
}
func (m *AppProxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppProxy.Unmarshal(m, b)
}
func (m *AppProxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppProxy.Marshal(b, m, deterministic)
}
func (m *AppProxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppProxy.Merge(m, src)
}
func (m *AppProxy) XXX_Size() int {
	return xxx_messageInfo_AppProxy.Size(m)
}
func (m *AppProxy) XXX_DiscardUnknown() {
	xxx_messageInfo_AppProxy.DiscardUnknown(m)
}

var xxx_messageInfo_AppProxy proto.InternalMessageInfo

func (m *AppProxy) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AppProxy) GetUpstream() string {
	if m != nil {
		return m.Upstream
	}
	return ""
}

func (m *AppProxy) GetInsecureSkipVerify() bool {
	if m != nil {
		return m.InsecureSkipVerify
	}
	return false
}

func (m *AppProxy) GetTransparentServerName() bool {
	if m != nil {
		return m.TransparentServerName
	}
	return false
}

type AppInfo struct {
	Id                   string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	Name                 string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name" valid:"required,matches(^[-_A-Za-z0-9]+$)"`
	Description          string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Avatar               string                     `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GrantType            []models.AppMeta_GrantType `protobuf:"varint,6,rep,packed,name=grant_type,json=grantType,proto3,enum=idas.service.models.AppMeta_GrantType" json:"grantType"`
	GrantMode            models.AppMeta_GrantMode   `protobuf:"varint,7,opt,name=grant_mode,json=grantMode,proto3,enum=idas.service.models.AppMeta_GrantMode" json:"grantMode"`
	Status               models.AppMeta_Status      `protobuf:"varint,8,opt,name=status,proto3,enum=idas.service.models.AppMeta_Status" json:"status"`
	Url                  string                     `protobuf:"bytes,9,opt,name=url,proto3" json:"url" valid:"required"`
	UpdateTime           string                     `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"updateTime" valid:"required"`
	CreateTime           string                     `protobuf:"bytes,13,opt,name=create_time,json=createTime,proto3" json:"createTime" valid:"required"`
	IsDelete             bool                       `protobuf:"varint,14,opt,name=is_delete,json=isDelete,proto3" json:"isDelete" valid:"required"`
	Users                []*UserInfo                `protobuf:"bytes,15,rep,name=users,proto3" json:"users,omitempty"`
	Roles                []*AppRole                 `protobuf:"bytes,16,rep,name=roles,proto3" json:"roles,omitempty"`
	Proxy                *AppProxy                  `protobuf:"bytes,17,opt,name=proxy,proto3" json:"proxy,omitempty"`
	DisplayName          string                     `protobuf:"bytes,18,opt,name=display_name,json=displayName,proto3" json:"displayName,omitempty" gorm:"type:varchar(128)"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{2}
}
func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (m *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(m, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *AppInfo) GetGrantType() []models.AppMeta_GrantType {
	if m != nil {
		return m.GrantType
	}
	return nil
}

func (m *AppInfo) GetGrantMode() models.AppMeta_GrantMode {
	if m != nil {
		return m.GrantMode
	}
	return models.AppMeta_manual
}

func (m *AppInfo) GetStatus() models.AppMeta_Status {
	if m != nil {
		return m.Status
	}
	return models.AppMeta_unknown
}

func (m *AppInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AppInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *AppInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *AppInfo) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *AppInfo) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *AppInfo) GetRoles() []*AppRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *AppInfo) GetProxy() *AppProxy {
	if m != nil {
		return m.Proxy
	}
	return nil
}

func (m *AppInfo) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type GetAppRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppRequest) Reset()         { *m = GetAppRequest{} }
func (m *GetAppRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppRequest) ProtoMessage()    {}
func (*GetAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{3}
}
func (m *GetAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppRequest.Unmarshal(m, b)
}
func (m *GetAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppRequest.Marshal(b, m, deterministic)
}
func (m *GetAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppRequest.Merge(m, src)
}
func (m *GetAppRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppRequest.Size(m)
}
func (m *GetAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppRequest proto.InternalMessageInfo

func (m *GetAppRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAppRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAppRequest) Reset()         { *m = DeleteAppRequest{} }
func (m *DeleteAppRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAppRequest) ProtoMessage()    {}
func (*DeleteAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{4}
}
func (m *DeleteAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAppRequest.Unmarshal(m, b)
}
func (m *DeleteAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAppRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAppRequest.Merge(m, src)
}
func (m *DeleteAppRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAppRequest.Size(m)
}
func (m *DeleteAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAppRequest proto.InternalMessageInfo

func (m *DeleteAppRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAppsRequest struct {
	BaseListRequest      `protobuf:"bytes,1,opt,name=base_list_request,json=baseListRequest,proto3,embedded=base_list_request" json:",omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppsRequest) Reset()         { *m = GetAppsRequest{} }
func (m *GetAppsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppsRequest) ProtoMessage()    {}
func (*GetAppsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{5}
}
func (m *GetAppsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppsRequest.Unmarshal(m, b)
}
func (m *GetAppsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppsRequest.Marshal(b, m, deterministic)
}
func (m *GetAppsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppsRequest.Merge(m, src)
}
func (m *GetAppsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppsRequest.Size(m)
}
func (m *GetAppsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppsRequest proto.InternalMessageInfo

type GetAppsResponse struct {
	BaseListResponse     `protobuf:"bytes,1,opt,name=base_list_response,json=baseListResponse,proto3,embedded=base_list_response" json:",omitempty"`
	Data                 []*AppInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAppsResponse) Reset()         { *m = GetAppsResponse{} }
func (m *GetAppsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppsResponse) ProtoMessage()    {}
func (*GetAppsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{6}
}
func (m *GetAppsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppsResponse.Unmarshal(m, b)
}
func (m *GetAppsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppsResponse.Marshal(b, m, deterministic)
}
func (m *GetAppsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppsResponse.Merge(m, src)
}
func (m *GetAppsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppsResponse.Size(m)
}
func (m *GetAppsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppsResponse proto.InternalMessageInfo

func (m *GetAppsResponse) GetData() []*AppInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAppResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,embedded=base_response" json:",omitempty"`
	Data                 *AppInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppResponse) Reset()         { *m = GetAppResponse{} }
func (m *GetAppResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppResponse) ProtoMessage()    {}
func (*GetAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{7}
}
func (m *GetAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppResponse.Unmarshal(m, b)
}
func (m *GetAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppResponse.Marshal(b, m, deterministic)
}
func (m *GetAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppResponse.Merge(m, src)
}
func (m *GetAppResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppResponse.Size(m)
}
func (m *GetAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppResponse proto.InternalMessageInfo

func (m *GetAppResponse) GetData() *AppInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type PatchAppRequest struct {
	Id          string                                                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	Description *string                                                            `protobuf:"bytes,3,opt,name=description,proto3,customtype=string" json:"description,omitempty"`
	Name        *string                                                            `protobuf:"bytes,4,opt,name=name,proto3,customtype=string" json:"name,omitempty" valid:"optional,matches(^[-_A-Za-z0-9]+$)"`
	Avatar      *string                                                            `protobuf:"bytes,5,opt,name=avatar,proto3,customtype=string" json:"avatar,omitempty"`
	GrantType   []github_com_MicroOps_cn_idas_pkg_service_models.AppMeta_GrantType `protobuf:"varint,6,rep,packed,name=grant_type,json=grantType,proto3,enum=idas.service.models.AppMeta_GrantType,customtype=github.com/MicroOps-cn/idas/pkg/service/models.AppMeta_GrantType" json:"grantType,omitempty"`
	GrantMode   *github_com_MicroOps_cn_idas_pkg_service_models.AppMeta_GrantType  `protobuf:"varint,7,opt,name=grant_mode,json=grantMode,proto3,enum=idas.service.models.AppMeta_GrantMode,customtype=github.com/MicroOps-cn/idas/pkg/service/models.AppMeta_GrantType" json:"grantMode,omitempty"`
	Status      *github_com_MicroOps_cn_idas_pkg_service_models.AppMeta_Status     `protobuf:"varint,8,opt,name=status,proto3,enum=idas.service.models.AppMeta_Status,customtype=github.com/MicroOps-cn/idas/pkg/service/models.AppMeta_Status" json:"status,omitempty"`
	Url         *string                                                            `protobuf:"bytes,12,opt,name=url,proto3,customtype=string" json:"url,omitempty"`
	IsDelete    *bool                                                              `protobuf:"varint,14,opt,name=is_delete,json=isDelete,proto3,customtype=bool" json:"isDelete,omitempty"`
	Proxy       *AppProxy                                                          `protobuf:"bytes,15,opt,name=proxy,proto3" json:"proxy,omitempty"`
	DisplayName string                                                             `protobuf:"bytes,16,opt,name=display_name,json=displayName,proto3" json:"displayName,omitempty" gorm:"type:varchar(128)"`
}

func (m *PatchAppRequest) Reset()         { *m = PatchAppRequest{} }
func (m *PatchAppRequest) String() string { return proto.CompactTextString(m) }
func (*PatchAppRequest) ProtoMessage()    {}
func (*PatchAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{8}
}
func (m *PatchAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchAppRequest.Unmarshal(m, b)
}
func (m *PatchAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchAppRequest.Marshal(b, m, deterministic)
}
func (m *PatchAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchAppRequest.Merge(m, src)
}
func (m *PatchAppRequest) XXX_Size() int {
	return xxx_messageInfo_PatchAppRequest.Size(m)
}
func (m *PatchAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchAppRequest proto.InternalMessageInfo

type AppUser struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	RoleId               string   `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"roleId,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppUser) Reset()         { *m = AppUser{} }
func (m *AppUser) String() string { return proto.CompactTextString(m) }
func (*AppUser) ProtoMessage()    {}
func (*AppUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{9}
}
func (m *AppUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppUser.Unmarshal(m, b)
}
func (m *AppUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppUser.Marshal(b, m, deterministic)
}
func (m *AppUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppUser.Merge(m, src)
}
func (m *AppUser) XXX_Size() int {
	return xxx_messageInfo_AppUser.Size(m)
}
func (m *AppUser) XXX_DiscardUnknown() {
	xxx_messageInfo_AppUser.DiscardUnknown(m)
}

var xxx_messageInfo_AppUser proto.InternalMessageInfo

func (m *AppUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppUser) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *AppUser) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type AppRole struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name" valid:"required"`
	Urls                 []string `protobuf:"bytes,4,rep,name=urls,proto3" json:"urls,omitempty"`
	IsDefault            bool     `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"isDefault,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppRole) Reset()         { *m = AppRole{} }
func (m *AppRole) String() string { return proto.CompactTextString(m) }
func (*AppRole) ProtoMessage()    {}
func (*AppRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{10}
}
func (m *AppRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppRole.Unmarshal(m, b)
}
func (m *AppRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppRole.Marshal(b, m, deterministic)
}
func (m *AppRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppRole.Merge(m, src)
}
func (m *AppRole) XXX_Size() int {
	return xxx_messageInfo_AppRole.Size(m)
}
func (m *AppRole) XXX_DiscardUnknown() {
	xxx_messageInfo_AppRole.DiscardUnknown(m)
}

var xxx_messageInfo_AppRole proto.InternalMessageInfo

func (m *AppRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppRole) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *AppRole) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

type CreateAppRequest struct {
	Description string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Name        string                     `protobuf:"bytes,4,opt,name=name,proto3" json:"name" valid:"required,matches(^[-_A-Za-z0-9]+$)"`
	Avatar      string                     `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GrantType   []models.AppMeta_GrantType `protobuf:"varint,6,rep,packed,name=grant_type,json=grantType,proto3,enum=idas.service.models.AppMeta_GrantType" json:"grantType,omitempty"`
	GrantMode   models.AppMeta_GrantMode   `protobuf:"varint,7,opt,name=grant_mode,json=grantMode,proto3,enum=idas.service.models.AppMeta_GrantMode" json:"grantMode,omitempty"`
	Users       []*AppUser                 `protobuf:"bytes,8,rep,name=users,proto3" json:"users,omitempty"`
	Roles       []*AppRole                 `protobuf:"bytes,9,rep,name=roles,proto3" json:"roles,omitempty"`
	Url         string                     `protobuf:"bytes,12,opt,name=url,proto3" json:"url" valid:"required"`
	Proxy       *AppProxy                  `protobuf:"bytes,17,opt,name=proxy,proto3" json:"proxy,omitempty"`
	DisplayName string                     `protobuf:"bytes,13,opt,name=display_name,json=displayName,proto3" json:"displayName,omitempty" gorm:"type:varchar(128)"`
}

func (m *CreateAppRequest) Reset()         { *m = CreateAppRequest{} }
func (m *CreateAppRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAppRequest) ProtoMessage()    {}
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{11}
}
func (m *CreateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppRequest.Unmarshal(m, b)
}
func (m *CreateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppRequest.Marshal(b, m, deterministic)
}
func (m *CreateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppRequest.Merge(m, src)
}
func (m *CreateAppRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAppRequest.Size(m)
}
func (m *CreateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppRequest proto.InternalMessageInfo

type UpdateAppRequest struct {
	Id          string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	Description string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Name        string                     `protobuf:"bytes,4,opt,name=name,proto3" json:"name" valid:"required,matches(^[-_A-Za-z0-9]+$)"`
	Avatar      string                     `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GrantType   []models.AppMeta_GrantType `protobuf:"varint,6,rep,packed,name=grant_type,json=grantType,proto3,enum=idas.service.models.AppMeta_GrantType" json:"grantType,omitempty"`
	GrantMode   models.AppMeta_GrantMode   `protobuf:"varint,7,opt,name=grant_mode,json=grantMode,proto3,enum=idas.service.models.AppMeta_GrantMode" json:"grantMode,omitempty"`
	Users       []*AppUser                 `protobuf:"bytes,8,rep,name=users,proto3" json:"users,omitempty"`
	Roles       []*AppRole                 `protobuf:"bytes,9,rep,name=roles,proto3" json:"roles,omitempty"`
	Status      models.AppMeta_Status      `protobuf:"varint,10,opt,name=status,proto3,enum=idas.service.models.AppMeta_Status" json:"status"`
	IsDelete    bool                       `protobuf:"varint,11,opt,name=is_delete,json=isDelete,proto3" json:"isDelete,omitempty"`
	Url         string                     `protobuf:"bytes,12,opt,name=url,proto3" json:"url"`
	Proxy       *AppProxy                  `protobuf:"bytes,17,opt,name=proxy,proto3" json:"proxy,omitempty"`
	DisplayName string                     `protobuf:"bytes,13,opt,name=display_name,json=displayName,proto3" json:"displayName,omitempty" gorm:"type:varchar(128)"`
}

func (m *UpdateAppRequest) Reset()         { *m = UpdateAppRequest{} }
func (m *UpdateAppRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAppRequest) ProtoMessage()    {}
func (*UpdateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{12}
}
func (m *UpdateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppRequest.Unmarshal(m, b)
}
func (m *UpdateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppRequest.Merge(m, src)
}
func (m *UpdateAppRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAppRequest.Size(m)
}
func (m *UpdateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppRequest proto.InternalMessageInfo

type AppKeyInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	UpdateTime           string   `protobuf:"bytes,2,opt,name=update_time,json=updateTime,proto3" json:"updateTime" valid:"required"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"createTime" valid:"required"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	AppId                string   `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"appId"`
	Key                  string   `protobuf:"bytes,6,opt,name=key,proto3" json:"key"`
	Secret               string   `protobuf:"bytes,7,opt,name=secret,proto3" json:"secret"`
	PrivateKey           string   `protobuf:"bytes,8,opt,name=privateKey,proto3" json:"privateKey"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppKeyInfo) Reset()         { *m = AppKeyInfo{} }
func (m *AppKeyInfo) String() string { return proto.CompactTextString(m) }
func (*AppKeyInfo) ProtoMessage()    {}
func (*AppKeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{13}
}
func (m *AppKeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppKeyInfo.Unmarshal(m, b)
}
func (m *AppKeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppKeyInfo.Marshal(b, m, deterministic)
}
func (m *AppKeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppKeyInfo.Merge(m, src)
}
func (m *AppKeyInfo) XXX_Size() int {
	return xxx_messageInfo_AppKeyInfo.Size(m)
}
func (m *AppKeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppKeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppKeyInfo proto.InternalMessageInfo

func (m *AppKeyInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppKeyInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *AppKeyInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *AppKeyInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppKeyInfo) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *AppKeyInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AppKeyInfo) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *AppKeyInfo) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type SimpleAppKeyInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required,uuid"`
	UpdateTime           string   `protobuf:"bytes,2,opt,name=update_time,json=updateTime,proto3" json:"updateTime" valid:"required"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"createTime" valid:"required"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	AppId                string   `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"appId"`
	Key                  string   `protobuf:"bytes,6,opt,name=key,proto3" json:"key"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleAppKeyInfo) Reset()         { *m = SimpleAppKeyInfo{} }
func (m *SimpleAppKeyInfo) String() string { return proto.CompactTextString(m) }
func (*SimpleAppKeyInfo) ProtoMessage()    {}
func (*SimpleAppKeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{14}
}
func (m *SimpleAppKeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleAppKeyInfo.Unmarshal(m, b)
}
func (m *SimpleAppKeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleAppKeyInfo.Marshal(b, m, deterministic)
}
func (m *SimpleAppKeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleAppKeyInfo.Merge(m, src)
}
func (m *SimpleAppKeyInfo) XXX_Size() int {
	return xxx_messageInfo_SimpleAppKeyInfo.Size(m)
}
func (m *SimpleAppKeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleAppKeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleAppKeyInfo proto.InternalMessageInfo

func (m *SimpleAppKeyInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SimpleAppKeyInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *SimpleAppKeyInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *SimpleAppKeyInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SimpleAppKeyInfo) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *SimpleAppKeyInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type CreateAppKeyRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"appId" valid:"required,uuid"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAppKeyRequest) Reset()         { *m = CreateAppKeyRequest{} }
func (m *CreateAppKeyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAppKeyRequest) ProtoMessage()    {}
func (*CreateAppKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{15}
}
func (m *CreateAppKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppKeyRequest.Unmarshal(m, b)
}
func (m *CreateAppKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppKeyRequest.Marshal(b, m, deterministic)
}
func (m *CreateAppKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppKeyRequest.Merge(m, src)
}
func (m *CreateAppKeyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAppKeyRequest.Size(m)
}
func (m *CreateAppKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppKeyRequest proto.InternalMessageInfo

func (m *CreateAppKeyRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CreateAppKeyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateAppKeyResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,embedded=base_response" json:",omitempty"`
	Data                 *AppKeyInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAppKeyResponse) Reset()         { *m = CreateAppKeyResponse{} }
func (m *CreateAppKeyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAppKeyResponse) ProtoMessage()    {}
func (*CreateAppKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{16}
}
func (m *CreateAppKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppKeyResponse.Unmarshal(m, b)
}
func (m *CreateAppKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppKeyResponse.Marshal(b, m, deterministic)
}
func (m *CreateAppKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppKeyResponse.Merge(m, src)
}
func (m *CreateAppKeyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAppKeyResponse.Size(m)
}
func (m *CreateAppKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppKeyResponse proto.InternalMessageInfo

func (m *CreateAppKeyResponse) GetData() *AppKeyInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAppKeysRequest struct {
	BaseListRequest      `protobuf:"bytes,1,opt,name=base_list_request,json=baseListRequest,proto3,embedded=base_list_request" json:"base_list_request"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"appId" valid:"required,uuid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppKeysRequest) Reset()         { *m = GetAppKeysRequest{} }
func (m *GetAppKeysRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppKeysRequest) ProtoMessage()    {}
func (*GetAppKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{17}
}
func (m *GetAppKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppKeysRequest.Unmarshal(m, b)
}
func (m *GetAppKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppKeysRequest.Marshal(b, m, deterministic)
}
func (m *GetAppKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppKeysRequest.Merge(m, src)
}
func (m *GetAppKeysRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppKeysRequest.Size(m)
}
func (m *GetAppKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppKeysRequest proto.InternalMessageInfo

func (m *GetAppKeysRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type GetAppKeysResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,embedded=base_response" json:",omitempty"`
	Data                 []*SimpleAppKeyInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAppKeysResponse) Reset()         { *m = GetAppKeysResponse{} }
func (m *GetAppKeysResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppKeysResponse) ProtoMessage()    {}
func (*GetAppKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{18}
}
func (m *GetAppKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppKeysResponse.Unmarshal(m, b)
}
func (m *GetAppKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppKeysResponse.Marshal(b, m, deterministic)
}
func (m *GetAppKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppKeysResponse.Merge(m, src)
}
func (m *GetAppKeysResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppKeysResponse.Size(m)
}
func (m *GetAppKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppKeysResponse proto.InternalMessageInfo

func (m *GetAppKeysResponse) GetData() []*SimpleAppKeyInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteAppKeysRequest struct {
	Id                   github_com_go_openapi_spec.StringOrArray `protobuf:"bytes,1,opt,name=id,proto3,customtype=github.com/go-openapi/spec.StringOrArray" json:"id" valid:"required,uuid"`
	AppId                string                                   `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId" valid:"required"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *DeleteAppKeysRequest) Reset()         { *m = DeleteAppKeysRequest{} }
func (m *DeleteAppKeysRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAppKeysRequest) ProtoMessage()    {}
func (*DeleteAppKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0a7f6d6e7b09df, []int{19}
}
func (m *DeleteAppKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAppKeysRequest.Unmarshal(m, b)
}
func (m *DeleteAppKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAppKeysRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAppKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAppKeysRequest.Merge(m, src)
}
func (m *DeleteAppKeysRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAppKeysRequest.Size(m)
}
func (m *DeleteAppKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAppKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAppKeysRequest proto.InternalMessageInfo

func (m *DeleteAppKeysRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func init() {
	proto.RegisterType((*AppProxyUrl)(nil), "idas.endpoint.AppProxyUrl")
	proto.RegisterType((*AppProxy)(nil), "idas.endpoint.AppProxy")
	proto.RegisterType((*AppInfo)(nil), "idas.endpoint.AppInfo")
	proto.RegisterType((*GetAppRequest)(nil), "idas.endpoint.GetAppRequest")
	proto.RegisterType((*DeleteAppRequest)(nil), "idas.endpoint.DeleteAppRequest")
	proto.RegisterType((*GetAppsRequest)(nil), "idas.endpoint.GetAppsRequest")
	proto.RegisterType((*GetAppsResponse)(nil), "idas.endpoint.GetAppsResponse")
	proto.RegisterType((*GetAppResponse)(nil), "idas.endpoint.GetAppResponse")
	proto.RegisterType((*PatchAppRequest)(nil), "idas.endpoint.PatchAppRequest")
	proto.RegisterType((*AppUser)(nil), "idas.endpoint.AppUser")
	proto.RegisterType((*AppRole)(nil), "idas.endpoint.AppRole")
	proto.RegisterType((*CreateAppRequest)(nil), "idas.endpoint.CreateAppRequest")
	proto.RegisterType((*UpdateAppRequest)(nil), "idas.endpoint.UpdateAppRequest")
	proto.RegisterType((*AppKeyInfo)(nil), "idas.endpoint.AppKeyInfo")
	proto.RegisterType((*SimpleAppKeyInfo)(nil), "idas.endpoint.SimpleAppKeyInfo")
	proto.RegisterType((*CreateAppKeyRequest)(nil), "idas.endpoint.CreateAppKeyRequest")
	proto.RegisterType((*CreateAppKeyResponse)(nil), "idas.endpoint.CreateAppKeyResponse")
	proto.RegisterType((*GetAppKeysRequest)(nil), "idas.endpoint.GetAppKeysRequest")
	proto.RegisterType((*GetAppKeysResponse)(nil), "idas.endpoint.GetAppKeysResponse")
	proto.RegisterType((*DeleteAppKeysRequest)(nil), "idas.endpoint.DeleteAppKeysRequest")
}

func init() { proto.RegisterFile("endpoints/apps.proto", fileDescriptor_ed0a7f6d6e7b09df) }

var fileDescriptor_ed0a7f6d6e7b09df = []byte{
	// 1699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0xcd, 0x6f, 0x1b, 0xb9,
	0x15, 0xf7, 0xc8, 0xb2, 0x2c, 0xd1, 0x5f, 0xca, 0xd8, 0xb1, 0x95, 0xc4, 0xcd, 0x08, 0x93, 0xb4,
	0xb0, 0x53, 0x4b, 0x72, 0x6c, 0x24, 0x75, 0x9c, 0x06, 0x88, 0x94, 0x02, 0xa9, 0xe3, 0xa4, 0x76,
	0xc7, 0x76, 0x11, 0x24, 0x68, 0x04, 0x4a, 0x43, 0xcb, 0x84, 0x25, 0x0d, 0x43, 0x8e, 0x8c, 0xaa,
	0x40, 0x7b, 0xe8, 0xa9, 0xc7, 0x02, 0x05, 0x8a, 0xee, 0x69, 0x37, 0xd9, 0x1c, 0xf6, 0xb0, 0xf7,
	0xdd, 0x3f, 0x61, 0x8f, 0x39, 0xfb, 0x30, 0x7f, 0x80, 0x0e, 0x7b, 0xf0, 0x61, 0x8f, 0x8b, 0x05,
	0x39, 0x1c, 0x89, 0x92, 0x2c, 0x7f, 0x29, 0x01, 0x72, 0xc8, 0xc5, 0xe2, 0x3c, 0xbe, 0xf7, 0xe3,
	0xe3, 0xe3, 0xfb, 0x22, 0x0d, 0xa6, 0x50, 0xd5, 0x26, 0x0e, 0xae, 0xba, 0x2c, 0x03, 0x09, 0x61,
	0x69, 0x42, 0x1d, 0xd7, 0xd1, 0xc7, 0xb0, 0x0d, 0x59, 0x3a, 0x98, 0xba, 0x3a, 0x55, 0x72, 0x4a,
	0x8e, 0x98, 0xc9, 0xf0, 0x91, 0xcf, 0x74, 0x75, 0xb2, 0xe2, 0xd8, 0xa8, 0xcc, 0x32, 0xfe, 0x8f,
	0x24, 0x5e, 0x6e, 0xe1, 0xd5, 0x18, 0xa2, 0x01, 0x59, 0x59, 0xa6, 0x00, 0x19, 0xf2, 0xa9, 0xe6,
	0x8f, 0x1a, 0x18, 0xc9, 0x12, 0xb2, 0x49, 0x9d, 0xbf, 0xd5, 0x77, 0x68, 0x59, 0xcf, 0x80, 0x10,
	0xb6, 0x13, 0x5a, 0x52, 0x9b, 0x8b, 0xe5, 0x8c, 0x86, 0x67, 0x84, 0xb0, 0x7d, 0xe4, 0x19, 0x97,
	0x0f, 0x60, 0x19, 0xdb, 0xab, 0x26, 0x45, 0xaf, 0x6b, 0x98, 0x22, 0x7b, 0xa1, 0x56, 0xc3, 0xb6,
	0x69, 0x85, 0xb0, 0xad, 0xaf, 0x80, 0x70, 0x15, 0x56, 0x50, 0x62, 0x50, 0x88, 0xdc, 0x6c, 0x78,
	0x86, 0xf8, 0x3e, 0xf2, 0x8c, 0x44, 0xc9, 0xa1, 0x95, 0x55, 0xd3, 0xad, 0x13, 0xb4, 0x7a, 0x00,
	0x69, 0x71, 0x0f, 0xd2, 0xb9, 0x3b, 0x8b, 0xf3, 0xf7, 0x4d, 0x4b, 0x70, 0xe8, 0x0f, 0x40, 0xa4,
	0x82, 0xdc, 0x3d, 0xc7, 0x4e, 0x84, 0x85, 0xec, 0xaf, 0x1b, 0x9e, 0x21, 0x29, 0x47, 0x9e, 0x31,
	0x73, 0x8c, 0xf4, 0x0a, 0x17, 0x96, 0x2c, 0xfa, 0x1d, 0x30, 0x58, 0xa3, 0xe5, 0xc4, 0x90, 0x90,
	0xbd, 0xd1, 0xf0, 0x0c, 0xfe, 0x79, 0xe2, 0xb2, 0x9c, 0xc1, 0x7c, 0x33, 0x08, 0xa2, 0xc1, 0x86,
	0xf5, 0x0d, 0x10, 0xb1, 0x9d, 0x0a, 0xc4, 0x55, 0xa9, 0xfe, 0xef, 0xb8, 0x0a, 0x3e, 0xe5, 0xc8,
	0x33, 0xe6, 0x7b, 0x21, 0x25, 0x3b, 0xcc, 0x61, 0x5a, 0x52, 0x48, 0xdf, 0x01, 0xd1, 0x1a, 0x61,
	0x2e, 0x45, 0xb0, 0x22, 0x77, 0x75, 0xaf, 0xe1, 0x19, 0x4d, 0xda, 0xf9, 0x40, 0x9b, 0x62, 0xfa,
	0x26, 0x08, 0xd7, 0x68, 0x99, 0xc9, 0xcd, 0xfe, 0xfe, 0x07, 0xcf, 0x18, 0x38, 0xf4, 0x8c, 0x51,
	0xe5, 0xe0, 0x18, 0x37, 0x3c, 0xe7, 0x39, 0xf2, 0x8c, 0x59, 0x7f, 0x89, 0x5d, 0x87, 0x22, 0x5c,
	0xaa, 0xae, 0xa3, 0xfa, 0x6a, 0xc0, 0xb8, 0x66, 0x9b, 0x96, 0xe0, 0xd2, 0xff, 0x08, 0xa6, 0x70,
	0x95, 0xa1, 0x62, 0x8d, 0xa2, 0x3c, 0xdb, 0xc7, 0x24, 0x7f, 0x80, 0x28, 0xde, 0xad, 0x27, 0x22,
	0x49, 0x6d, 0x2e, 0x9a, 0x9b, 0x6e, 0x78, 0x86, 0x1e, 0xcc, 0x6f, 0xed, 0x63, 0xf2, 0x17, 0x31,
	0x6b, 0x1d, 0x43, 0xd3, 0xff, 0x0c, 0x66, 0x5c, 0x0a, 0xab, 0x8c, 0x40, 0x8a, 0xaa, 0x6e, 0x9e,
	0x21, 0x7a, 0x80, 0x68, 0x5e, 0xf8, 0xc4, 0xb0, 0x00, 0xbb, 0xd2, 0xf0, 0x8c, 0xcb, 0x0a, 0xcb,
	0x96, 0xe0, 0xf8, 0x13, 0xac, 0x20, 0xeb, 0x78, 0xb2, 0xf9, 0xdf, 0x61, 0x30, 0x9c, 0x25, 0x64,
	0xad, 0xba, 0xeb, 0x9c, 0xdf, 0x21, 0x9f, 0x48, 0x87, 0x0c, 0x09, 0x91, 0xbb, 0x8a, 0x43, 0xde,
	0xea, 0x14, 0xaa, 0x40, 0xb7, 0xb8, 0x87, 0xd8, 0xdc, 0xab, 0x97, 0xa9, 0x7c, 0x36, 0xf5, 0x02,
	0xa6, 0xfe, 0xbe, 0x98, 0xba, 0xf7, 0xd7, 0xdf, 0xde, 0x9c, 0x0f, 0x5c, 0x34, 0x09, 0x46, 0x6c,
	0xc4, 0x8a, 0x14, 0x13, 0x17, 0x3b, 0xd2, 0x49, 0x2c, 0x95, 0xa4, 0x4f, 0x83, 0x08, 0x3c, 0x80,
	0x2e, 0xa4, 0xfe, 0xd9, 0x58, 0xf2, 0x4b, 0xdf, 0x06, 0xa0, 0x44, 0x61, 0xd5, 0xcd, 0xf3, 0x83,
	0x4e, 0x44, 0x92, 0x83, 0x73, 0xe3, 0x4b, 0xbf, 0x49, 0x8b, 0x98, 0xe6, 0x16, 0xc2, 0x45, 0x94,
	0x96, 0x41, 0x9b, 0x25, 0xe4, 0x19, 0x72, 0x61, 0xfa, 0x31, 0x67, 0xdf, 0xae, 0x13, 0x94, 0x1b,
	0x6b, 0x78, 0x46, 0xac, 0x14, 0x7c, 0x5a, 0xad, 0x61, 0x0b, 0x95, 0xcb, 0x0a, 0xf3, 0x9e, 0x09,
	0xf5, 0x99, 0x63, 0xab, 0xa8, 0xfc, 0xd3, 0x6a, 0x0d, 0xf5, 0xc7, 0x20, 0xc2, 0x5c, 0xe8, 0xd6,
	0x58, 0x22, 0x2a, 0x10, 0x6f, 0x9c, 0x88, 0xb8, 0x25, 0x58, 0x73, 0x80, 0x87, 0x8a, 0x2f, 0x66,
	0xc9, 0x5f, 0x3d, 0xe5, 0x87, 0x64, 0x4c, 0x58, 0xfe, 0x5a, 0x2b, 0x24, 0xe3, 0x5d, 0xae, 0xcd,
	0x27, 0xf4, 0x47, 0x60, 0xa4, 0x46, 0x6c, 0xe8, 0xa2, 0xbc, 0x8b, 0x2b, 0x28, 0x31, 0x2a, 0xc4,
	0xcc, 0x86, 0x67, 0x00, 0x9f, 0xbc, 0x8d, 0xc5, 0xb1, 0x75, 0x4b, 0x2b, 0xf3, 0x1c, 0xa4, 0x48,
	0x51, 0x13, 0x64, 0xac, 0x05, 0xe2, 0x93, 0x7b, 0x83, 0xb4, 0xe6, 0xf5, 0x07, 0x20, 0x86, 0x59,
	0xde, 0x46, 0x65, 0xe4, 0xa2, 0xc4, 0xb8, 0xf0, 0xda, 0x24, 0x8f, 0x5b, 0xcc, 0xfe, 0x20, 0x68,
	0xc7, 0x02, 0x34, 0x67, 0xf5, 0x14, 0x18, 0x12, 0x99, 0x36, 0x31, 0x91, 0x1c, 0x9c, 0x1b, 0x59,
	0x9a, 0x49, 0xb7, 0xe5, 0xee, 0xf4, 0x0e, 0x43, 0x94, 0xfb, 0xb2, 0xe5, 0x73, 0xe9, 0x0b, 0x60,
	0x88, 0x3a, 0x65, 0xc4, 0x12, 0x71, 0xc1, 0x3e, 0xdd, 0xc1, 0x9e, 0x25, 0xc4, 0x72, 0xca, 0xc8,
	0xf2, 0x99, 0x38, 0x38, 0xe1, 0xb1, 0x9b, 0xb8, 0x94, 0xd4, 0x8e, 0x01, 0x0f, 0x42, 0xdb, 0xf2,
	0xb9, 0xf4, 0xe7, 0x60, 0xd4, 0xc6, 0x8c, 0x94, 0x61, 0xdd, 0x8f, 0x41, 0x5d, 0x18, 0xe4, 0x0e,
	0x8f, 0x41, 0x49, 0xe7, 0x21, 0xb6, 0xe0, 0x54, 0xb0, 0x8b, 0x2a, 0xc4, 0xad, 0xf7, 0xc8, 0x98,
	0xb7, 0x97, 0x56, 0xe6, 0x4d, 0x6b, 0x44, 0x11, 0x31, 0x1f, 0x82, 0xb1, 0xc7, 0xc8, 0xe5, 0xda,
	0xa1, 0xd7, 0x35, 0xc4, 0xdc, 0x73, 0x87, 0xa6, 0xf9, 0x08, 0xc4, 0x7d, 0x8b, 0xf5, 0x03, 0xe2,
	0x82, 0x71, 0x5f, 0x0d, 0x16, 0x40, 0x14, 0xc0, 0x25, 0x5e, 0xd1, 0xf2, 0x65, 0xcc, 0xdc, 0x3c,
	0xf5, 0x89, 0x02, 0x71, 0x64, 0xe9, 0x7a, 0x87, 0xb5, 0x72, 0x90, 0xa1, 0xa7, 0x98, 0xb9, 0x52,
	0x34, 0x37, 0xcd, 0x53, 0xe9, 0x7b, 0xcf, 0xd0, 0xb8, 0xc3, 0xb4, 0x8c, 0x62, 0x4d, 0x14, 0xda,
	0x19, 0xcd, 0x77, 0x1a, 0x98, 0x68, 0x2e, 0xcb, 0x88, 0x53, 0x65, 0x48, 0x47, 0x40, 0x57, 0xd7,
	0xf5, 0xa9, 0x72, 0x61, 0xa3, 0xe7, 0xc2, 0x3e, 0x5b, 0xcf, 0x95, 0xe3, 0x85, 0x0e, 0x4e, 0xfd,
	0x16, 0x08, 0xdb, 0xd0, 0x85, 0x89, 0x50, 0x2f, 0x6f, 0x11, 0xbe, 0x25, 0x78, 0xcc, 0xff, 0x69,
	0x81, 0x75, 0x9a, 0xe2, 0xcf, 0xc1, 0x98, 0xd0, 0xb2, 0x43, 0xc1, 0x6b, 0xc7, 0x28, 0x78, 0xaa,
	0x72, 0xa3, 0x05, 0x85, 0x4b, 0x51, 0x4c, 0x3b, 0x55, 0xb1, 0xef, 0x86, 0xc1, 0xc4, 0x26, 0x4f,
	0xb7, 0x7d, 0x1c, 0xbd, 0xbe, 0x70, 0x4c, 0x3a, 0xce, 0x81, 0x43, 0x91, 0x88, 0x28, 0xae, 0x96,
	0xda, 0x53, 0xf3, 0x53, 0x59, 0x08, 0xfc, 0x3a, 0xbc, 0xd2, 0x62, 0x53, 0x4a, 0x81, 0x23, 0x58,
	0x61, 0xf9, 0xf4, 0x52, 0x60, 0xb6, 0x27, 0xfa, 0xb6, 0x65, 0x83, 0xa4, 0xff, 0x56, 0xeb, 0x23,
	0xeb, 0xbf, 0x3c, 0xf4, 0x8c, 0x87, 0x25, 0xec, 0xee, 0xd5, 0x0a, 0xe9, 0xa2, 0x53, 0xc9, 0x3c,
	0xc3, 0x45, 0xea, 0x6c, 0x10, 0x96, 0x2a, 0x56, 0x33, 0x1c, 0x21, 0x43, 0xf6, 0x4b, 0x19, 0x89,
	0x92, 0x69, 0x47, 0xc9, 0x37, 0x51, 0x1a, 0x9e, 0x31, 0xd9, 0x2c, 0x17, 0xca, 0xc1, 0x29, 0x35,
	0xa4, 0xa5, 0xe4, 0x05, 0x8a, 0xc8, 0x87, 0x55, 0x92, 0x43, 0x76, 0x29, 0x29, 0x4a, 0xd2, 0x3f,
	0x2f, 0x52, 0x92, 0xb2, 0x87, 0x9e, 0xf1, 0xe0, 0x82, 0xca, 0x6d, 0xb5, 0x57, 0xb2, 0x59, 0xbf,
	0x92, 0x8d, 0x76, 0x1d, 0xb5, 0x28, 0x5c, 0xf7, 0xbb, 0xcb, 0xc5, 0xf5, 0x43, 0xcf, 0x08, 0x17,
	0x1c, 0xa7, 0x2c, 0x3a, 0x27, 0x59, 0x18, 0x94, 0xbd, 0xb5, 0x8a, 0x45, 0x2e, 0xc8, 0xe7, 0x13,
	0x27, 0xe6, 0xf3, 0xdc, 0x64, 0xc3, 0x33, 0x26, 0x04, 0xa7, 0x02, 0xd3, 0x23, 0xc9, 0xc7, 0x3f,
	0x54, 0x92, 0x5f, 0x8d, 0xff, 0xfb, 0x2b, 0x63, 0xe0, 0xfd, 0x1b, 0x63, 0xe0, 0x3f, 0x6f, 0x8d,
	0x81, 0xff, 0xbf, 0x35, 0x06, 0xcc, 0x7f, 0x88, 0x5e, 0x8c, 0xd7, 0xb0, 0xf3, 0x07, 0x6c, 0x0a,
	0x0c, 0xf3, 0x22, 0x96, 0xc7, 0xb6, 0x6c, 0xc7, 0xa6, 0x1a, 0x9e, 0x11, 0xe7, 0xa4, 0x35, 0x5b,
	0xd9, 0x55, 0xc4, 0xa7, 0xe8, 0x3a, 0x08, 0xf3, 0x91, 0xec, 0xb3, 0xc4, 0xd8, 0xfc, 0x5e, 0x13,
	0xeb, 0xf3, 0x8a, 0x78, 0xfe, 0xf5, 0x17, 0xdb, 0x7a, 0xc1, 0x59, 0xa5, 0x17, 0xec, 0x2e, 0xe7,
	0x7e, 0x98, 0xeb, 0xb2, 0xd3, 0x0e, 0x27, 0x07, 0xb9, 0x0a, 0xa2, 0x57, 0xbe, 0x0b, 0x80, 0x38,
	0xee, 0x5d, 0x58, 0x2b, 0xbb, 0x22, 0xfc, 0xa3, 0xb9, 0x19, 0xee, 0xc4, 0xfc, 0x4c, 0x05, 0x51,
	0x75, 0xe2, 0x26, 0xd1, 0xfc, 0x39, 0x0c, 0xe2, 0x8f, 0x44, 0x93, 0xa1, 0x24, 0xbd, 0xd3, 0x5b,
	0xca, 0x27, 0x6d, 0x79, 0xab, 0xbf, 0x06, 0xb6, 0x57, 0x7b, 0xfa, 0xaa, 0x8f, 0x44, 0x35, 0x73,
	0x86, 0x24, 0xf3, 0xaa, 0x8f, 0x1c, 0x33, 0x73, 0x86, 0xfc, 0xb0, 0x10, 0x74, 0x5c, 0xd1, 0x5e,
	0x45, 0x91, 0x3b, 0x6c, 0x57, 0xc3, 0x15, 0x3b, 0x5b, 0xc3, 0xa5, 0xc4, 0xfe, 0xe9, 0x5d, 0x6c,
	0x9f, 0xfd, 0xd9, 0xd8, 0x47, 0x0c, 0xdd, 0x2f, 0x22, 0x20, 0xbe, 0x23, 0x5a, 0xe5, 0x7e, 0xaa,
	0xee, 0x67, 0x8f, 0xfd, 0xd4, 0x3d, 0xb6, 0x75, 0x81, 0x03, 0xfd, 0x5d, 0xe0, 0x96, 0xd5, 0xc2,
	0x36, 0xa2, 0x3c, 0x05, 0x9c, 0x54, 0xd0, 0xae, 0xa8, 0xf1, 0x32, 0x2c, 0xe3, 0xe5, 0x93, 0x8f,
	0x8d, 0x9f, 0x42, 0x00, 0x64, 0x09, 0x59, 0x47, 0xf5, 0x8b, 0x3d, 0x33, 0x74, 0x5c, 0x5e, 0x43,
	0x1f, 0xe2, 0xf2, 0x3a, 0x78, 0xa1, 0xcb, 0xeb, 0x6c, 0x5b, 0xf4, 0x45, 0x83, 0xe8, 0x6b, 0x3e,
	0x61, 0x44, 0x20, 0x21, 0xbc, 0x02, 0xfb, 0x7d, 0x6b, 0xac, 0xe1, 0x19, 0x43, 0x90, 0x90, 0x35,
	0xdb, 0xf2, 0x7f, 0xf8, 0xf9, 0xed, 0x23, 0xff, 0xe5, 0x47, 0x9e, 0xdf, 0x3e, 0xaa, 0x5b, 0xfc,
	0x0f, 0x6f, 0x7a, 0x19, 0x2a, 0x52, 0xe4, 0x8a, 0x80, 0x88, 0x49, 0x9f, 0x11, 0x14, 0x4b, 0xfe,
	0xea, 0x69, 0x00, 0x08, 0xc5, 0x07, 0xd0, 0x45, 0xeb, 0xa8, 0x2e, 0xda, 0xb5, 0x58, 0x6e, 0x9c,
	0x6f, 0xa1, 0x45, 0xb5, 0x94, 0xb1, 0xf9, 0x4d, 0x08, 0xc4, 0xb7, 0x70, 0x85, 0x94, 0xd1, 0x67,
	0xf3, 0x9f, 0x6c, 0x7e, 0xf3, 0x5f, 0x1a, 0x98, 0x6c, 0x36, 0x10, 0xdc, 0x8e, 0x32, 0x85, 0xdf,
	0x6b, 0x82, 0x6a, 0x4d, 0x95, 0x7d, 0xb4, 0xde, 0x46, 0x93, 0xab, 0x2d, 0xb6, 0x3d, 0xd7, 0x9e,
	0xa1, 0x23, 0x32, 0xbf, 0xd4, 0xc0, 0x54, 0xbb, 0x12, 0x1f, 0xfd, 0x62, 0x99, 0x6a, 0xbb, 0x58,
	0x5e, 0xe9, 0xce, 0x1a, 0xd2, 0x6d, 0xe4, 0xdd, 0xf2, 0x9d, 0x06, 0x2e, 0xf9, 0x97, 0xde, 0x75,
	0x54, 0x6f, 0xbe, 0x0a, 0x6c, 0x5f, 0xfc, 0x55, 0x20, 0x1a, 0x68, 0xd9, 0xf5, 0x0e, 0xa0, 0x98,
	0x3e, 0x74, 0x4e, 0xd3, 0x9b, 0x5f, 0x6b, 0x40, 0x57, 0xd5, 0xfc, 0xe8, 0x66, 0x5c, 0x6e, 0x7b,
	0x38, 0xe8, 0x7c, 0x91, 0xe8, 0x8c, 0x41, 0x69, 0xcc, 0x6f, 0x35, 0x30, 0xd5, 0x7c, 0xa4, 0x51,
	0xed, 0x99, 0x57, 0x42, 0x74, 0x43, 0xbe, 0x40, 0xcf, 0x29, 0xb7, 0xad, 0x92, 0x93, 0x72, 0x08,
	0xaa, 0x42, 0x82, 0x33, 0x8c, 0xa0, 0x62, 0x7a, 0x4b, 0x5c, 0x98, 0x36, 0x68, 0x96, 0x52, 0x58,
	0x3f, 0x4b, 0x48, 0x2f, 0x03, 0xdf, 0x50, 0xd2, 0xb2, 0xbf, 0x52, 0x2d, 0xdb, 0xed, 0x9c, 0xfe,
	0x54, 0x6e, 0xf9, 0xc5, 0xed, 0xd3, 0x6e, 0x7c, 0xc1, 0x8e, 0xef, 0x07, 0x83, 0xcd, 0x81, 0x42,
	0x44, 0xfc, 0xf7, 0x63, 0xf9, 0x97, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x72, 0xc3, 0x47, 0x7c,
	0x19, 0x00, 0x00,
}
