// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: v1/apps.proto

package endpoint

import (
	fmt "fmt"
	github_com_MicroOps_cn_idas_pkg_service_models "github.com/MicroOps-cn/idas/pkg/service/models"
	models "github.com/MicroOps-cn/idas/pkg/service/models"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AppInfo struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	Name                 string                   `protobuf:"bytes,2,opt,name=name,proto3" json:"name" valid:"required"`
	Description          string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Storage              string                   `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage" valid:"required"`
	Avatar               string                   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GrantType            models.AppMeta_GrantType `protobuf:"varint,6,opt,name=grant_type,json=grantType,proto3,enum=idas.service.models.AppMeta_GrantType" json:"grantType"`
	GrantMode            models.AppMeta_GrantMode `protobuf:"varint,7,opt,name=grant_mode,json=grantMode,proto3,enum=idas.service.models.AppMeta_GrantMode" json:"grantMode"`
	Status               models.AppMeta_Status    `protobuf:"varint,8,opt,name=status,proto3,enum=idas.service.models.AppMeta_Status" json:"status"`
	UpdateTime           string                   `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"updateTime" valid:"required"`
	CreateTime           string                   `protobuf:"bytes,13,opt,name=create_time,json=createTime,proto3" json:"createTime" valid:"required"`
	IsDelete             bool                     `protobuf:"varint,14,opt,name=is_delete,json=isDelete,proto3" json:"isDelete" valid:"required"`
	User                 []*AppUser               `protobuf:"bytes,15,rep,name=user,proto3" json:"user,omitempty"`
	Role                 []*AppRole               `protobuf:"bytes,16,rep,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{0}
}
func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (m *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(m, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AppInfo) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *AppInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *AppInfo) GetGrantType() models.AppMeta_GrantType {
	if m != nil {
		return m.GrantType
	}
	return models.AppMeta_none
}

func (m *AppInfo) GetGrantMode() models.AppMeta_GrantMode {
	if m != nil {
		return m.GrantMode
	}
	return models.AppMeta_manual
}

func (m *AppInfo) GetStatus() models.AppMeta_Status {
	if m != nil {
		return m.Status
	}
	return models.AppMeta_unknown
}

func (m *AppInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *AppInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *AppInfo) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *AppInfo) GetUser() []*AppUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AppInfo) GetRole() []*AppRole {
	if m != nil {
		return m.Role
	}
	return nil
}

type GetAppRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	Storage              string   `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppRequest) Reset()         { *m = GetAppRequest{} }
func (m *GetAppRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppRequest) ProtoMessage()    {}
func (*GetAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{1}
}
func (m *GetAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppRequest.Unmarshal(m, b)
}
func (m *GetAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppRequest.Marshal(b, m, deterministic)
}
func (m *GetAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppRequest.Merge(m, src)
}
func (m *GetAppRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppRequest.Size(m)
}
func (m *GetAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppRequest proto.InternalMessageInfo

func (m *GetAppRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetAppRequest) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

type DeleteAppRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	Storage              string   `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAppRequest) Reset()         { *m = DeleteAppRequest{} }
func (m *DeleteAppRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAppRequest) ProtoMessage()    {}
func (*DeleteAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{2}
}
func (m *DeleteAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAppRequest.Unmarshal(m, b)
}
func (m *DeleteAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAppRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAppRequest.Merge(m, src)
}
func (m *DeleteAppRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAppRequest.Size(m)
}
func (m *DeleteAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAppRequest proto.InternalMessageInfo

func (m *DeleteAppRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteAppRequest) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

type GetAppsRequest struct {
	BaseListRequest      `protobuf:"bytes,1,opt,name=base_list_request,json=baseListRequest,proto3,embedded=base_list_request" json:",omitempty"`
	Storage              string   `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppsRequest) Reset()         { *m = GetAppsRequest{} }
func (m *GetAppsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAppsRequest) ProtoMessage()    {}
func (*GetAppsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{3}
}
func (m *GetAppsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppsRequest.Unmarshal(m, b)
}
func (m *GetAppsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppsRequest.Marshal(b, m, deterministic)
}
func (m *GetAppsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppsRequest.Merge(m, src)
}
func (m *GetAppsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAppsRequest.Size(m)
}
func (m *GetAppsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppsRequest proto.InternalMessageInfo

func (m *GetAppsRequest) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

type GetAppsResponse struct {
	BaseListResponse     `protobuf:"bytes,1,opt,name=base_list_response,json=baseListResponse,proto3,embedded=base_list_response" json:",omitempty"`
	Data                 []*AppInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAppsResponse) Reset()         { *m = GetAppsResponse{} }
func (m *GetAppsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppsResponse) ProtoMessage()    {}
func (*GetAppsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{4}
}
func (m *GetAppsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppsResponse.Unmarshal(m, b)
}
func (m *GetAppsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppsResponse.Marshal(b, m, deterministic)
}
func (m *GetAppsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppsResponse.Merge(m, src)
}
func (m *GetAppsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppsResponse.Size(m)
}
func (m *GetAppsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppsResponse proto.InternalMessageInfo

func (m *GetAppsResponse) GetData() []*AppInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAppResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,embedded=base_response" json:",omitempty"`
	Data                 *AppInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppResponse) Reset()         { *m = GetAppResponse{} }
func (m *GetAppResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppResponse) ProtoMessage()    {}
func (*GetAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{5}
}
func (m *GetAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppResponse.Unmarshal(m, b)
}
func (m *GetAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppResponse.Marshal(b, m, deterministic)
}
func (m *GetAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppResponse.Merge(m, src)
}
func (m *GetAppResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppResponse.Size(m)
}
func (m *GetAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppResponse proto.InternalMessageInfo

func (m *GetAppResponse) GetData() *AppInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type PatchAppRequest struct {
	Id                   string                                                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	Storage              string                                                            `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage" valid:"required"`
	Description          *string                                                           `protobuf:"bytes,3,opt,name=description,proto3,customtype=string" json:"description,omitempty"`
	Name                 *string                                                           `protobuf:"bytes,4,opt,name=name,proto3,customtype=string" json:"name,omitempty"`
	Avatar               *string                                                           `protobuf:"bytes,5,opt,name=avatar,proto3,customtype=string" json:"avatar,omitempty"`
	GrantType            *github_com_MicroOps_cn_idas_pkg_service_models.AppMeta_GrantType `protobuf:"varint,6,opt,name=grant_type,json=grantType,proto3,enum=idas.service.models.AppMeta_GrantType,customtype=github.com/MicroOps-cn/idas/pkg/service/models.AppMeta_GrantType" json:"grantType,omitempty"`
	GrantMode            *github_com_MicroOps_cn_idas_pkg_service_models.AppMeta_GrantType `protobuf:"varint,7,opt,name=grant_mode,json=grantMode,proto3,enum=idas.service.models.AppMeta_GrantMode,customtype=github.com/MicroOps-cn/idas/pkg/service/models.AppMeta_GrantType" json:"grantMode,omitempty"`
	Status               *github_com_MicroOps_cn_idas_pkg_service_models.AppMeta_Status    `protobuf:"varint,8,opt,name=status,proto3,enum=idas.service.models.AppMeta_Status,customtype=github.com/MicroOps-cn/idas/pkg/service/models.AppMeta_Status" json:"status,omitempty"`
	IsDelete             *bool                                                             `protobuf:"varint,14,opt,name=is_delete,json=isDelete,proto3,customtype=bool" json:"isDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                          `json:"-"`
	XXX_unrecognized     []byte                                                            `json:"-"`
	XXX_sizecache        int32                                                             `json:"-"`
}

func (m *PatchAppRequest) Reset()         { *m = PatchAppRequest{} }
func (m *PatchAppRequest) String() string { return proto.CompactTextString(m) }
func (*PatchAppRequest) ProtoMessage()    {}
func (*PatchAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{6}
}
func (m *PatchAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchAppRequest.Unmarshal(m, b)
}
func (m *PatchAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchAppRequest.Marshal(b, m, deterministic)
}
func (m *PatchAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchAppRequest.Merge(m, src)
}
func (m *PatchAppRequest) XXX_Size() int {
	return xxx_messageInfo_PatchAppRequest.Size(m)
}
func (m *PatchAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchAppRequest proto.InternalMessageInfo

func (m *PatchAppRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PatchAppRequest) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

type PatchAppResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,embedded=base_response" json:"base_response"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchAppResponse) Reset()         { *m = PatchAppResponse{} }
func (m *PatchAppResponse) String() string { return proto.CompactTextString(m) }
func (*PatchAppResponse) ProtoMessage()    {}
func (*PatchAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{7}
}
func (m *PatchAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchAppResponse.Unmarshal(m, b)
}
func (m *PatchAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchAppResponse.Marshal(b, m, deterministic)
}
func (m *PatchAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchAppResponse.Merge(m, src)
}
func (m *PatchAppResponse) XXX_Size() int {
	return xxx_messageInfo_PatchAppResponse.Size(m)
}
func (m *PatchAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PatchAppResponse proto.InternalMessageInfo

type PatchAppsResponse struct {
	BaseTotalResponse    `protobuf:"bytes,1,opt,name=base_total_response,json=baseTotalResponse,proto3,embedded=base_total_response" json:",omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchAppsResponse) Reset()         { *m = PatchAppsResponse{} }
func (m *PatchAppsResponse) String() string { return proto.CompactTextString(m) }
func (*PatchAppsResponse) ProtoMessage()    {}
func (*PatchAppsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{8}
}
func (m *PatchAppsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchAppsResponse.Unmarshal(m, b)
}
func (m *PatchAppsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchAppsResponse.Marshal(b, m, deterministic)
}
func (m *PatchAppsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchAppsResponse.Merge(m, src)
}
func (m *PatchAppsResponse) XXX_Size() int {
	return xxx_messageInfo_PatchAppsResponse.Size(m)
}
func (m *PatchAppsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchAppsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PatchAppsResponse proto.InternalMessageInfo

type AppSourceType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppSourceType) Reset()         { *m = AppSourceType{} }
func (m *AppSourceType) String() string { return proto.CompactTextString(m) }
func (*AppSourceType) ProtoMessage()    {}
func (*AppSourceType) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{9}
}
func (m *AppSourceType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppSourceType.Unmarshal(m, b)
}
func (m *AppSourceType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppSourceType.Marshal(b, m, deterministic)
}
func (m *AppSourceType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppSourceType.Merge(m, src)
}
func (m *AppSourceType) XXX_Size() int {
	return xxx_messageInfo_AppSourceType.Size(m)
}
func (m *AppSourceType) XXX_DiscardUnknown() {
	xxx_messageInfo_AppSourceType.DiscardUnknown(m)
}

var xxx_messageInfo_AppSourceType proto.InternalMessageInfo

type GetAppSourceResponse struct {
	BaseTotalResponse    `protobuf:"bytes,1,opt,name=base_total_response,json=baseTotalResponse,proto3,embedded=base_total_response" json:",omitempty"`
	Data                 map[string]string `protobuf:"bytes,8,opt,name=data,proto3,customtype=map[string]string" json:"data"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAppSourceResponse) Reset()         { *m = GetAppSourceResponse{} }
func (m *GetAppSourceResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppSourceResponse) ProtoMessage()    {}
func (*GetAppSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{10}
}
func (m *GetAppSourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppSourceResponse.Unmarshal(m, b)
}
func (m *GetAppSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppSourceResponse.Marshal(b, m, deterministic)
}
func (m *GetAppSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppSourceResponse.Merge(m, src)
}
func (m *GetAppSourceResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppSourceResponse.Size(m)
}
func (m *GetAppSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppSourceResponse proto.InternalMessageInfo

type AppUser struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	RoleId               string   `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"roleId,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppUser) Reset()         { *m = AppUser{} }
func (m *AppUser) String() string { return proto.CompactTextString(m) }
func (*AppUser) ProtoMessage()    {}
func (*AppUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{11}
}
func (m *AppUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppUser.Unmarshal(m, b)
}
func (m *AppUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppUser.Marshal(b, m, deterministic)
}
func (m *AppUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppUser.Merge(m, src)
}
func (m *AppUser) XXX_Size() int {
	return xxx_messageInfo_AppUser.Size(m)
}
func (m *AppUser) XXX_DiscardUnknown() {
	xxx_messageInfo_AppUser.DiscardUnknown(m)
}

var xxx_messageInfo_AppUser proto.InternalMessageInfo

func (m *AppUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppUser) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *AppUser) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type AppRole struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config               string   `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	IsDefault            bool     `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"isDefault,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppRole) Reset()         { *m = AppRole{} }
func (m *AppRole) String() string { return proto.CompactTextString(m) }
func (*AppRole) ProtoMessage()    {}
func (*AppRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{12}
}
func (m *AppRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppRole.Unmarshal(m, b)
}
func (m *AppRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppRole.Marshal(b, m, deterministic)
}
func (m *AppRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppRole.Merge(m, src)
}
func (m *AppRole) XXX_Size() int {
	return xxx_messageInfo_AppRole.Size(m)
}
func (m *AppRole) XXX_DiscardUnknown() {
	xxx_messageInfo_AppRole.DiscardUnknown(m)
}

var xxx_messageInfo_AppRole proto.InternalMessageInfo

func (m *AppRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AppRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppRole) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *AppRole) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

type CreateAppRequest struct {
	Storage              string                   `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage" valid:"required"`
	Description          string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string                   `protobuf:"bytes,4,opt,name=name,proto3" json:"name" valid:"required"`
	Avatar               string                   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GrantType            models.AppMeta_GrantType `protobuf:"varint,6,opt,name=grant_type,json=grantType,proto3,enum=idas.service.models.AppMeta_GrantType" json:"grantType,omitempty"`
	GrantMode            models.AppMeta_GrantMode `protobuf:"varint,7,opt,name=grant_mode,json=grantMode,proto3,enum=idas.service.models.AppMeta_GrantMode" json:"grantMode,omitempty"`
	User                 []*AppUser               `protobuf:"bytes,8,rep,name=user,proto3" json:"user,omitempty"`
	Role                 []*AppRole               `protobuf:"bytes,9,rep,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CreateAppRequest) Reset()         { *m = CreateAppRequest{} }
func (m *CreateAppRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAppRequest) ProtoMessage()    {}
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{13}
}
func (m *CreateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppRequest.Unmarshal(m, b)
}
func (m *CreateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppRequest.Marshal(b, m, deterministic)
}
func (m *CreateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppRequest.Merge(m, src)
}
func (m *CreateAppRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAppRequest.Size(m)
}
func (m *CreateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppRequest proto.InternalMessageInfo

func (m *CreateAppRequest) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *CreateAppRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateAppRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAppRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *CreateAppRequest) GetGrantType() models.AppMeta_GrantType {
	if m != nil {
		return m.GrantType
	}
	return models.AppMeta_none
}

func (m *CreateAppRequest) GetGrantMode() models.AppMeta_GrantMode {
	if m != nil {
		return m.GrantMode
	}
	return models.AppMeta_manual
}

func (m *CreateAppRequest) GetUser() []*AppUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateAppRequest) GetRole() []*AppRole {
	if m != nil {
		return m.Role
	}
	return nil
}

type UpdateAppRequest struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	Storage              string                   `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage" valid:"required"`
	Description          string                   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string                   `protobuf:"bytes,4,opt,name=name,proto3" json:"name" valid:"required"`
	Avatar               string                   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GrantType            models.AppMeta_GrantType `protobuf:"varint,6,opt,name=grant_type,json=grantType,proto3,enum=idas.service.models.AppMeta_GrantType" json:"grantType,omitempty"`
	GrantMode            models.AppMeta_GrantMode `protobuf:"varint,7,opt,name=grant_mode,json=grantMode,proto3,enum=idas.service.models.AppMeta_GrantMode" json:"grantMode,omitempty"`
	User                 []*AppUser               `protobuf:"bytes,8,rep,name=user,proto3" json:"user,omitempty"`
	Role                 []*AppRole               `protobuf:"bytes,9,rep,name=role,proto3" json:"role,omitempty"`
	Status               models.AppMeta_Status    `protobuf:"varint,10,opt,name=status,proto3,enum=idas.service.models.AppMeta_Status" json:"status"`
	IsDelete             bool                     `protobuf:"varint,11,opt,name=is_delete,json=isDelete,proto3" json:"isDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *UpdateAppRequest) Reset()         { *m = UpdateAppRequest{} }
func (m *UpdateAppRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAppRequest) ProtoMessage()    {}
func (*UpdateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{14}
}
func (m *UpdateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppRequest.Unmarshal(m, b)
}
func (m *UpdateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppRequest.Merge(m, src)
}
func (m *UpdateAppRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAppRequest.Size(m)
}
func (m *UpdateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppRequest proto.InternalMessageInfo

func (m *UpdateAppRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAppRequest) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *UpdateAppRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateAppRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateAppRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UpdateAppRequest) GetGrantType() models.AppMeta_GrantType {
	if m != nil {
		return m.GrantType
	}
	return models.AppMeta_none
}

func (m *UpdateAppRequest) GetGrantMode() models.AppMeta_GrantMode {
	if m != nil {
		return m.GrantMode
	}
	return models.AppMeta_manual
}

func (m *UpdateAppRequest) GetUser() []*AppUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateAppRequest) GetRole() []*AppRole {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *UpdateAppRequest) GetStatus() models.AppMeta_Status {
	if m != nil {
		return m.Status
	}
	return models.AppMeta_unknown
}

func (m *UpdateAppRequest) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

type UpdateAppResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,embedded=base_response" json:",omitempty"`
	Data                 *AppInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAppResponse) Reset()         { *m = UpdateAppResponse{} }
func (m *UpdateAppResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateAppResponse) ProtoMessage()    {}
func (*UpdateAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0659db32fca3fc4, []int{15}
}
func (m *UpdateAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppResponse.Unmarshal(m, b)
}
func (m *UpdateAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppResponse.Marshal(b, m, deterministic)
}
func (m *UpdateAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppResponse.Merge(m, src)
}
func (m *UpdateAppResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateAppResponse.Size(m)
}
func (m *UpdateAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppResponse proto.InternalMessageInfo

func (m *UpdateAppResponse) GetData() *AppInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*AppInfo)(nil), "idas.endpoint.AppInfo")
	proto.RegisterType((*GetAppRequest)(nil), "idas.endpoint.GetAppRequest")
	proto.RegisterType((*DeleteAppRequest)(nil), "idas.endpoint.DeleteAppRequest")
	proto.RegisterType((*GetAppsRequest)(nil), "idas.endpoint.GetAppsRequest")
	proto.RegisterType((*GetAppsResponse)(nil), "idas.endpoint.GetAppsResponse")
	proto.RegisterType((*GetAppResponse)(nil), "idas.endpoint.GetAppResponse")
	proto.RegisterType((*PatchAppRequest)(nil), "idas.endpoint.PatchAppRequest")
	proto.RegisterType((*PatchAppResponse)(nil), "idas.endpoint.PatchAppResponse")
	proto.RegisterType((*PatchAppsResponse)(nil), "idas.endpoint.PatchAppsResponse")
	proto.RegisterType((*AppSourceType)(nil), "idas.endpoint.AppSourceType")
	proto.RegisterType((*GetAppSourceResponse)(nil), "idas.endpoint.GetAppSourceResponse")
	proto.RegisterType((*AppUser)(nil), "idas.endpoint.AppUser")
	proto.RegisterType((*AppRole)(nil), "idas.endpoint.AppRole")
	proto.RegisterType((*CreateAppRequest)(nil), "idas.endpoint.CreateAppRequest")
	proto.RegisterType((*UpdateAppRequest)(nil), "idas.endpoint.UpdateAppRequest")
	proto.RegisterType((*UpdateAppResponse)(nil), "idas.endpoint.UpdateAppResponse")
}

func init() { proto.RegisterFile("v1/apps.proto", fileDescriptor_b0659db32fca3fc4) }

var fileDescriptor_b0659db32fca3fc4 = []byte{
	// 1087 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0x5e, 0xa7, 0x69, 0x9a, 0x4e, 0x37, 0x4d, 0x3a, 0x5b, 0xa5, 0xa6, 0xac, 0xea, 0xc8, 0x48,
	0xa8, 0x5a, 0xed, 0x26, 0xbb, 0xad, 0x84, 0x04, 0xab, 0x95, 0xa8, 0x17, 0xa9, 0x5a, 0xa0, 0x62,
	0xe5, 0xb6, 0x12, 0x62, 0x45, 0xa3, 0x49, 0x3c, 0x4d, 0x47, 0x24, 0x9e, 0x59, 0xcf, 0x24, 0xa2,
	0x87, 0xe5, 0x27, 0x70, 0x44, 0xe2, 0x8a, 0xf8, 0x31, 0x5c, 0x90, 0xe0, 0x9a, 0x83, 0x7f, 0x80,
	0x6f, 0xec, 0x95, 0x0b, 0x9a, 0xb1, 0x1d, 0xdb, 0x69, 0x42, 0xd2, 0x06, 0x15, 0x0e, 0x9c, 0xea,
	0x79, 0xf3, 0xcd, 0x37, 0x9f, 0xc7, 0x6f, 0xbe, 0xf7, 0x52, 0x50, 0x1a, 0x3c, 0x69, 0x20, 0xc6,
	0x78, 0x9d, 0x79, 0x54, 0x50, 0x58, 0x22, 0x0e, 0xe2, 0x75, 0xec, 0x3a, 0x8c, 0x12, 0x57, 0x6c,
	0x6f, 0x76, 0x68, 0x87, 0xaa, 0x99, 0x86, 0x7c, 0x0a, 0x41, 0xdb, 0x72, 0x4d, 0x0b, 0x71, 0x1c,
	0x0d, 0xa1, 0xb8, 0x64, 0x98, 0x37, 0x7a, 0xd4, 0xc1, 0xdd, 0x88, 0xc7, 0x7c, 0xbb, 0x0c, 0x56,
	0x0e, 0x18, 0x7b, 0xe1, 0x9e, 0x53, 0xf8, 0x00, 0xe4, 0x88, 0xa3, 0x6b, 0x35, 0x6d, 0x77, 0xd5,
	0xda, 0x0e, 0x7c, 0x23, 0x47, 0x9c, 0xb7, 0xbe, 0x51, 0x19, 0xa0, 0x2e, 0x71, 0x3e, 0x32, 0x3d,
	0xfc, 0xba, 0x4f, 0x3c, 0xec, 0x98, 0x76, 0x8e, 0x38, 0xf0, 0x31, 0xc8, 0xbb, 0xa8, 0x87, 0xf5,
	0x9c, 0x42, 0xdf, 0x0f, 0x7c, 0x43, 0x8d, 0x27, 0xe2, 0xd5, 0x0c, 0xac, 0x81, 0x35, 0x07, 0xf3,
	0xb6, 0x47, 0x98, 0x20, 0xd4, 0xd5, 0x97, 0xe4, 0x42, 0x3b, 0x1d, 0x82, 0x1f, 0x82, 0x15, 0x2e,
	0xa8, 0x87, 0x3a, 0x58, 0xcf, 0x2b, 0x5a, 0x23, 0xf0, 0x8d, 0x38, 0x34, 0x91, 0x39, 0x9e, 0x84,
	0x55, 0x50, 0x40, 0x03, 0x24, 0x90, 0xa7, 0x2f, 0x2b, 0xde, 0x68, 0x04, 0x4f, 0x00, 0xe8, 0x78,
	0xc8, 0x15, 0x4d, 0xf9, 0xea, 0x7a, 0xa1, 0xa6, 0xed, 0xae, 0xef, 0xbd, 0x5f, 0x57, 0x67, 0xc7,
	0xb1, 0x37, 0x20, 0x6d, 0x5c, 0x8f, 0x8e, 0xe3, 0x80, 0xb1, 0x23, 0x2c, 0x50, 0xfd, 0x50, 0xc2,
	0x4f, 0x2e, 0x19, 0xb6, 0x4a, 0x81, 0x6f, 0xac, 0x76, 0xe2, 0xa1, 0x9d, 0x3c, 0x26, 0xac, 0x72,
	0xad, 0xbe, 0x32, 0x2f, 0xeb, 0x11, 0x75, 0xd2, 0xac, 0x72, 0x68, 0x27, 0x8f, 0xf0, 0x10, 0x14,
	0xb8, 0x40, 0xa2, 0xcf, 0xf5, 0xa2, 0x62, 0x7c, 0xef, 0x6f, 0x19, 0x8f, 0x15, 0xd4, 0x02, 0x81,
	0x6f, 0x44, 0xcb, 0xec, 0xe8, 0x2f, 0x7c, 0x0e, 0xd6, 0xfa, 0xcc, 0x41, 0x02, 0x37, 0x05, 0xe9,
	0x61, 0xfd, 0xae, 0x3a, 0x4b, 0x33, 0xf0, 0x0d, 0x10, 0x86, 0x4f, 0xc8, 0x94, 0x0f, 0x95, 0x9a,
	0x97, 0x24, 0x6d, 0x0f, 0x8f, 0x48, 0x4a, 0x09, 0x49, 0x18, 0x9e, 0x4e, 0x92, 0xcc, 0xc3, 0x67,
	0x60, 0x95, 0xf0, 0xa6, 0x83, 0xbb, 0x58, 0x60, 0x7d, 0xbd, 0xa6, 0xed, 0x16, 0xad, 0x5a, 0xe0,
	0x1b, 0x45, 0xc2, 0x3f, 0x51, 0xb1, 0x89, 0x04, 0xa3, 0x59, 0xf8, 0x00, 0xe4, 0xfb, 0x1c, 0x7b,
	0x7a, 0xb9, 0xb6, 0xb4, 0xbb, 0xb6, 0x57, 0xad, 0x67, 0x72, 0x5e, 0x9e, 0xc4, 0x29, 0xc7, 0x9e,
	0xad, 0x30, 0x12, 0xeb, 0xd1, 0x2e, 0xd6, 0x2b, 0xd3, 0xb0, 0x36, 0xed, 0x62, 0x5b, 0x61, 0xcc,
	0x01, 0x28, 0x1d, 0x62, 0x21, 0x63, 0xf8, 0x75, 0x1f, 0x73, 0x71, 0xad, 0xcc, 0x4f, 0x65, 0x69,
	0xee, 0x7a, 0x59, 0x6a, 0x5e, 0x82, 0x4a, 0xf8, 0x66, 0xb7, 0xbf, 0xf5, 0xf7, 0x1a, 0x58, 0x0f,
	0xdf, 0x99, 0xc7, 0x3b, 0xb7, 0xc0, 0x86, 0x34, 0x87, 0x66, 0x97, 0x70, 0xd1, 0xf4, 0xc2, 0xa0,
	0x12, 0xb2, 0xb6, 0xb7, 0x33, 0x76, 0x7c, 0x16, 0xe2, 0xf8, 0x73, 0xc2, 0x45, 0xb4, 0xd4, 0xaa,
	0xfe, 0xe2, 0x1b, 0x77, 0x7e, 0xf3, 0x0d, 0x4d, 0xe6, 0xc3, 0x43, 0xda, 0x23, 0x02, 0xf7, 0x98,
	0xb8, 0xb4, 0xcb, 0xad, 0x2c, 0x10, 0xea, 0x63, 0x8a, 0x13, 0x41, 0x3f, 0x6b, 0xa0, 0x3c, 0x12,
	0xc4, 0x19, 0x75, 0x39, 0x86, 0x18, 0xc0, 0xb4, 0xa2, 0x30, 0x1a, 0x49, 0x32, 0xa6, 0x4a, 0x0a,
	0x61, 0x53, 0x35, 0x55, 0x5a, 0x63, 0x48, 0x99, 0x2a, 0x0e, 0x12, 0x48, 0xcf, 0x4d, 0x4b, 0x15,
	0xe9, 0x86, 0xb6, 0xc2, 0x98, 0x3f, 0x8c, 0xce, 0x6d, 0xb4, 0xfc, 0x4b, 0x50, 0x52, 0x2a, 0xc7,
	0x04, 0xbe, 0x3b, 0x41, 0xe0, 0x4c, 0x71, 0x77, 0x5b, 0x29, 0x54, 0x4a, 0x98, 0x36, 0x53, 0xd8,
	0x1f, 0xcb, 0xa0, 0xfc, 0x12, 0x89, 0xf6, 0xc5, 0xad, 0xe7, 0x12, 0x7c, 0x38, 0xc1, 0xc9, 0x2d,
	0x30, 0x54, 0x46, 0xe4, 0x11, 0xb7, 0x93, 0x75, 0xf5, 0x9d, 0xa8, 0x52, 0xe4, 0xaf, 0xc0, 0xc2,
	0xba, 0x60, 0x66, 0xad, 0x3b, 0x83, 0x88, 0x6d, 0xfc, 0x27, 0x6d, 0x01, 0x1f, 0x7f, 0x35, 0xf4,
	0x8d, 0x8f, 0x3b, 0x44, 0x5c, 0xf4, 0x5b, 0xf5, 0x36, 0xed, 0x35, 0x8e, 0x48, 0xdb, 0xa3, 0x5f,
	0x30, 0xfe, 0xa8, 0xed, 0x36, 0x24, 0x43, 0x83, 0x7d, 0xd3, 0x69, 0x44, 0x2c, 0x8d, 0x2c, 0x4b,
	0x73, 0xc4, 0x12, 0xf8, 0xc6, 0xbd, 0x51, 0x01, 0x48, 0x7d, 0xc0, 0x54, 0x55, 0x48, 0x44, 0xde,
	0xa0, 0x2c, 0xfc, 0xb3, 0x22, 0x25, 0xe5, 0x15, 0x91, 0xaa, 0xc8, 0x7c, 0x77, 0x93, 0x22, 0x73,
	0x30, 0xf4, 0x8d, 0x67, 0x37, 0x14, 0x77, 0x9c, 0xad, 0x4d, 0x4f, 0xaf, 0x56, 0x84, 0x9d, 0xa1,
	0x6f, 0xe4, 0x5b, 0x94, 0x76, 0x03, 0xdf, 0x80, 0xb1, 0xf7, 0xa7, 0xd4, 0x8f, 0xea, 0x81, 0x79,
	0x06, 0x2a, 0x49, 0xca, 0x47, 0x77, 0xe6, 0xd3, 0x1b, 0xdc, 0xc6, 0x62, 0x7c, 0x1b, 0xb3, 0xf7,
	0xcf, 0x7c, 0x03, 0x36, 0x62, 0xfe, 0xc4, 0x94, 0x2e, 0xc0, 0x3d, 0xb5, 0x81, 0xa0, 0x02, 0x75,
	0xc7, 0xb7, 0xa9, 0x4d, 0xd8, 0xe6, 0x44, 0x02, 0x67, 0xde, 0x7c, 0xe5, 0xbd, 0x19, 0xa8, 0x59,
	0x06, 0xa5, 0x03, 0xc6, 0x8e, 0x69, 0xdf, 0x6b, 0x63, 0xf9, 0x39, 0xcd, 0x5f, 0x35, 0xb0, 0x19,
	0x9a, 0x4f, 0x18, 0xbc, 0x7d, 0x4d, 0xf0, 0xb3, 0xc8, 0x92, 0x8a, 0x8a, 0xfa, 0xfe, 0x55, 0x4b,
	0x4a, 0xe4, 0x5a, 0xef, 0x48, 0xda, 0xa1, 0x6f, 0x6c, 0xf4, 0x10, 0x7b, 0x15, 0xde, 0xe0, 0xaf,
	0xe3, 0xab, 0xae, 0x3c, 0xeb, 0x5b, 0xd5, 0x6b, 0x9e, 0x86, 0xe5, 0x7a, 0x7e, 0xab, 0x7a, 0x04,
	0x56, 0x64, 0xd9, 0x6e, 0x12, 0x27, 0xb2, 0xaa, 0xcd, 0xc0, 0x37, 0x2a, 0x32, 0xf4, 0xc2, 0x49,
	0xa9, 0x2f, 0x84, 0x11, 0x08, 0xa3, 0x4e, 0x20, 0xec, 0x30, 0xc3, 0x8a, 0xff, 0x46, 0xed, 0x2c,
	0x5b, 0x00, 0xb8, 0x9e, 0xec, 0xac, 0xd8, 0x61, 0xba, 0x93, 0x8d, 0x3c, 0xa9, 0x0a, 0x0a, 0x6d,
	0xea, 0x9e, 0x93, 0x4e, 0x44, 0x12, 0x8d, 0xe0, 0x07, 0x00, 0xa8, 0xec, 0x3d, 0x47, 0xfd, 0xae,
	0x50, 0x8e, 0x56, 0xb4, 0xb6, 0xe4, 0xad, 0x93, 0x29, 0xaa, 0x82, 0xe9, 0x5b, 0x37, 0x0a, 0x9a,
	0xbf, 0x2f, 0x81, 0xca, 0x73, 0xd5, 0x16, 0xa5, 0xdc, 0x7a, 0x01, 0x07, 0x9e, 0xdd, 0x4b, 0x3f,
	0xce, 0xb8, 0xee, 0x3c, 0xfd, 0xf9, 0xb4, 0x16, 0xfa, 0x6c, 0x01, 0xeb, 0xdd, 0x9a, 0xc3, 0x36,
	0xcf, 0x16, 0x70, 0xcd, 0xad, 0x39, 0x1c, 0x2f, 0x6e, 0x22, 0x8b, 0xd7, 0x68, 0x22, 0x57, 0xe7,
	0x68, 0x22, 0xff, 0xcc, 0x83, 0xca, 0xa9, 0xea, 0x97, 0x6f, 0xbf, 0x02, 0xff, 0xff, 0xfd, 0xff,
	0xf5, 0xef, 0x9f, 0xfa, 0xb9, 0x06, 0x16, 0xfb, 0xb9, 0xb6, 0x9f, 0x2e, 0x89, 0x6b, 0xca, 0x53,
	0xaa, 0x33, 0x4b, 0xe1, 0x8f, 0x1a, 0xd8, 0x48, 0x65, 0xdf, 0x7f, 0xa9, 0x35, 0xb5, 0xf6, 0xbf,
	0x7a, 0x32, 0xab, 0x59, 0x88, 0x57, 0x3e, 0x8d, 0x1f, 0x5e, 0xde, 0x69, 0x15, 0xd4, 0x7f, 0x24,
	0xf6, 0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x84, 0xc3, 0xc9, 0xea, 0x10, 0x00, 0x00,
}
