// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: v1/base.proto

package endpoint

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BaseListRequest struct {
	PageSize             int64    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"pageSize,omitempty"`
	Current              int64    `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	Keywords             string   `protobuf:"bytes,3,opt,name=keywords,proto3" json:"keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseListRequest) Reset()         { *m = BaseListRequest{} }
func (m *BaseListRequest) String() string { return proto.CompactTextString(m) }
func (*BaseListRequest) ProtoMessage()    {}
func (*BaseListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cadb02d0b0a23f3, []int{0}
}
func (m *BaseListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseListRequest.Unmarshal(m, b)
}
func (m *BaseListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseListRequest.Marshal(b, m, deterministic)
}
func (m *BaseListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseListRequest.Merge(m, src)
}
func (m *BaseListRequest) XXX_Size() int {
	return xxx_messageInfo_BaseListRequest.Size(m)
}
func (m *BaseListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseListRequest proto.InternalMessageInfo

func (m *BaseListRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *BaseListRequest) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *BaseListRequest) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

type ErrorType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorType) Reset()         { *m = ErrorType{} }
func (m *ErrorType) String() string { return proto.CompactTextString(m) }
func (*ErrorType) ProtoMessage()    {}
func (*ErrorType) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cadb02d0b0a23f3, []int{1}
}
func (m *ErrorType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorType.Unmarshal(m, b)
}
func (m *ErrorType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorType.Marshal(b, m, deterministic)
}
func (m *ErrorType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorType.Merge(m, src)
}
func (m *ErrorType) XXX_Size() int {
	return xxx_messageInfo_ErrorType.Size(m)
}
func (m *ErrorType) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorType.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorType proto.InternalMessageInfo

type BaseResponse struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"traceId" valid:"required"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success" valid:"required"`
	ErrorCode            string   `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"errorMessage,omitempty"`
	Error                error    `protobuf:"bytes,5,opt,name=error,proto3,customtype=error" json:"-"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cadb02d0b0a23f3, []int{2}
}
func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (m *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(m, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *BaseResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *BaseResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *BaseResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type BaseTotalResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,embedded=base_response" json:",omitempty"`
	Total                int64    `protobuf:"varint,7,opt,name=total,proto3" json:"total"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseTotalResponse) Reset()         { *m = BaseTotalResponse{} }
func (m *BaseTotalResponse) String() string { return proto.CompactTextString(m) }
func (*BaseTotalResponse) ProtoMessage()    {}
func (*BaseTotalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cadb02d0b0a23f3, []int{3}
}
func (m *BaseTotalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseTotalResponse.Unmarshal(m, b)
}
func (m *BaseTotalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseTotalResponse.Marshal(b, m, deterministic)
}
func (m *BaseTotalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseTotalResponse.Merge(m, src)
}
func (m *BaseTotalResponse) XXX_Size() int {
	return xxx_messageInfo_BaseTotalResponse.Size(m)
}
func (m *BaseTotalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseTotalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseTotalResponse proto.InternalMessageInfo

func (m *BaseTotalResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type BaseListResponse struct {
	BaseTotalResponse    `protobuf:"bytes,1,opt,name=base_total_response,json=baseTotalResponse,proto3,embedded=base_total_response" json:",omitempty"`
	Current              int64    `protobuf:"varint,2,opt,name=current,proto3" json:"current"`
	PageSize             int64    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"pageSize"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseListResponse) Reset()         { *m = BaseListResponse{} }
func (m *BaseListResponse) String() string { return proto.CompactTextString(m) }
func (*BaseListResponse) ProtoMessage()    {}
func (*BaseListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cadb02d0b0a23f3, []int{4}
}
func (m *BaseListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseListResponse.Unmarshal(m, b)
}
func (m *BaseListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseListResponse.Marshal(b, m, deterministic)
}
func (m *BaseListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseListResponse.Merge(m, src)
}
func (m *BaseListResponse) XXX_Size() int {
	return xxx_messageInfo_BaseListResponse.Size(m)
}
func (m *BaseListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseListResponse proto.InternalMessageInfo

func (m *BaseListResponse) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *BaseListResponse) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func init() {
	proto.RegisterType((*BaseListRequest)(nil), "idas.endpoint.BaseListRequest")
	proto.RegisterType((*ErrorType)(nil), "idas.endpoint.ErrorType")
	proto.RegisterType((*BaseResponse)(nil), "idas.endpoint.BaseResponse")
	proto.RegisterType((*BaseTotalResponse)(nil), "idas.endpoint.BaseTotalResponse")
	proto.RegisterType((*BaseListResponse)(nil), "idas.endpoint.BaseListResponse")
}

func init() { proto.RegisterFile("v1/base.proto", fileDescriptor_7cadb02d0b0a23f3) }

var fileDescriptor_7cadb02d0b0a23f3 = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x97, 0x95, 0xd2, 0xc6, 0x6d, 0xc5, 0xe6, 0xa1, 0x12, 0x95, 0x83, 0xab, 0x48, 0x48,
	0x45, 0x62, 0x8d, 0xb6, 0x4a, 0x48, 0x8c, 0x03, 0x52, 0x10, 0x07, 0x24, 0x26, 0x50, 0xd8, 0x01,
	0x71, 0xa9, 0xd2, 0xe4, 0x55, 0x66, 0x6d, 0xad, 0x33, 0xdb, 0x19, 0xea, 0xc4, 0x67, 0xe0, 0x43,
	0x71, 0xe2, 0x84, 0x38, 0x73, 0xf0, 0x07, 0xc8, 0x91, 0x4f, 0x80, 0xec, 0xfc, 0x69, 0x56, 0xc6,
	0x29, 0xf6, 0xf3, 0xbe, 0x8f, 0xfc, 0xf3, 0xeb, 0x27, 0x68, 0x70, 0x7d, 0xe4, 0x2d, 0x42, 0x01,
	0xd3, 0x94, 0x33, 0xc9, 0xf0, 0x80, 0xc6, 0xa1, 0x98, 0xc2, 0x2a, 0x4e, 0x19, 0x5d, 0xc9, 0xd1,
	0xc3, 0x84, 0x25, 0xcc, 0x54, 0x3c, 0xbd, 0x2a, 0x9a, 0xdc, 0xaf, 0xe8, 0x81, 0x1f, 0x0a, 0x78,
	0x47, 0x85, 0x0c, 0xe0, 0x2a, 0x03, 0x21, 0xf1, 0x0c, 0xd9, 0x69, 0x98, 0xc0, 0x5c, 0xd0, 0x1b,
	0x70, 0xac, 0xb1, 0x35, 0x69, 0xf9, 0xc3, 0x5c, 0x11, 0xac, 0xc5, 0x8f, 0xf4, 0x06, 0x9e, 0xb1,
	0x25, 0x95, 0xb0, 0x4c, 0xe5, 0x3a, 0xe8, 0x56, 0x1a, 0x76, 0x50, 0x27, 0xca, 0x38, 0x87, 0x95,
	0x74, 0x76, 0xb5, 0x25, 0xa8, 0xb6, 0x78, 0x84, 0xba, 0x17, 0xb0, 0xfe, 0xc2, 0x78, 0x2c, 0x9c,
	0xd6, 0xd8, 0x9a, 0xd8, 0x41, 0xbd, 0x77, 0x7b, 0xc8, 0x7e, 0xc3, 0x39, 0xe3, 0x67, 0xeb, 0x14,
	0xdc, 0xef, 0xbb, 0xa8, 0xaf, 0x59, 0x02, 0x10, 0x29, 0x5b, 0x09, 0xc0, 0x27, 0xa8, 0x2b, 0x79,
	0x18, 0xc1, 0x9c, 0xc6, 0x86, 0xc3, 0xf6, 0x49, 0xae, 0x48, 0xc7, 0x68, 0x6f, 0xe3, 0x3f, 0x8a,
	0xec, 0x5d, 0x87, 0x97, 0x34, 0x3e, 0x71, 0x39, 0x5c, 0x65, 0x94, 0x43, 0xec, 0x06, 0x55, 0x11,
	0xbf, 0x40, 0x1d, 0x91, 0x45, 0x11, 0x08, 0x61, 0x78, 0xba, 0x85, 0xb5, 0x94, 0xee, 0xb6, 0x96,
	0x45, 0xfc, 0x1c, 0x21, 0xd0, 0x50, 0xf3, 0x88, 0xc5, 0x50, 0x20, 0xfb, 0x8f, 0x72, 0x45, 0x0e,
	0x8c, 0xfa, 0x9a, 0xc5, 0xcd, 0x09, 0xd8, 0xb5, 0x88, 0x5f, 0xa1, 0x41, 0xe1, 0x5b, 0x82, 0x10,
	0x61, 0x02, 0xce, 0x3d, 0x63, 0x1d, 0xe5, 0x8a, 0x0c, 0x4d, 0xe1, 0xb4, 0xd0, 0x1b, 0xee, 0x7e,
	0x53, 0xc7, 0x3e, 0x6a, 0x9b, 0xbd, 0xd3, 0x1e, 0x5b, 0x93, 0xde, 0xb1, 0x33, 0xbd, 0xf5, 0x80,
	0xd3, 0x7a, 0x52, 0x3e, 0xfe, 0xa1, 0xc8, 0xce, 0x6f, 0x45, 0x8a, 0xf6, 0x5c, 0x11, 0xeb, 0x30,
	0x28, 0xd6, 0xee, 0x37, 0x0b, 0xed, 0xeb, 0x21, 0x9e, 0x31, 0x19, 0x5e, 0xd6, 0x93, 0xfc, 0x84,
	0x06, 0x3a, 0x18, 0x73, 0x5e, 0x0a, 0x66, 0x9c, 0xbd, 0xe3, 0xc7, 0x5b, 0x27, 0x34, 0xa7, 0xef,
	0x0f, 0xf5, 0x21, 0xbf, 0x14, 0xb1, 0x72, 0x45, 0x50, 0x93, 0x79, 0xd1, 0x7c, 0x23, 0x82, 0xda,
	0x52, 0x1f, 0xe5, 0x74, 0x4c, 0x50, 0xec, 0x5c, 0x91, 0x42, 0x08, 0x8a, 0x8f, 0xfb, 0xd3, 0x42,
	0x7b, 0x9b, 0x84, 0x95, 0xae, 0x73, 0x74, 0x60, 0x78, 0x4c, 0xcb, 0x36, 0xd5, 0xf8, 0x0e, 0xaa,
	0x5b, 0xd7, 0xf9, 0x2f, 0xda, 0xfe, 0xe2, 0x9f, 0x9b, 0x3f, 0xd9, 0xca, 0xa5, 0xdf, 0xd3, 0x39,
	0x28, 0xa5, 0x4d, 0x48, 0x9f, 0x36, 0x33, 0xdf, 0x32, 0x8d, 0xfd, 0x5c, 0x91, 0x3a, 0xdf, 0x9b,
	0xa4, 0xfb, 0xb3, 0xcf, 0x47, 0x09, 0x95, 0xe7, 0xd9, 0x62, 0x1a, 0xb1, 0xa5, 0x77, 0x4a, 0x23,
	0xce, 0xde, 0xa7, 0xe2, 0x30, 0x5a, 0x79, 0x1a, 0xdb, 0x4b, 0x2f, 0x12, 0xaf, 0x42, 0x7f, 0x59,
	0x2d, 0x3e, 0xec, 0x2c, 0xee, 0x9b, 0xff, 0x6d, 0xf6, 0x37, 0x00, 0x00, 0xff, 0xff, 0x84, 0x29,
	0x9f, 0xe0, 0xa5, 0x03, 0x00, 0x00,
}
