// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: endpoints/oauth2.proto

package endpoint

import (
	fmt "fmt"
	github_com_MicroOps_cn_idas_pkg_service_models "github.com/MicroOps-cn/idas/pkg/service/models"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// @sync-to-public:public/src/services/idas/enums.ts:OAuthGrantType
type OAuthGrantType int32

const (
	OAuthGrantType_refresh_token      OAuthGrantType = 0
	OAuthGrantType_authorization_code OAuthGrantType = 1
	OAuthGrantType_password           OAuthGrantType = 2
	OAuthGrantType_client_credentials OAuthGrantType = 3
)

var OAuthGrantType_name = map[int32]string{
	0: "refresh_token",
	1: "authorization_code",
	2: "password",
	3: "client_credentials",
}

var OAuthGrantType_value = map[string]int32{
	"refresh_token":      0,
	"authorization_code": 1,
	"password":           2,
	"client_credentials": 3,
}

func (x OAuthGrantType) String() string {
	return proto.EnumName(OAuthGrantType_name, int32(x))
}

func (OAuthGrantType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{0}
}

type OAuthTokenType int32

const (
	OAuthTokenType_Bearer OAuthTokenType = 0
	OAuthTokenType_Mac    OAuthTokenType = 1
	OAuthTokenType_Cookie OAuthTokenType = 2
)

var OAuthTokenType_name = map[int32]string{
	0: "Bearer",
	1: "Mac",
	2: "Cookie",
}

var OAuthTokenType_value = map[string]int32{
	"Bearer": 0,
	"Mac":    1,
	"Cookie": 2,
}

func (x OAuthTokenType) String() string {
	return proto.EnumName(OAuthTokenType_name, int32(x))
}

func (OAuthTokenType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{1}
}

// @sync-to-public:public/src/services/idas/enums.ts:ResponseType
type OAuthAuthorizeRequest_ResponseType int32

const (
	OAuthAuthorizeRequest_none     OAuthAuthorizeRequest_ResponseType = 0
	OAuthAuthorizeRequest_code     OAuthAuthorizeRequest_ResponseType = 1
	OAuthAuthorizeRequest_token    OAuthAuthorizeRequest_ResponseType = 2
	OAuthAuthorizeRequest_id_token OAuthAuthorizeRequest_ResponseType = 3
)

var OAuthAuthorizeRequest_ResponseType_name = map[int32]string{
	0: "none",
	1: "code",
	2: "token",
	3: "id_token",
}

var OAuthAuthorizeRequest_ResponseType_value = map[string]int32{
	"none":     0,
	"code":     1,
	"token":    2,
	"id_token": 3,
}

func (x OAuthAuthorizeRequest_ResponseType) String() string {
	return proto.EnumName(OAuthAuthorizeRequest_ResponseType_name, int32(x))
}

func (OAuthAuthorizeRequest_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{1, 0}
}

type OAuthAuthorizeRequest_CodeChallengeMethod int32

const (
	OAuthAuthorizeRequest_plain OAuthAuthorizeRequest_CodeChallengeMethod = 0
	OAuthAuthorizeRequest_S256  OAuthAuthorizeRequest_CodeChallengeMethod = 1
)

var OAuthAuthorizeRequest_CodeChallengeMethod_name = map[int32]string{
	0: "plain",
	1: "S256",
}

var OAuthAuthorizeRequest_CodeChallengeMethod_value = map[string]int32{
	"plain": 0,
	"S256":  1,
}

func (x OAuthAuthorizeRequest_CodeChallengeMethod) String() string {
	return proto.EnumName(OAuthAuthorizeRequest_CodeChallengeMethod_name, int32(x))
}

func (OAuthAuthorizeRequest_CodeChallengeMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{1, 1}
}

type OAuthTokenResponse struct {
	AccessToken          string            `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType            OAuthTokenType    `protobuf:"varint,2,opt,name=token_type,json=tokenType,proto3,enum=idas.oauth2.OAuthTokenType" json:"token_type"`
	ExpiresIn            int               `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3,customtype=int" json:"expires_in"`
	RefreshToken         string            `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Error                string            `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	IdToken              string            `protobuf:"bytes,6,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	Headers              map[string]string `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cookies              []string          `protobuf:"bytes,8,rep,name=cookies,proto3" json:"cookies,omitempty"`
	NextMethod           []LoginType       `protobuf:"varint,9,rep,packed,name=next_method,json=nextMethod,proto3,enum=idas.endpoint.LoginType" json:"next_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OAuthTokenResponse) Reset()         { *m = OAuthTokenResponse{} }
func (m *OAuthTokenResponse) String() string { return proto.CompactTextString(m) }
func (*OAuthTokenResponse) ProtoMessage()    {}
func (*OAuthTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{0}
}
func (m *OAuthTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthTokenResponse.Unmarshal(m, b)
}
func (m *OAuthTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthTokenResponse.Marshal(b, m, deterministic)
}
func (m *OAuthTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthTokenResponse.Merge(m, src)
}
func (m *OAuthTokenResponse) XXX_Size() int {
	return xxx_messageInfo_OAuthTokenResponse.Size(m)
}
func (m *OAuthTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthTokenResponse proto.InternalMessageInfo

func (m *OAuthTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *OAuthTokenResponse) GetTokenType() OAuthTokenType {
	if m != nil {
		return m.TokenType
	}
	return OAuthTokenType_Bearer
}

func (m *OAuthTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *OAuthTokenResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *OAuthTokenResponse) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

func (m *OAuthTokenResponse) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *OAuthTokenResponse) GetCookies() []string {
	if m != nil {
		return m.Cookies
	}
	return nil
}

func (m *OAuthTokenResponse) GetNextMethod() []LoginType {
	if m != nil {
		return m.NextMethod
	}
	return nil
}

type OAuthAuthorizeRequest struct {
	ResponseType         *OAuthAuthorizeRequest_ResponseTypes      `protobuf:"bytes,1,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	ClientId             string                                    `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RedirectUri          string                                    `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	State                string                                    `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Scope                string                                    `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	AccessType           string                                    `protobuf:"bytes,6,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`
	CodeChallenge        string                                    `protobuf:"bytes,7,opt,name=code_challenge,json=codeChallenge,proto3" json:"code_challenge,omitempty"`
	CodeChallengeMethod  OAuthAuthorizeRequest_CodeChallengeMethod `protobuf:"varint,8,opt,name=code_challenge_method,json=codeChallengeMethod,proto3,enum=idas.oauth2.OAuthAuthorizeRequest_CodeChallengeMethod" json:"code_challenge_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *OAuthAuthorizeRequest) Reset()         { *m = OAuthAuthorizeRequest{} }
func (m *OAuthAuthorizeRequest) String() string { return proto.CompactTextString(m) }
func (*OAuthAuthorizeRequest) ProtoMessage()    {}
func (*OAuthAuthorizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{1}
}
func (m *OAuthAuthorizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthAuthorizeRequest.Unmarshal(m, b)
}
func (m *OAuthAuthorizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthAuthorizeRequest.Marshal(b, m, deterministic)
}
func (m *OAuthAuthorizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthAuthorizeRequest.Merge(m, src)
}
func (m *OAuthAuthorizeRequest) XXX_Size() int {
	return xxx_messageInfo_OAuthAuthorizeRequest.Size(m)
}
func (m *OAuthAuthorizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthAuthorizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthAuthorizeRequest proto.InternalMessageInfo

func (m *OAuthAuthorizeRequest) GetResponseType() *OAuthAuthorizeRequest_ResponseTypes {
	if m != nil {
		return m.ResponseType
	}
	return nil
}

func (m *OAuthAuthorizeRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *OAuthAuthorizeRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *OAuthAuthorizeRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *OAuthAuthorizeRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *OAuthAuthorizeRequest) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

func (m *OAuthAuthorizeRequest) GetCodeChallenge() string {
	if m != nil {
		return m.CodeChallenge
	}
	return ""
}

func (m *OAuthAuthorizeRequest) GetCodeChallengeMethod() OAuthAuthorizeRequest_CodeChallengeMethod {
	if m != nil {
		return m.CodeChallengeMethod
	}
	return OAuthAuthorizeRequest_plain
}

type OAuthAuthorizeRequest_ResponseTypes struct {
	Types                []OAuthAuthorizeRequest_ResponseType `protobuf:"varint,1,rep,packed,name=types,proto3,enum=idas.oauth2.OAuthAuthorizeRequest_ResponseType" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *OAuthAuthorizeRequest_ResponseTypes) Reset()         { *m = OAuthAuthorizeRequest_ResponseTypes{} }
func (m *OAuthAuthorizeRequest_ResponseTypes) String() string { return proto.CompactTextString(m) }
func (*OAuthAuthorizeRequest_ResponseTypes) ProtoMessage()    {}
func (*OAuthAuthorizeRequest_ResponseTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{1, 0}
}
func (m *OAuthAuthorizeRequest_ResponseTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthAuthorizeRequest_ResponseTypes.Unmarshal(m, b)
}
func (m *OAuthAuthorizeRequest_ResponseTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthAuthorizeRequest_ResponseTypes.Marshal(b, m, deterministic)
}
func (m *OAuthAuthorizeRequest_ResponseTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthAuthorizeRequest_ResponseTypes.Merge(m, src)
}
func (m *OAuthAuthorizeRequest_ResponseTypes) XXX_Size() int {
	return xxx_messageInfo_OAuthAuthorizeRequest_ResponseTypes.Size(m)
}
func (m *OAuthAuthorizeRequest_ResponseTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthAuthorizeRequest_ResponseTypes.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthAuthorizeRequest_ResponseTypes proto.InternalMessageInfo

func (m *OAuthAuthorizeRequest_ResponseTypes) GetTypes() []OAuthAuthorizeRequest_ResponseType {
	if m != nil {
		return m.Types
	}
	return nil
}

type OAuthTokenRequest struct {
	GrantType            OAuthGrantType                                         `protobuf:"varint,1,opt,name=grant_type,json=grantType,proto3,enum=idas.oauth2.OAuthGrantType" json:"grant_type,omitempty"`
	Code                 string                                                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	RedirectUri          string                                                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	ClientId             string                                                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         github_com_MicroOps_cn_idas_pkg_service_models.Secret  `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3,customtype=github.com/MicroOps-cn/idas/pkg/service/models.Secret" json:"client_secret"`
	Username             string                                                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Password             github_com_MicroOps_cn_idas_pkg_service_models.Secret  `protobuf:"bytes,7,opt,name=password,proto3,customtype=github.com/MicroOps-cn/idas/pkg/service/models.Secret" json:"password"`
	RefreshToken         *github_com_MicroOps_cn_idas_pkg_service_models.Secret `protobuf:"bytes,8,opt,name=refresh_token,json=refreshToken,proto3,customtype=github.com/MicroOps-cn/idas/pkg/service/models.Secret" json:"refresh_token,omitempty"`
	State                string                                                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	DisableRefreshToken  bool                                                   `protobuf:"varint,10,opt,name=disable_refresh_token,json=disableRefreshToken,proto3" json:"disable_refresh_token,omitempty"`
	TokenType            OAuthTokenType                                         `protobuf:"varint,11,opt,name=token_type,json=tokenType,proto3,enum=idas.oauth2.OAuthTokenType" json:"token_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *OAuthTokenRequest) Reset()         { *m = OAuthTokenRequest{} }
func (m *OAuthTokenRequest) String() string { return proto.CompactTextString(m) }
func (*OAuthTokenRequest) ProtoMessage()    {}
func (*OAuthTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{2}
}
func (m *OAuthTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthTokenRequest.Unmarshal(m, b)
}
func (m *OAuthTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthTokenRequest.Marshal(b, m, deterministic)
}
func (m *OAuthTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthTokenRequest.Merge(m, src)
}
func (m *OAuthTokenRequest) XXX_Size() int {
	return xxx_messageInfo_OAuthTokenRequest.Size(m)
}
func (m *OAuthTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthTokenRequest proto.InternalMessageInfo

func (m *OAuthTokenRequest) GetGrantType() OAuthGrantType {
	if m != nil {
		return m.GrantType
	}
	return OAuthGrantType_refresh_token
}

func (m *OAuthTokenRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OAuthTokenRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *OAuthTokenRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *OAuthTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *OAuthTokenRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *OAuthTokenRequest) GetDisableRefreshToken() bool {
	if m != nil {
		return m.DisableRefreshToken
	}
	return false
}

func (m *OAuthTokenRequest) GetTokenType() OAuthTokenType {
	if m != nil {
		return m.TokenType
	}
	return OAuthTokenType_Bearer
}

type OIDCWellKnownResponse struct {
	Issuer                            string   `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	AuthorizationEndpoint             string   `protobuf:"bytes,2,opt,name=authorization_endpoint,json=authorizationEndpoint,proto3" json:"authorization_endpoint,omitempty"`
	DeviceAuthorizationEndpoint       string   `protobuf:"bytes,3,opt,name=device_authorization_endpoint,json=deviceAuthorizationEndpoint,proto3" json:"device_authorization_endpoint,omitempty"`
	TokenEndpoint                     string   `protobuf:"bytes,4,opt,name=token_endpoint,json=tokenEndpoint,proto3" json:"token_endpoint,omitempty"`
	UserinfoEndpoint                  string   `protobuf:"bytes,5,opt,name=userinfo_endpoint,json=userinfoEndpoint,proto3" json:"userinfo_endpoint,omitempty"`
	RevocationEndpoint                string   `protobuf:"bytes,6,opt,name=revocation_endpoint,json=revocationEndpoint,proto3" json:"revocation_endpoint,omitempty"`
	JwksUri                           string   `protobuf:"bytes,7,opt,name=jwks_uri,json=jwksUri,proto3" json:"jwks_uri,omitempty"`
	ResponseTypesSupported            []string `protobuf:"bytes,8,rep,name=response_types_supported,json=responseTypesSupported,proto3" json:"response_types_supported,omitempty"`
	SubjectTypesSupported             []string `protobuf:"bytes,9,rep,name=subject_types_supported,json=subjectTypesSupported,proto3" json:"subject_types_supported,omitempty"`
	IdTokenSigningAlgValuesSupported  []string `protobuf:"bytes,10,rep,name=id_token_signing_alg_values_supported,json=idTokenSigningAlgValuesSupported,proto3" json:"id_token_signing_alg_values_supported,omitempty"`
	ScopesSupported                   []string `protobuf:"bytes,11,rep,name=scopes_supported,json=scopesSupported,proto3" json:"scopes_supported,omitempty"`
	TokenEndpointAuthMethodsSupported []string `protobuf:"bytes,12,rep,name=token_endpoint_auth_methods_supported,json=tokenEndpointAuthMethodsSupported,proto3" json:"token_endpoint_auth_methods_supported,omitempty"`
	ClaimsSupported                   []string `protobuf:"bytes,13,rep,name=claims_supported,json=claimsSupported,proto3" json:"claims_supported,omitempty"`
	CodeChallengeMethodsSupported     []string `protobuf:"bytes,14,rep,name=code_challenge_methods_supported,json=codeChallengeMethodsSupported,proto3" json:"code_challenge_methods_supported,omitempty"`
	GrantTypesSupported               []string `protobuf:"bytes,15,rep,name=grant_types_supported,json=grantTypesSupported,proto3" json:"grant_types_supported,omitempty"`
	XXX_NoUnkeyedLiteral              struct{} `json:"-"`
	XXX_unrecognized                  []byte   `json:"-"`
	XXX_sizecache                     int32    `json:"-"`
}

func (m *OIDCWellKnownResponse) Reset()         { *m = OIDCWellKnownResponse{} }
func (m *OIDCWellKnownResponse) String() string { return proto.CompactTextString(m) }
func (*OIDCWellKnownResponse) ProtoMessage()    {}
func (*OIDCWellKnownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{3}
}
func (m *OIDCWellKnownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OIDCWellKnownResponse.Unmarshal(m, b)
}
func (m *OIDCWellKnownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OIDCWellKnownResponse.Marshal(b, m, deterministic)
}
func (m *OIDCWellKnownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OIDCWellKnownResponse.Merge(m, src)
}
func (m *OIDCWellKnownResponse) XXX_Size() int {
	return xxx_messageInfo_OIDCWellKnownResponse.Size(m)
}
func (m *OIDCWellKnownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OIDCWellKnownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OIDCWellKnownResponse proto.InternalMessageInfo

func (m *OIDCWellKnownResponse) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *OIDCWellKnownResponse) GetAuthorizationEndpoint() string {
	if m != nil {
		return m.AuthorizationEndpoint
	}
	return ""
}

func (m *OIDCWellKnownResponse) GetDeviceAuthorizationEndpoint() string {
	if m != nil {
		return m.DeviceAuthorizationEndpoint
	}
	return ""
}

func (m *OIDCWellKnownResponse) GetTokenEndpoint() string {
	if m != nil {
		return m.TokenEndpoint
	}
	return ""
}

func (m *OIDCWellKnownResponse) GetUserinfoEndpoint() string {
	if m != nil {
		return m.UserinfoEndpoint
	}
	return ""
}

func (m *OIDCWellKnownResponse) GetRevocationEndpoint() string {
	if m != nil {
		return m.RevocationEndpoint
	}
	return ""
}

func (m *OIDCWellKnownResponse) GetJwksUri() string {
	if m != nil {
		return m.JwksUri
	}
	return ""
}

func (m *OIDCWellKnownResponse) GetResponseTypesSupported() []string {
	if m != nil {
		return m.ResponseTypesSupported
	}
	return nil
}

func (m *OIDCWellKnownResponse) GetSubjectTypesSupported() []string {
	if m != nil {
		return m.SubjectTypesSupported
	}
	return nil
}

func (m *OIDCWellKnownResponse) GetIdTokenSigningAlgValuesSupported() []string {
	if m != nil {
		return m.IdTokenSigningAlgValuesSupported
	}
	return nil
}

func (m *OIDCWellKnownResponse) GetScopesSupported() []string {
	if m != nil {
		return m.ScopesSupported
	}
	return nil
}

func (m *OIDCWellKnownResponse) GetTokenEndpointAuthMethodsSupported() []string {
	if m != nil {
		return m.TokenEndpointAuthMethodsSupported
	}
	return nil
}

func (m *OIDCWellKnownResponse) GetClaimsSupported() []string {
	if m != nil {
		return m.ClaimsSupported
	}
	return nil
}

func (m *OIDCWellKnownResponse) GetCodeChallengeMethodsSupported() []string {
	if m != nil {
		return m.CodeChallengeMethodsSupported
	}
	return nil
}

func (m *OIDCWellKnownResponse) GetGrantTypesSupported() []string {
	if m != nil {
		return m.GrantTypesSupported
	}
	return nil
}

type OIDCWellKnownRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty" valid:"required,uuid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OIDCWellKnownRequest) Reset()         { *m = OIDCWellKnownRequest{} }
func (m *OIDCWellKnownRequest) String() string { return proto.CompactTextString(m) }
func (*OIDCWellKnownRequest) ProtoMessage()    {}
func (*OIDCWellKnownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{4}
}
func (m *OIDCWellKnownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OIDCWellKnownRequest.Unmarshal(m, b)
}
func (m *OIDCWellKnownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OIDCWellKnownRequest.Marshal(b, m, deterministic)
}
func (m *OIDCWellKnownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OIDCWellKnownRequest.Merge(m, src)
}
func (m *OIDCWellKnownRequest) XXX_Size() int {
	return xxx_messageInfo_OIDCWellKnownRequest.Size(m)
}
func (m *OIDCWellKnownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OIDCWellKnownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OIDCWellKnownRequest proto.InternalMessageInfo

func (m *OIDCWellKnownRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type OAuthJWKSRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty" valid:"required,uuid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuthJWKSRequest) Reset()         { *m = OAuthJWKSRequest{} }
func (m *OAuthJWKSRequest) String() string { return proto.CompactTextString(m) }
func (*OAuthJWKSRequest) ProtoMessage()    {}
func (*OAuthJWKSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{5}
}
func (m *OAuthJWKSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthJWKSRequest.Unmarshal(m, b)
}
func (m *OAuthJWKSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthJWKSRequest.Marshal(b, m, deterministic)
}
func (m *OAuthJWKSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthJWKSRequest.Merge(m, src)
}
func (m *OAuthJWKSRequest) XXX_Size() int {
	return xxx_messageInfo_OAuthJWKSRequest.Size(m)
}
func (m *OAuthJWKSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthJWKSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthJWKSRequest proto.InternalMessageInfo

func (m *OAuthJWKSRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type OAuthJWKSResponse struct {
	Keys                 []*OAuthJWKSResponse_Key `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *OAuthJWKSResponse) Reset()         { *m = OAuthJWKSResponse{} }
func (m *OAuthJWKSResponse) String() string { return proto.CompactTextString(m) }
func (*OAuthJWKSResponse) ProtoMessage()    {}
func (*OAuthJWKSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{6}
}
func (m *OAuthJWKSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthJWKSResponse.Unmarshal(m, b)
}
func (m *OAuthJWKSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthJWKSResponse.Marshal(b, m, deterministic)
}
func (m *OAuthJWKSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthJWKSResponse.Merge(m, src)
}
func (m *OAuthJWKSResponse) XXX_Size() int {
	return xxx_messageInfo_OAuthJWKSResponse.Size(m)
}
func (m *OAuthJWKSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthJWKSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthJWKSResponse proto.InternalMessageInfo

func (m *OAuthJWKSResponse) GetKeys() []*OAuthJWKSResponse_Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

type OAuthJWKSResponse_Key struct {
	Kid                  string   `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	Alg                  string   `protobuf:"bytes,2,opt,name=alg,proto3" json:"alg,omitempty"`
	Use                  string   `protobuf:"bytes,3,opt,name=use,proto3" json:"use,omitempty"`
	E                    string   `protobuf:"bytes,4,opt,name=e,proto3" json:"e,omitempty"`
	N                    string   `protobuf:"bytes,5,opt,name=n,proto3" json:"n,omitempty"`
	Kty                  string   `protobuf:"bytes,6,opt,name=kty,proto3" json:"kty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuthJWKSResponse_Key) Reset()         { *m = OAuthJWKSResponse_Key{} }
func (m *OAuthJWKSResponse_Key) String() string { return proto.CompactTextString(m) }
func (*OAuthJWKSResponse_Key) ProtoMessage()    {}
func (*OAuthJWKSResponse_Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{6, 0}
}
func (m *OAuthJWKSResponse_Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthJWKSResponse_Key.Unmarshal(m, b)
}
func (m *OAuthJWKSResponse_Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthJWKSResponse_Key.Marshal(b, m, deterministic)
}
func (m *OAuthJWKSResponse_Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthJWKSResponse_Key.Merge(m, src)
}
func (m *OAuthJWKSResponse_Key) XXX_Size() int {
	return xxx_messageInfo_OAuthJWKSResponse_Key.Size(m)
}
func (m *OAuthJWKSResponse_Key) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthJWKSResponse_Key.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthJWKSResponse_Key proto.InternalMessageInfo

func (m *OAuthJWKSResponse_Key) GetKid() string {
	if m != nil {
		return m.Kid
	}
	return ""
}

func (m *OAuthJWKSResponse_Key) GetAlg() string {
	if m != nil {
		return m.Alg
	}
	return ""
}

func (m *OAuthJWKSResponse_Key) GetUse() string {
	if m != nil {
		return m.Use
	}
	return ""
}

func (m *OAuthJWKSResponse_Key) GetE() string {
	if m != nil {
		return m.E
	}
	return ""
}

func (m *OAuthJWKSResponse_Key) GetN() string {
	if m != nil {
		return m.N
	}
	return ""
}

func (m *OAuthJWKSResponse_Key) GetKty() string {
	if m != nil {
		return m.Kty
	}
	return ""
}

func init() {
	proto.RegisterEnum("idas.oauth2.OAuthGrantType", OAuthGrantType_name, OAuthGrantType_value)
	proto.RegisterEnum("idas.oauth2.OAuthTokenType", OAuthTokenType_name, OAuthTokenType_value)
	proto.RegisterEnum("idas.oauth2.OAuthAuthorizeRequest_ResponseType", OAuthAuthorizeRequest_ResponseType_name, OAuthAuthorizeRequest_ResponseType_value)
	proto.RegisterEnum("idas.oauth2.OAuthAuthorizeRequest_CodeChallengeMethod", OAuthAuthorizeRequest_CodeChallengeMethod_name, OAuthAuthorizeRequest_CodeChallengeMethod_value)
	proto.RegisterType((*OAuthTokenResponse)(nil), "idas.oauth2.OAuthTokenResponse")
	proto.RegisterMapType((map[string]string)(nil), "idas.oauth2.OAuthTokenResponse.HeadersEntry")
	proto.RegisterType((*OAuthAuthorizeRequest)(nil), "idas.oauth2.OAuthAuthorizeRequest")
	proto.RegisterType((*OAuthAuthorizeRequest_ResponseTypes)(nil), "idas.oauth2.OAuthAuthorizeRequest.ResponseTypes")
	proto.RegisterType((*OAuthTokenRequest)(nil), "idas.oauth2.OAuthTokenRequest")
	proto.RegisterType((*OIDCWellKnownResponse)(nil), "idas.oauth2.OIDCWellKnownResponse")
	proto.RegisterType((*OIDCWellKnownRequest)(nil), "idas.oauth2.OIDCWellKnownRequest")
	proto.RegisterType((*OAuthJWKSRequest)(nil), "idas.oauth2.OAuthJWKSRequest")
	proto.RegisterType((*OAuthJWKSResponse)(nil), "idas.oauth2.OAuthJWKSResponse")
	proto.RegisterType((*OAuthJWKSResponse_Key)(nil), "idas.oauth2.OAuthJWKSResponse.Key")
}

func init() { proto.RegisterFile("endpoints/oauth2.proto", fileDescriptor_6bf1d6517b82c2f3) }

var fileDescriptor_6bf1d6517b82c2f3 = []byte{
	// 1289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4f, 0x6f, 0xdb, 0xc6,
	0x12, 0x37, 0x2d, 0xdb, 0x92, 0x46, 0xb2, 0xc2, 0xac, 0x23, 0x3f, 0xc6, 0x41, 0x60, 0x45, 0x0f,
	0x06, 0xfc, 0xfc, 0xf2, 0xa4, 0x17, 0x05, 0x31, 0x12, 0x07, 0x3d, 0x44, 0x6e, 0x9a, 0x26, 0x6e,
	0xea, 0x82, 0xce, 0x1f, 0xb4, 0x87, 0x12, 0x34, 0x39, 0x91, 0x36, 0xa6, 0x97, 0xcc, 0x2e, 0xe9,
	0x44, 0xfd, 0x58, 0x3d, 0xf4, 0x33, 0xf4, 0xd6, 0x7b, 0x0f, 0x3e, 0xf5, 0xd4, 0x63, 0x3f, 0x41,
	0xb1, 0x7f, 0x28, 0x52, 0x8a, 0x83, 0xa4, 0xc8, 0x81, 0xc0, 0xee, 0xcc, 0xfc, 0x66, 0x67, 0x77,
	0x66, 0x7e, 0x43, 0x58, 0x47, 0x16, 0x26, 0x31, 0x65, 0xa9, 0xe8, 0xc7, 0x7e, 0x96, 0x8e, 0x07,
	0xbd, 0x84, 0xc7, 0x69, 0x4c, 0x1a, 0x34, 0xf4, 0x45, 0x4f, 0x8b, 0x36, 0xae, 0x14, 0x46, 0xc7,
	0xbe, 0x40, 0x6d, 0xb2, 0xe1, 0x14, 0x52, 0x81, 0x42, 0xd0, 0x98, 0x09, 0xad, 0xe9, 0x9e, 0x57,
	0x80, 0x1c, 0x3e, 0xc8, 0xd2, 0xf1, 0xb3, 0xf8, 0x04, 0x99, 0x8b, 0x22, 0x89, 0x99, 0x40, 0x72,
	0x03, 0x9a, 0x7e, 0x10, 0xa0, 0x10, 0x5e, 0x2a, 0xe5, 0x8e, 0xd5, 0xb1, 0xb6, 0xeb, 0x6e, 0x43,
	0xcb, 0x94, 0x29, 0x79, 0x02, 0xa0, 0x74, 0x5e, 0x3a, 0x49, 0xd0, 0x59, 0xec, 0x58, 0xdb, 0xad,
	0xc1, 0xb5, 0x5e, 0x29, 0x96, 0x5e, 0xe1, 0xf7, 0xd9, 0x24, 0xc1, 0x61, 0xeb, 0xcf, 0xf3, 0xcd,
	0x12, 0xc4, 0xad, 0xa7, 0xb9, 0x8a, 0xec, 0x00, 0xe0, 0xbb, 0x84, 0x72, 0x14, 0x1e, 0x65, 0x4e,
	0xa5, 0x63, 0x6d, 0x2f, 0x0f, 0x1b, 0xbf, 0x9e, 0x6f, 0x2e, 0xfc, 0x7e, 0xbe, 0x59, 0xa1, 0x2c,
	0x75, 0xeb, 0x46, 0xfd, 0x98, 0x91, 0x7f, 0xc3, 0x2a, 0xc7, 0x57, 0x1c, 0xc5, 0xd8, 0xc4, 0xb6,
	0xa4, 0x62, 0x6b, 0x1a, 0xa1, 0x0e, 0xee, 0x0a, 0x2c, 0x23, 0xe7, 0x31, 0x77, 0x96, 0x95, 0x52,
	0x6f, 0xc8, 0x55, 0xa8, 0xd1, 0xd0, 0xa0, 0x56, 0x94, 0xa2, 0x4a, 0x43, 0x0d, 0xf8, 0x0a, 0xaa,
	0x63, 0xf4, 0x43, 0xe4, 0xc2, 0xa9, 0x76, 0x2a, 0xdb, 0x8d, 0xc1, 0xcd, 0x0f, 0x5c, 0x25, 0x7f,
	0xa2, 0xde, 0xd7, 0xda, 0xfc, 0x21, 0x4b, 0xf9, 0xc4, 0xcd, 0xc1, 0xc4, 0x81, 0x6a, 0x10, 0xc7,
	0x27, 0x14, 0x85, 0x53, 0xeb, 0x54, 0xe4, 0x09, 0x66, 0x4b, 0xee, 0x41, 0x83, 0xe1, 0xbb, 0xd4,
	0x3b, 0xc5, 0x74, 0x1c, 0x87, 0x4e, 0xbd, 0x53, 0xd9, 0x6e, 0x0d, 0x1c, 0x7d, 0x4a, 0x9e, 0x9e,
	0xde, 0x37, 0xf1, 0x88, 0xaa, 0x27, 0x71, 0x41, 0x1a, 0x3f, 0x55, 0xb6, 0x1b, 0x7b, 0xd0, 0x2c,
	0x9f, 0x46, 0x6c, 0xa8, 0x9c, 0xe0, 0xc4, 0x24, 0x45, 0x2e, 0xe5, 0x7d, 0xcf, 0xfc, 0x28, 0xd3,
	0x79, 0xa8, 0xbb, 0x7a, 0xb3, 0xb7, 0x78, 0xd7, 0xea, 0xfe, 0xb6, 0x04, 0x6d, 0x15, 0xbd, 0xfc,
	0x62, 0x4e, 0x7f, 0x42, 0x17, 0xdf, 0x64, 0x28, 0x52, 0xf2, 0x5c, 0x3e, 0xa4, 0xbe, 0x8c, 0xce,
	0xa1, 0xf4, 0xd7, 0x18, 0xfc, 0xff, 0xfd, 0x8b, 0xcf, 0x43, 0x7b, 0xf9, 0x23, 0xc8, 0x48, 0x85,
	0x7c, 0xfa, 0x62, 0x4b, 0xae, 0x41, 0x3d, 0x88, 0x28, 0xb2, 0xd4, 0xa3, 0xa1, 0x09, 0xa7, 0xa6,
	0x05, 0x8f, 0x43, 0x59, 0x57, 0x1c, 0x43, 0xca, 0x31, 0x48, 0xbd, 0x8c, 0x53, 0x95, 0xea, 0xba,
	0xdb, 0xc8, 0x65, 0xcf, 0x39, 0x95, 0x57, 0x11, 0xa9, 0x9f, 0xa2, 0xc9, 0xab, 0xde, 0x28, 0x69,
	0x10, 0x27, 0x98, 0x27, 0x54, 0x6d, 0xc8, 0x26, 0x34, 0xf2, 0x32, 0x95, 0x17, 0xd0, 0x39, 0x05,
	0x53, 0xa5, 0x32, 0x98, 0x2d, 0x68, 0x05, 0x71, 0x88, 0x5e, 0x30, 0xf6, 0xa3, 0x08, 0xd9, 0x08,
	0x9d, 0xaa, 0xb2, 0x59, 0x95, 0xd2, 0xfd, 0x5c, 0x48, 0x5e, 0x43, 0x7b, 0xd6, 0x2c, 0xcf, 0x52,
	0x4d, 0x95, 0xf5, 0xee, 0x27, 0x3c, 0xc9, 0x7e, 0xd9, 0xa1, 0xce, 0x9b, 0xbb, 0x16, 0xbc, 0x2f,
	0xdc, 0x78, 0x01, 0xab, 0x33, 0xcf, 0x47, 0x1e, 0xc2, 0xb2, 0x8c, 0x5e, 0x38, 0x96, 0x2a, 0x89,
	0xfe, 0x3f, 0x7c, 0x7f, 0x57, 0xa3, 0xbb, 0xf7, 0xa1, 0x59, 0x16, 0x93, 0x1a, 0x2c, 0xb1, 0x98,
	0xa1, 0xbd, 0x20, 0x57, 0x32, 0x10, 0xdb, 0x22, 0x75, 0x58, 0x56, 0xd5, 0x6f, 0x2f, 0x92, 0x66,
	0xd1, 0x0b, 0x76, 0xa5, 0xbb, 0x03, 0x6b, 0x17, 0x5c, 0x40, 0xda, 0x27, 0x91, 0x4f, 0x99, 0x76,
	0x72, 0x34, 0xb8, 0xb3, 0x6b, 0x5b, 0xdd, 0x3f, 0x96, 0xe0, 0x72, 0xb9, 0x1f, 0x74, 0x35, 0xed,
	0x01, 0x8c, 0xb8, 0xcf, 0xd2, 0xa2, 0x94, 0x2e, 0xa4, 0x83, 0x47, 0xd2, 0x46, 0x85, 0x5d, 0x1f,
	0xe5, 0x4b, 0x42, 0x74, 0x80, 0xa6, 0x5a, 0xd4, 0xfa, 0x53, 0x2a, 0x65, 0xa6, 0xd2, 0x96, 0xe6,
	0x2a, 0xed, 0x18, 0x56, 0x8d, 0x52, 0x60, 0xc0, 0x31, 0xd5, 0x85, 0x33, 0xfc, 0xc2, 0xb0, 0xca,
	0x9d, 0x11, 0x4d, 0xc7, 0xd9, 0x71, 0x2f, 0x88, 0x4f, 0xfb, 0x4f, 0x69, 0xc0, 0xe3, 0xc3, 0x44,
	0xfc, 0x2f, 0x60, 0x7d, 0x19, 0x70, 0x3f, 0x39, 0x19, 0xf5, 0x05, 0xf2, 0x33, 0x1a, 0x60, 0xff,
	0x34, 0x0e, 0x31, 0x12, 0xbd, 0x23, 0xe5, 0xc4, 0x6d, 0x6a, 0x9f, 0x7a, 0x47, 0x36, 0xa0, 0x96,
	0x09, 0xe4, 0xcc, 0x3f, 0xcd, 0x6b, 0x6f, 0xba, 0x27, 0xdf, 0x43, 0x2d, 0xf1, 0x85, 0x78, 0x1b,
	0xf3, 0x50, 0xd7, 0xdc, 0xe7, 0x1e, 0x3d, 0x75, 0x47, 0x7e, 0x9c, 0x67, 0xc0, 0x9a, 0xf2, 0x7f,
	0xef, 0x33, 0xae, 0x35, 0x4f, 0x9e, 0xba, 0x03, 0xeb, 0xe5, 0x0e, 0x1c, 0x40, 0x3b, 0xa4, 0xc2,
	0x3f, 0x8e, 0xd0, 0x9b, 0x3d, 0x1d, 0x3a, 0xd6, 0x76, 0xcd, 0x5d, 0x33, 0x4a, 0xb7, 0xec, 0x69,
	0x6f, 0x66, 0x46, 0x34, 0x3e, 0x3a, 0x23, 0x4a, 0x33, 0xa1, 0xfb, 0xf3, 0x0a, 0xb4, 0x0f, 0x1f,
	0x7f, 0xb9, 0xff, 0x12, 0xa3, 0xe8, 0x80, 0xc5, 0x6f, 0x8b, 0xe1, 0xb4, 0x0e, 0x2b, 0x54, 0x88,
	0x0c, 0xb9, 0x61, 0x40, 0xb3, 0x23, 0x77, 0x60, 0xdd, 0x37, 0x9d, 0xe2, 0xa7, 0x34, 0x66, 0x5e,
	0x4e, 0xab, 0xa6, 0xb0, 0xda, 0x33, 0xda, 0x87, 0x46, 0x49, 0x86, 0x70, 0x3d, 0x44, 0xf9, 0x28,
	0xde, 0x07, 0xd0, 0xba, 0xf4, 0xae, 0x69, 0xa3, 0x07, 0x17, 0xfa, 0xd8, 0x82, 0x96, 0xbe, 0xe8,
	0x14, 0xa4, 0xeb, 0x71, 0x55, 0x49, 0xa7, 0x66, 0xff, 0x85, 0xcb, 0xb2, 0x40, 0x28, 0x7b, 0x15,
	0x17, 0x96, 0x9a, 0xd1, 0xec, 0x5c, 0x31, 0x35, 0xee, 0xc3, 0x1a, 0xc7, 0xb3, 0x38, 0x98, 0x8b,
	0x46, 0x17, 0x1a, 0x29, 0x54, 0x53, 0xc0, 0x55, 0xa8, 0xbd, 0x7e, 0x7b, 0x22, 0x54, 0xbb, 0x68,
	0x9a, 0xab, 0xca, 0xbd, 0x6c, 0x95, 0xbb, 0xe0, 0xcc, 0x70, 0xbd, 0xf0, 0x44, 0x96, 0x24, 0x31,
	0x4f, 0x31, 0x34, 0x73, 0x6a, 0xbd, 0x4c, 0xe2, 0xe2, 0x28, 0xd7, 0x92, 0x5d, 0xf8, 0x97, 0xc8,
	0x8e, 0x5f, 0xcb, 0x36, 0x9c, 0x07, 0xd6, 0x15, 0xb0, 0x6d, 0xd4, 0x73, 0xb8, 0x43, 0xd8, 0xca,
	0xf9, 0xc5, 0x13, 0x74, 0xc4, 0x28, 0x1b, 0x79, 0x7e, 0x34, 0xf2, 0xd4, 0x64, 0x2a, 0x7b, 0x01,
	0xe5, 0xa5, 0x63, 0x06, 0xf1, 0x91, 0x36, 0x7d, 0x10, 0x8d, 0x5e, 0x28, 0xc3, 0xc2, 0xe1, 0x7f,
	0xc0, 0x56, 0xa4, 0x5f, 0xc6, 0x36, 0x14, 0xf6, 0x92, 0x96, 0x17, 0xa6, 0xdf, 0xc1, 0xd6, 0x6c,
	0x36, 0x54, 0x66, 0x0d, 0xa7, 0x97, 0xf1, 0x4d, 0x85, 0xbf, 0x31, 0x93, 0x24, 0x99, 0x60, 0x4d,
	0x7f, 0xb3, 0x87, 0x07, 0x91, 0x4f, 0x4f, 0xcb, 0xe0, 0x55, 0x7d, 0xb8, 0x96, 0x17, 0xa6, 0x8f,
	0xa0, 0x73, 0xe1, 0x2c, 0x29, 0x43, 0x5b, 0x0a, 0x7a, 0xfd, 0x82, 0xf1, 0x50, 0x72, 0x34, 0x80,
	0x76, 0xc1, 0xa8, 0x65, 0xf4, 0x25, 0x85, 0x5e, 0x9b, 0xf2, 0x67, 0x81, 0xe9, 0x7e, 0x0b, 0x57,
	0xe6, 0x7a, 0x46, 0xb3, 0xf3, 0x6e, 0x99, 0x2a, 0x55, 0xd7, 0x0c, 0xaf, 0xfe, 0x75, 0xbe, 0xd9,
	0x3e, 0xf3, 0x23, 0x1a, 0xee, 0x75, 0x39, 0xbe, 0xc9, 0x28, 0xc7, 0xf0, 0x66, 0x96, 0xd1, 0xb0,
	0x5b, 0xb0, 0x68, 0xf7, 0x09, 0xd8, 0xaa, 0x43, 0x9f, 0xbc, 0x3c, 0x38, 0xfa, 0x5c, 0x5f, 0xbf,
	0x58, 0x66, 0x6e, 0x68, 0x67, 0xa6, 0x99, 0x77, 0x61, 0xe9, 0x04, 0x27, 0x7a, 0xf8, 0x35, 0x06,
	0xdd, 0xf7, 0xc9, 0xa1, 0x6c, 0xdd, 0x3b, 0xc0, 0x89, 0xab, 0xec, 0x37, 0x28, 0x54, 0x0e, 0x50,
	0xff, 0x0a, 0xe5, 0x61, 0xb8, 0x72, 0x29, 0x25, 0x7e, 0x34, 0x32, 0x2d, 0x2f, 0x97, 0x52, 0x92,
	0x09, 0x34, 0x6d, 0x2c, 0x97, 0xa4, 0x09, 0x56, 0xfe, 0x7f, 0x61, 0xa9, 0x1d, 0x33, 0x5d, 0x68,
	0x31, 0xe5, 0x31, 0x9d, 0x98, 0x36, 0x93, 0xcb, 0x1d, 0x1f, 0x5a, 0xb3, 0xb3, 0x8b, 0x5c, 0x9e,
	0x63, 0x60, 0x7b, 0x81, 0xac, 0x03, 0x99, 0xa5, 0x0f, 0x33, 0x72, 0x9b, 0xc5, 0x1c, 0xb0, 0x17,
	0xa5, 0x95, 0x79, 0xbb, 0x80, 0x63, 0x88, 0x2c, 0xa5, 0x7e, 0x24, 0xec, 0xca, 0xce, 0x2d, 0x73,
	0xc4, 0x94, 0x09, 0x09, 0xc0, 0xca, 0x10, 0x7d, 0x8e, 0xdc, 0x5e, 0x20, 0x55, 0xa8, 0x3c, 0xf5,
	0x03, 0xdb, 0x92, 0xc2, 0x7d, 0xf5, 0x3b, 0x69, 0x2f, 0x0e, 0x6f, 0xff, 0x70, 0xeb, 0x63, 0x64,
	0x9f, 0x97, 0xff, 0xfd, 0x7c, 0x71, 0xbc, 0xa2, 0xfe, 0xfa, 0x6f, 0xff, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x6d, 0x33, 0x06, 0x30, 0x4c, 0x0c, 0x00, 0x00,
}
