// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: endpoints/oauth2.proto

package endpoint

import (
	fmt "fmt"
	github_com_MicroOps_cn_idas_pkg_service_models "github.com/MicroOps-cn/idas/pkg/service/models"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// @sync-to-public:public/src/services/idas/enums.ts:OAuthGrantType
type OAuthGrantType int32

const (
	OAuthGrantType_refresh_token      OAuthGrantType = 0
	OAuthGrantType_authorization_code OAuthGrantType = 1
	OAuthGrantType_password           OAuthGrantType = 2
	OAuthGrantType_client_credentials OAuthGrantType = 3
)

var OAuthGrantType_name = map[int32]string{
	0: "refresh_token",
	1: "authorization_code",
	2: "password",
	3: "client_credentials",
}

var OAuthGrantType_value = map[string]int32{
	"refresh_token":      0,
	"authorization_code": 1,
	"password":           2,
	"client_credentials": 3,
}

func (x OAuthGrantType) String() string {
	return proto.EnumName(OAuthGrantType_name, int32(x))
}

func (OAuthGrantType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{0}
}

type OAuthTokenType int32

const (
	OAuthTokenType_Bearer OAuthTokenType = 0
	OAuthTokenType_Mac    OAuthTokenType = 1
	OAuthTokenType_Cookie OAuthTokenType = 2
)

var OAuthTokenType_name = map[int32]string{
	0: "Bearer",
	1: "Mac",
	2: "Cookie",
}

var OAuthTokenType_value = map[string]int32{
	"Bearer": 0,
	"Mac":    1,
	"Cookie": 2,
}

func (x OAuthTokenType) String() string {
	return proto.EnumName(OAuthTokenType_name, int32(x))
}

func (OAuthTokenType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{1}
}

// @sync-to-public:public/src/services/idas/enums.ts:ResponseType
type OAuthAuthorizeRequest_ResponseType int32

const (
	OAuthAuthorizeRequest_default OAuthAuthorizeRequest_ResponseType = 0
	OAuthAuthorizeRequest_code    OAuthAuthorizeRequest_ResponseType = 1
	OAuthAuthorizeRequest_token   OAuthAuthorizeRequest_ResponseType = 2
)

var OAuthAuthorizeRequest_ResponseType_name = map[int32]string{
	0: "default",
	1: "code",
	2: "token",
}

var OAuthAuthorizeRequest_ResponseType_value = map[string]int32{
	"default": 0,
	"code":    1,
	"token":   2,
}

func (x OAuthAuthorizeRequest_ResponseType) String() string {
	return proto.EnumName(OAuthAuthorizeRequest_ResponseType_name, int32(x))
}

func (OAuthAuthorizeRequest_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{1, 0}
}

type OAuthTokenResponse struct {
	AccessToken          string            `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType            OAuthTokenType    `protobuf:"varint,2,opt,name=token_type,json=tokenType,proto3,enum=idas.oauth2.OAuthTokenType" json:"token_type,omitempty"`
	ExpiresIn            int               `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3,customtype=int" json:"expires_in"`
	RefreshToken         string            `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Error                string            `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	IdToken              string            `protobuf:"bytes,6,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	Headers              map[string]string `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cookies              []string          `protobuf:"bytes,8,rep,name=cookies,proto3" json:"cookies,omitempty"`
	NextMethod           []LoginType       `protobuf:"varint,9,rep,packed,name=next_method,json=nextMethod,proto3,enum=idas.endpoint.LoginType" json:"next_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OAuthTokenResponse) Reset()         { *m = OAuthTokenResponse{} }
func (m *OAuthTokenResponse) String() string { return proto.CompactTextString(m) }
func (*OAuthTokenResponse) ProtoMessage()    {}
func (*OAuthTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{0}
}
func (m *OAuthTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthTokenResponse.Unmarshal(m, b)
}
func (m *OAuthTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthTokenResponse.Marshal(b, m, deterministic)
}
func (m *OAuthTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthTokenResponse.Merge(m, src)
}
func (m *OAuthTokenResponse) XXX_Size() int {
	return xxx_messageInfo_OAuthTokenResponse.Size(m)
}
func (m *OAuthTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthTokenResponse proto.InternalMessageInfo

func (m *OAuthTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *OAuthTokenResponse) GetTokenType() OAuthTokenType {
	if m != nil {
		return m.TokenType
	}
	return OAuthTokenType_Bearer
}

func (m *OAuthTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *OAuthTokenResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *OAuthTokenResponse) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

func (m *OAuthTokenResponse) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *OAuthTokenResponse) GetCookies() []string {
	if m != nil {
		return m.Cookies
	}
	return nil
}

func (m *OAuthTokenResponse) GetNextMethod() []LoginType {
	if m != nil {
		return m.NextMethod
	}
	return nil
}

type OAuthAuthorizeRequest struct {
	ResponseType         OAuthAuthorizeRequest_ResponseType `protobuf:"varint,1,opt,name=response_type,json=responseType,proto3,enum=idas.oauth2.OAuthAuthorizeRequest_ResponseType" json:"response_type,omitempty"`
	ClientId             string                             `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RedirectUri          string                             `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	State                string                             `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Scope                string                             `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	AccessType           string                             `protobuf:"bytes,6,opt,name=access_type,json=accessType,proto3" json:"access_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *OAuthAuthorizeRequest) Reset()         { *m = OAuthAuthorizeRequest{} }
func (m *OAuthAuthorizeRequest) String() string { return proto.CompactTextString(m) }
func (*OAuthAuthorizeRequest) ProtoMessage()    {}
func (*OAuthAuthorizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{1}
}
func (m *OAuthAuthorizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthAuthorizeRequest.Unmarshal(m, b)
}
func (m *OAuthAuthorizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthAuthorizeRequest.Marshal(b, m, deterministic)
}
func (m *OAuthAuthorizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthAuthorizeRequest.Merge(m, src)
}
func (m *OAuthAuthorizeRequest) XXX_Size() int {
	return xxx_messageInfo_OAuthAuthorizeRequest.Size(m)
}
func (m *OAuthAuthorizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthAuthorizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthAuthorizeRequest proto.InternalMessageInfo

func (m *OAuthAuthorizeRequest) GetResponseType() OAuthAuthorizeRequest_ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return OAuthAuthorizeRequest_default
}

func (m *OAuthAuthorizeRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *OAuthAuthorizeRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *OAuthAuthorizeRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *OAuthAuthorizeRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *OAuthAuthorizeRequest) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

type OAuthTokenRequest struct {
	GrantType            OAuthGrantType                                         `protobuf:"varint,1,opt,name=grant_type,json=grantType,proto3,enum=idas.oauth2.OAuthGrantType" json:"grant_type,omitempty"`
	Code                 string                                                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	RedirectUri          string                                                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	ClientId             string                                                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         github_com_MicroOps_cn_idas_pkg_service_models.Secret  `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3,customtype=github.com/MicroOps-cn/idas/pkg/service/models.Secret" json:"client_secret"`
	Username             string                                                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Password             github_com_MicroOps_cn_idas_pkg_service_models.Secret  `protobuf:"bytes,7,opt,name=password,proto3,customtype=github.com/MicroOps-cn/idas/pkg/service/models.Secret" json:"password"`
	RefreshToken         *github_com_MicroOps_cn_idas_pkg_service_models.Secret `protobuf:"bytes,8,opt,name=refresh_token,json=refreshToken,proto3,customtype=github.com/MicroOps-cn/idas/pkg/service/models.Secret" json:"refresh_token,omitempty"`
	State                string                                                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	DisableRefreshToken  bool                                                   `protobuf:"varint,10,opt,name=disable_refresh_token,json=disableRefreshToken,proto3" json:"disable_refresh_token,omitempty"`
	TokenType            OAuthTokenType                                         `protobuf:"varint,11,opt,name=token_type,json=tokenType,proto3,enum=idas.oauth2.OAuthTokenType" json:"token_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *OAuthTokenRequest) Reset()         { *m = OAuthTokenRequest{} }
func (m *OAuthTokenRequest) String() string { return proto.CompactTextString(m) }
func (*OAuthTokenRequest) ProtoMessage()    {}
func (*OAuthTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bf1d6517b82c2f3, []int{2}
}
func (m *OAuthTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuthTokenRequest.Unmarshal(m, b)
}
func (m *OAuthTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuthTokenRequest.Marshal(b, m, deterministic)
}
func (m *OAuthTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuthTokenRequest.Merge(m, src)
}
func (m *OAuthTokenRequest) XXX_Size() int {
	return xxx_messageInfo_OAuthTokenRequest.Size(m)
}
func (m *OAuthTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuthTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OAuthTokenRequest proto.InternalMessageInfo

func (m *OAuthTokenRequest) GetGrantType() OAuthGrantType {
	if m != nil {
		return m.GrantType
	}
	return OAuthGrantType_refresh_token
}

func (m *OAuthTokenRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OAuthTokenRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *OAuthTokenRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *OAuthTokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *OAuthTokenRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *OAuthTokenRequest) GetDisableRefreshToken() bool {
	if m != nil {
		return m.DisableRefreshToken
	}
	return false
}

func (m *OAuthTokenRequest) GetTokenType() OAuthTokenType {
	if m != nil {
		return m.TokenType
	}
	return OAuthTokenType_Bearer
}

func init() {
	proto.RegisterEnum("idas.oauth2.OAuthGrantType", OAuthGrantType_name, OAuthGrantType_value)
	proto.RegisterEnum("idas.oauth2.OAuthTokenType", OAuthTokenType_name, OAuthTokenType_value)
	proto.RegisterEnum("idas.oauth2.OAuthAuthorizeRequest_ResponseType", OAuthAuthorizeRequest_ResponseType_name, OAuthAuthorizeRequest_ResponseType_value)
	proto.RegisterType((*OAuthTokenResponse)(nil), "idas.oauth2.OAuthTokenResponse")
	proto.RegisterMapType((map[string]string)(nil), "idas.oauth2.OAuthTokenResponse.HeadersEntry")
	proto.RegisterType((*OAuthAuthorizeRequest)(nil), "idas.oauth2.OAuthAuthorizeRequest")
	proto.RegisterType((*OAuthTokenRequest)(nil), "idas.oauth2.OAuthTokenRequest")
}

func init() { proto.RegisterFile("endpoints/oauth2.proto", fileDescriptor_6bf1d6517b82c2f3) }

var fileDescriptor_6bf1d6517b82c2f3 = []byte{
	// 774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0x1e, 0xc7, 0x33, 0x13, 0xbb, 0x9c, 0x1d, 0x79, 0x9b, 0xdd, 0x95, 0x99, 0x3d, 0x4c, 0x18,
	0x2e, 0xd1, 0x08, 0x1c, 0x36, 0x2b, 0x24, 0x36, 0x88, 0x03, 0x41, 0xfc, 0xac, 0xc4, 0x68, 0x25,
	0x33, 0x1c, 0xe0, 0x80, 0xd5, 0xb1, 0x6b, 0x93, 0x56, 0x92, 0x6e, 0xd3, 0xdd, 0x5e, 0x36, 0x3c,
	0x13, 0x0f, 0xc2, 0x89, 0x07, 0xe0, 0x30, 0x27, 0x1e, 0x04, 0xb9, 0xbb, 0x3d, 0x71, 0x02, 0x08,
	0x10, 0x1c, 0x22, 0x75, 0xfd, 0x74, 0xd5, 0x57, 0x5f, 0x7d, 0xee, 0xc0, 0x23, 0xe4, 0x65, 0x25,
	0x18, 0xd7, 0x6a, 0x2c, 0x68, 0xad, 0x97, 0x93, 0xb4, 0x92, 0x42, 0x0b, 0x12, 0xb1, 0x92, 0xaa,
	0xd4, 0xba, 0xce, 0x1f, 0xec, 0x92, 0xe6, 0x54, 0xa1, 0x4d, 0x39, 0x4f, 0x76, 0x5e, 0x85, 0x4a,
	0x31, 0xc1, 0x95, 0x8d, 0x5c, 0xfe, 0xe2, 0x03, 0x79, 0xf1, 0x71, 0xad, 0x97, 0x37, 0x62, 0x85,
	0x3c, 0x43, 0x55, 0x09, 0xae, 0x90, 0xbc, 0x05, 0x03, 0x5a, 0x14, 0xa8, 0x54, 0xae, 0x1b, 0x7f,
	0xe2, 0x0d, 0xbd, 0x51, 0x98, 0x45, 0xd6, 0x67, 0x52, 0xc9, 0x14, 0xc0, 0xc4, 0x72, 0xbd, 0xad,
	0x30, 0xe9, 0x0d, 0xbd, 0xd1, 0xd9, 0xe4, 0x71, 0xda, 0xc1, 0x92, 0xee, 0xea, 0xde, 0x6c, 0x2b,
	0xcc, 0x42, 0xdd, 0x1e, 0xc9, 0x15, 0x00, 0xbe, 0xae, 0x98, 0x44, 0x95, 0x33, 0x9e, 0xf8, 0x43,
	0x6f, 0x74, 0x32, 0x8b, 0x7e, 0xbe, 0xbd, 0x38, 0xfa, 0xf5, 0xf6, 0xc2, 0x67, 0x5c, 0x67, 0xa1,
	0x0b, 0x3f, 0xe7, 0xe4, 0x6d, 0xb8, 0x27, 0xf1, 0xa5, 0x44, 0xb5, 0x74, 0x58, 0x8e, 0x0d, 0x96,
	0x81, 0x73, 0x5a, 0x30, 0x0f, 0xe0, 0x04, 0xa5, 0x14, 0x32, 0x39, 0x31, 0x41, 0x6b, 0x90, 0x37,
	0x21, 0x60, 0xa5, 0xbb, 0x75, 0x6a, 0x02, 0x7d, 0x56, 0xda, 0x0b, 0x9f, 0x41, 0x7f, 0x89, 0xb4,
	0x44, 0xa9, 0x92, 0xfe, 0xd0, 0x1f, 0x45, 0x93, 0x77, 0xfe, 0x02, 0x7a, 0x4b, 0x49, 0xfa, 0x85,
	0x4d, 0xff, 0x94, 0x6b, 0xb9, 0xcd, 0xda, 0xcb, 0x24, 0x81, 0x7e, 0x21, 0xc4, 0x8a, 0xa1, 0x4a,
	0x82, 0xa1, 0xdf, 0x74, 0x70, 0x26, 0x79, 0x06, 0x11, 0xc7, 0xd7, 0x3a, 0xdf, 0xa0, 0x5e, 0x8a,
	0x32, 0x09, 0x87, 0xfe, 0xe8, 0x6c, 0x92, 0xd8, 0x2e, 0xed, 0x3a, 0xd2, 0x2f, 0xc5, 0x82, 0x59,
	0x76, 0xa0, 0x49, 0xbe, 0x36, 0xb9, 0xe7, 0x53, 0x18, 0x74, 0xbb, 0x91, 0x18, 0xfc, 0x15, 0x6e,
	0xdd, 0x12, 0x9a, 0x63, 0x33, 0xef, 0x2b, 0xba, 0xae, 0x2d, 0xef, 0x61, 0x66, 0x8d, 0x69, 0xef,
	0x03, 0xef, 0xf2, 0xa7, 0x1e, 0x3c, 0x34, 0xe8, 0x9b, 0x9f, 0x90, 0xec, 0x47, 0xcc, 0xf0, 0xfb,
	0x1a, 0x95, 0x26, 0x37, 0x0d, 0x91, 0x76, 0x18, 0xbb, 0x33, 0xcf, 0xec, 0x6c, 0xfc, 0xc7, 0xc1,
	0x0f, 0xaf, 0xa6, 0x2d, 0x09, 0x06, 0xe9, 0x40, 0x76, 0x2c, 0xf2, 0x18, 0xc2, 0x62, 0xcd, 0x90,
	0xeb, 0x9c, 0x95, 0x0e, 0x4d, 0x60, 0x1d, 0xcf, 0xcb, 0x46, 0x46, 0x12, 0x4b, 0x26, 0xb1, 0xd0,
	0x79, 0x2d, 0x99, 0xd9, 0x74, 0x98, 0x45, 0xad, 0xef, 0x6b, 0xc9, 0x9a, 0x49, 0x94, 0xa6, 0x1a,
	0xdd, 0x5a, 0xad, 0x61, 0xbc, 0x85, 0xa8, 0xb0, 0xdd, 0xa7, 0x31, 0xc8, 0x05, 0x44, 0xad, 0x2a,
	0x1b, 0xfc, 0x76, 0xa5, 0xe0, 0x44, 0xb9, 0xad, 0xf0, 0xf2, 0x3d, 0x18, 0x74, 0xa1, 0x92, 0x08,
	0xfa, 0x25, 0xbe, 0xa4, 0xf5, 0x5a, 0xc7, 0x47, 0x24, 0x80, 0xe3, 0x42, 0x94, 0x18, 0x7b, 0x24,
	0x84, 0x13, 0x23, 0x8a, 0xb8, 0x77, 0xf9, 0xdb, 0x31, 0xdc, 0xef, 0x2e, 0xdb, 0x52, 0x35, 0x05,
	0x58, 0x48, 0xca, 0x75, 0x97, 0xa7, 0x3f, 0xd1, 0xf6, 0xe7, 0x4d, 0x8e, 0xd5, 0xf6, 0xa2, 0x3d,
	0x12, 0x62, 0xdb, 0x38, 0x2e, 0xcc, 0xf9, 0x9f, 0xf0, 0xb0, 0xc7, 0xe3, 0xf1, 0x01, 0x8f, 0x73,
	0xb8, 0xe7, 0x82, 0x0a, 0x0b, 0x89, 0xda, 0xd2, 0x32, 0xfb, 0xc8, 0x7d, 0x32, 0xef, 0x2f, 0x98,
	0x5e, 0xd6, 0xf3, 0xb4, 0x10, 0x9b, 0xf1, 0x35, 0x2b, 0xa4, 0x78, 0x51, 0xa9, 0x77, 0x0b, 0x3e,
	0x6e, 0x00, 0x8f, 0xab, 0xd5, 0x62, 0xac, 0x50, 0xbe, 0x62, 0x05, 0x8e, 0x37, 0xa2, 0xc4, 0xb5,
	0x4a, 0xbf, 0x32, 0x45, 0xb2, 0x81, 0xad, 0x69, 0x2d, 0x72, 0x0e, 0x41, 0xad, 0x50, 0x72, 0xba,
	0x69, 0x99, 0xbd, 0xb3, 0xc9, 0x37, 0x10, 0x54, 0x54, 0xa9, 0x1f, 0x84, 0x2c, 0x93, 0xfe, 0xff,
	0xd1, 0xfa, 0xae, 0x1c, 0xf9, 0xee, 0xf0, 0xf3, 0x0e, 0x4c, 0xfd, 0x67, 0xff, 0x61, 0xac, 0xc3,
	0x97, 0xc1, 0xea, 0x2b, 0xec, 0xea, 0x6b, 0x02, 0x0f, 0x4b, 0xa6, 0xe8, 0x7c, 0x8d, 0xf9, 0x7e,
	0x77, 0x18, 0x7a, 0xa3, 0x20, 0x7b, 0xc3, 0x05, 0xb3, 0x6e, 0xa5, 0xfd, 0x07, 0x2f, 0xfa, 0x37,
	0x0f, 0xde, 0x15, 0x85, 0xb3, 0x7d, 0xc5, 0x90, 0xfb, 0x07, 0x73, 0xc7, 0x47, 0xe4, 0x11, 0x10,
	0xea, 0xbe, 0x3c, 0xaa, 0x99, 0xe0, 0xb9, 0x93, 0xeb, 0x60, 0xc7, 0x7e, 0xdc, 0x6b, 0xb2, 0x9c,
	0x16, 0x0a, 0x89, 0x25, 0x72, 0xcd, 0xe8, 0x5a, 0xc5, 0xfe, 0xd5, 0x13, 0xd7, 0xe2, 0xae, 0x3f,
	0x01, 0x38, 0x9d, 0x21, 0x95, 0x28, 0xe3, 0x23, 0xd2, 0x07, 0xff, 0x9a, 0x16, 0xb1, 0xd7, 0x38,
	0x3f, 0x31, 0x2f, 0x54, 0xdc, 0x9b, 0x3d, 0xfd, 0xf6, 0xc9, 0xdf, 0x51, 0xdc, 0xbe, 0x54, 0x1f,
	0xb6, 0x87, 0xf9, 0xa9, 0xf9, 0xe3, 0x78, 0xfa, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0x7a,
	0x8a, 0x85, 0x8f, 0x06, 0x00, 0x00,
}
