// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: endpoints/pages.proto

package endpoint

import (
	encoding_json "encoding/json"
	fmt "fmt"
	models "github.com/MicroOps-cn/idas/pkg/service/models"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PageConfig struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	UpdateTime           string                `protobuf:"bytes,2,opt,name=update_time,json=updateTime,proto3" json:"updateTime" valid:"required"`
	CreateTime           string                `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"createTime" valid:"required"`
	Name                 string                `protobuf:"bytes,4,opt,name=name,proto3" json:"name"`
	Description          string                `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Fields               []*models.FieldConfig `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty"`
	Icon                 string                `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`
	IsDisable            bool                  `protobuf:"varint,8,opt,name=is_disable,json=isDisable,proto3" json:"isDisable"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PageConfig) Reset()         { *m = PageConfig{} }
func (m *PageConfig) String() string { return proto.CompactTextString(m) }
func (*PageConfig) ProtoMessage()    {}
func (*PageConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{0}
}
func (m *PageConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageConfig.Unmarshal(m, b)
}
func (m *PageConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageConfig.Marshal(b, m, deterministic)
}
func (m *PageConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageConfig.Merge(m, src)
}
func (m *PageConfig) XXX_Size() int {
	return xxx_messageInfo_PageConfig.Size(m)
}
func (m *PageConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PageConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PageConfig proto.InternalMessageInfo

func (m *PageConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PageConfig) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *PageConfig) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *PageConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PageConfig) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PageConfig) GetFields() []*models.FieldConfig {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *PageConfig) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *PageConfig) GetIsDisable() bool {
	if m != nil {
		return m.IsDisable
	}
	return false
}

type GetPagesRequest struct {
	BaseListRequest      `protobuf:"bytes,1,opt,name=base_list_request,json=baseListRequest,proto3,embedded=base_list_request" json:",omitempty"`
	Status               models.PageStatus `protobuf:"varint,2,opt,name=status,proto3,enum=idas.service.models.PageStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetPagesRequest) Reset()         { *m = GetPagesRequest{} }
func (m *GetPagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPagesRequest) ProtoMessage()    {}
func (*GetPagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{1}
}
func (m *GetPagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPagesRequest.Unmarshal(m, b)
}
func (m *GetPagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPagesRequest.Marshal(b, m, deterministic)
}
func (m *GetPagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPagesRequest.Merge(m, src)
}
func (m *GetPagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPagesRequest.Size(m)
}
func (m *GetPagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPagesRequest proto.InternalMessageInfo

func (m *GetPagesRequest) GetStatus() models.PageStatus {
	if m != nil {
		return m.Status
	}
	return models.PageStatus_all
}

type GetPagesResponse struct {
	BaseListResponse     `protobuf:"bytes,1,opt,name=base_list_response,json=baseListResponse,proto3,embedded=base_list_response" json:",omitempty"`
	Data                 []*PageConfig `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPagesResponse) Reset()         { *m = GetPagesResponse{} }
func (m *GetPagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPagesResponse) ProtoMessage()    {}
func (*GetPagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{2}
}
func (m *GetPagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPagesResponse.Unmarshal(m, b)
}
func (m *GetPagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPagesResponse.Marshal(b, m, deterministic)
}
func (m *GetPagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPagesResponse.Merge(m, src)
}
func (m *GetPagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetPagesResponse.Size(m)
}
func (m *GetPagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPagesResponse proto.InternalMessageInfo

func (m *GetPagesResponse) GetData() []*PageConfig {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetPageRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPageRequest) Reset()         { *m = GetPageRequest{} }
func (m *GetPageRequest) String() string { return proto.CompactTextString(m) }
func (*GetPageRequest) ProtoMessage()    {}
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{3}
}
func (m *GetPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageRequest.Unmarshal(m, b)
}
func (m *GetPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageRequest.Marshal(b, m, deterministic)
}
func (m *GetPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageRequest.Merge(m, src)
}
func (m *GetPageRequest) XXX_Size() int {
	return xxx_messageInfo_GetPageRequest.Size(m)
}
func (m *GetPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageRequest proto.InternalMessageInfo

func (m *GetPageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPageResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,embedded=base_response" json:",omitempty"`
	Data                 *PageConfig `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPageResponse) Reset()         { *m = GetPageResponse{} }
func (m *GetPageResponse) String() string { return proto.CompactTextString(m) }
func (*GetPageResponse) ProtoMessage()    {}
func (*GetPageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{4}
}
func (m *GetPageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageResponse.Unmarshal(m, b)
}
func (m *GetPageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageResponse.Marshal(b, m, deterministic)
}
func (m *GetPageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageResponse.Merge(m, src)
}
func (m *GetPageResponse) XXX_Size() int {
	return xxx_messageInfo_GetPageResponse.Size(m)
}
func (m *GetPageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageResponse proto.InternalMessageInfo

func (m *GetPageResponse) GetData() *PageConfig {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreatePageRequest struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name" valid:"required"`
	Description          string                `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Fields               []*models.FieldConfig `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Icon                 string                `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreatePageRequest) Reset()         { *m = CreatePageRequest{} }
func (m *CreatePageRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePageRequest) ProtoMessage()    {}
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{5}
}
func (m *CreatePageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePageRequest.Unmarshal(m, b)
}
func (m *CreatePageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePageRequest.Marshal(b, m, deterministic)
}
func (m *CreatePageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePageRequest.Merge(m, src)
}
func (m *CreatePageRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePageRequest.Size(m)
}
func (m *CreatePageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePageRequest proto.InternalMessageInfo

func (m *CreatePageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatePageRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreatePageRequest) GetFields() []*models.FieldConfig {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *CreatePageRequest) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

type UpdatePageRequest struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name" valid:"required"`
	Description          string                `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Fields               []*models.FieldConfig `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Icon                 string                `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	IsDisable            bool                  `protobuf:"varint,8,opt,name=is_disable,json=isDisable,proto3" json:"isDisable"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdatePageRequest) Reset()         { *m = UpdatePageRequest{} }
func (m *UpdatePageRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePageRequest) ProtoMessage()    {}
func (*UpdatePageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{6}
}
func (m *UpdatePageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePageRequest.Unmarshal(m, b)
}
func (m *UpdatePageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePageRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePageRequest.Merge(m, src)
}
func (m *UpdatePageRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePageRequest.Size(m)
}
func (m *UpdatePageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePageRequest proto.InternalMessageInfo

func (m *UpdatePageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatePageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePageRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdatePageRequest) GetFields() []*models.FieldConfig {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *UpdatePageRequest) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *UpdatePageRequest) GetIsDisable() bool {
	if m != nil {
		return m.IsDisable
	}
	return false
}

type PatchPageRequest struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	Name                 *string               `protobuf:"bytes,2,opt,name=name,proto3,customtype=string" json:"name,omitempty"`
	Description          *string               `protobuf:"bytes,3,opt,name=description,proto3,customtype=string" json:"description,omitempty"`
	Fields               []*models.FieldConfig `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Icon                 *string               `protobuf:"bytes,5,opt,name=icon,proto3,customtype=string" json:"icon,omitempty"`
	IsDelete             *bool                 `protobuf:"varint,7,opt,name=is_delete,json=isDelete,proto3,customtype=bool" json:"isDelete,omitempty"`
	IsDisable            *bool                 `protobuf:"varint,8,opt,name=is_disable,json=isDisable,proto3,customtype=bool" json:"isDisable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PatchPageRequest) Reset()         { *m = PatchPageRequest{} }
func (m *PatchPageRequest) String() string { return proto.CompactTextString(m) }
func (*PatchPageRequest) ProtoMessage()    {}
func (*PatchPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{7}
}
func (m *PatchPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchPageRequest.Unmarshal(m, b)
}
func (m *PatchPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchPageRequest.Marshal(b, m, deterministic)
}
func (m *PatchPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchPageRequest.Merge(m, src)
}
func (m *PatchPageRequest) XXX_Size() int {
	return xxx_messageInfo_PatchPageRequest.Size(m)
}
func (m *PatchPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchPageRequest proto.InternalMessageInfo

func (m *PatchPageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PatchPageRequest) GetFields() []*models.FieldConfig {
	if m != nil {
		return m.Fields
	}
	return nil
}

type DeletePageRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePageRequest) Reset()         { *m = DeletePageRequest{} }
func (m *DeletePageRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePageRequest) ProtoMessage()    {}
func (*DeletePageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{8}
}
func (m *DeletePageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePageRequest.Unmarshal(m, b)
}
func (m *DeletePageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePageRequest.Marshal(b, m, deterministic)
}
func (m *DeletePageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePageRequest.Merge(m, src)
}
func (m *DeletePageRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePageRequest.Size(m)
}
func (m *DeletePageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePageRequest proto.InternalMessageInfo

func (m *DeletePageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PageData struct {
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	PageId               string                    `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"pageId" valid:"required"`
	UpdateTime           string                    `protobuf:"bytes,3,opt,name=update_time,json=updateTime,proto3" json:"updateTime" valid:"required"`
	CreateTime           string                    `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"createTime" valid:"required"`
	Data                 *encoding_json.RawMessage `protobuf:"bytes,5,opt,name=data,proto3,customtype=encoding/json.RawMessage" json:"data,omitempty" type:"object"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PageData) Reset()         { *m = PageData{} }
func (m *PageData) String() string { return proto.CompactTextString(m) }
func (*PageData) ProtoMessage()    {}
func (*PageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{9}
}
func (m *PageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageData.Unmarshal(m, b)
}
func (m *PageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageData.Marshal(b, m, deterministic)
}
func (m *PageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageData.Merge(m, src)
}
func (m *PageData) XXX_Size() int {
	return xxx_messageInfo_PageData.Size(m)
}
func (m *PageData) XXX_DiscardUnknown() {
	xxx_messageInfo_PageData.DiscardUnknown(m)
}

var xxx_messageInfo_PageData proto.InternalMessageInfo

func (m *PageData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PageData) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *PageData) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *PageData) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type GetPageDatasRequest struct {
	BaseListRequest      `protobuf:"bytes,1,opt,name=base_list_request,json=baseListRequest,proto3,embedded=base_list_request" json:",omitempty"`
	PageId               string            `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"pageId" valid:"required"`
	Filters              map[string]string `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetPageDatasRequest) Reset()         { *m = GetPageDatasRequest{} }
func (m *GetPageDatasRequest) String() string { return proto.CompactTextString(m) }
func (*GetPageDatasRequest) ProtoMessage()    {}
func (*GetPageDatasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{10}
}
func (m *GetPageDatasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageDatasRequest.Unmarshal(m, b)
}
func (m *GetPageDatasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageDatasRequest.Marshal(b, m, deterministic)
}
func (m *GetPageDatasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageDatasRequest.Merge(m, src)
}
func (m *GetPageDatasRequest) XXX_Size() int {
	return xxx_messageInfo_GetPageDatasRequest.Size(m)
}
func (m *GetPageDatasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageDatasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageDatasRequest proto.InternalMessageInfo

func (m *GetPageDatasRequest) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *GetPageDatasRequest) GetFilters() map[string]string {
	if m != nil {
		return m.Filters
	}
	return nil
}

type GetPageDatasResponse struct {
	BaseListResponse     `protobuf:"bytes,1,opt,name=base_list_response,json=baseListResponse,proto3,embedded=base_list_response" json:",omitempty"`
	Data                 []*PageData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPageDatasResponse) Reset()         { *m = GetPageDatasResponse{} }
func (m *GetPageDatasResponse) String() string { return proto.CompactTextString(m) }
func (*GetPageDatasResponse) ProtoMessage()    {}
func (*GetPageDatasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{11}
}
func (m *GetPageDatasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageDatasResponse.Unmarshal(m, b)
}
func (m *GetPageDatasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageDatasResponse.Marshal(b, m, deterministic)
}
func (m *GetPageDatasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageDatasResponse.Merge(m, src)
}
func (m *GetPageDatasResponse) XXX_Size() int {
	return xxx_messageInfo_GetPageDatasResponse.Size(m)
}
func (m *GetPageDatasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageDatasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageDatasResponse proto.InternalMessageInfo

func (m *GetPageDatasResponse) GetData() []*PageData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetPageDataRequest struct {
	PageId               string   `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"pageId" valid:"required"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPageDataRequest) Reset()         { *m = GetPageDataRequest{} }
func (m *GetPageDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetPageDataRequest) ProtoMessage()    {}
func (*GetPageDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{12}
}
func (m *GetPageDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageDataRequest.Unmarshal(m, b)
}
func (m *GetPageDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageDataRequest.Marshal(b, m, deterministic)
}
func (m *GetPageDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageDataRequest.Merge(m, src)
}
func (m *GetPageDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetPageDataRequest.Size(m)
}
func (m *GetPageDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageDataRequest proto.InternalMessageInfo

func (m *GetPageDataRequest) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *GetPageDataRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPageDataResponse struct {
	BaseResponse         `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,embedded=base_response" json:",omitempty"`
	Data                 *PageData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPageDataResponse) Reset()         { *m = GetPageDataResponse{} }
func (m *GetPageDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetPageDataResponse) ProtoMessage()    {}
func (*GetPageDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{13}
}
func (m *GetPageDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPageDataResponse.Unmarshal(m, b)
}
func (m *GetPageDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPageDataResponse.Marshal(b, m, deterministic)
}
func (m *GetPageDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPageDataResponse.Merge(m, src)
}
func (m *GetPageDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetPageDataResponse.Size(m)
}
func (m *GetPageDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPageDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPageDataResponse proto.InternalMessageInfo

func (m *GetPageDataResponse) GetData() *PageData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreatePageDataRequest struct {
	PageId               string                    `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"pageId" valid:"required"`
	Data                 *encoding_json.RawMessage `protobuf:"bytes,2,opt,name=data,proto3,customtype=encoding/json.RawMessage" json:"data,omitempty" type:"object"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CreatePageDataRequest) Reset()         { *m = CreatePageDataRequest{} }
func (m *CreatePageDataRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePageDataRequest) ProtoMessage()    {}
func (*CreatePageDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{14}
}
func (m *CreatePageDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePageDataRequest.Unmarshal(m, b)
}
func (m *CreatePageDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePageDataRequest.Marshal(b, m, deterministic)
}
func (m *CreatePageDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePageDataRequest.Merge(m, src)
}
func (m *CreatePageDataRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePageDataRequest.Size(m)
}
func (m *CreatePageDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePageDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePageDataRequest proto.InternalMessageInfo

func (m *CreatePageDataRequest) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

type UpdatePageDataRequest struct {
	PageId               string                    `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"pageId" valid:"required"`
	Id                   string                    `protobuf:"bytes,2,opt,name=id,proto3" json:"id" valid:"required"`
	Data                 *encoding_json.RawMessage `protobuf:"bytes,3,opt,name=data,proto3,customtype=encoding/json.RawMessage" json:"data,omitempty" type:"object"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UpdatePageDataRequest) Reset()         { *m = UpdatePageDataRequest{} }
func (m *UpdatePageDataRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePageDataRequest) ProtoMessage()    {}
func (*UpdatePageDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{15}
}
func (m *UpdatePageDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePageDataRequest.Unmarshal(m, b)
}
func (m *UpdatePageDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePageDataRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePageDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePageDataRequest.Merge(m, src)
}
func (m *UpdatePageDataRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePageDataRequest.Size(m)
}
func (m *UpdatePageDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePageDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePageDataRequest proto.InternalMessageInfo

func (m *UpdatePageDataRequest) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *UpdatePageDataRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PatchPageDataRequest struct {
	PageId               string                    `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"pageId" valid:"required"`
	Id                   string                    `protobuf:"bytes,2,opt,name=id,proto3" json:"id" valid:"required"`
	IsDelete             bool                      `protobuf:"varint,3,opt,name=is_delete,json=isDelete,proto3" json:"isDelete,omitempty"`
	Data                 *encoding_json.RawMessage `protobuf:"bytes,4,opt,name=data,proto3,customtype=encoding/json.RawMessage" json:"data,omitempty" type:"object"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PatchPageDataRequest) Reset()         { *m = PatchPageDataRequest{} }
func (m *PatchPageDataRequest) String() string { return proto.CompactTextString(m) }
func (*PatchPageDataRequest) ProtoMessage()    {}
func (*PatchPageDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{16}
}
func (m *PatchPageDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchPageDataRequest.Unmarshal(m, b)
}
func (m *PatchPageDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchPageDataRequest.Marshal(b, m, deterministic)
}
func (m *PatchPageDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchPageDataRequest.Merge(m, src)
}
func (m *PatchPageDataRequest) XXX_Size() int {
	return xxx_messageInfo_PatchPageDataRequest.Size(m)
}
func (m *PatchPageDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchPageDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchPageDataRequest proto.InternalMessageInfo

func (m *PatchPageDataRequest) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *PatchPageDataRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PatchPageDataRequest) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

type DeletePageDataRequest struct {
	PageId               string   `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"pageId" valid:"required"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePageDataRequest) Reset()         { *m = DeletePageDataRequest{} }
func (m *DeletePageDataRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePageDataRequest) ProtoMessage()    {}
func (*DeletePageDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d737b23da87684a, []int{17}
}
func (m *DeletePageDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePageDataRequest.Unmarshal(m, b)
}
func (m *DeletePageDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePageDataRequest.Marshal(b, m, deterministic)
}
func (m *DeletePageDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePageDataRequest.Merge(m, src)
}
func (m *DeletePageDataRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePageDataRequest.Size(m)
}
func (m *DeletePageDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePageDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePageDataRequest proto.InternalMessageInfo

func (m *DeletePageDataRequest) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *DeletePageDataRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*PageConfig)(nil), "idas.endpoint.PageConfig")
	proto.RegisterType((*GetPagesRequest)(nil), "idas.endpoint.GetPagesRequest")
	proto.RegisterType((*GetPagesResponse)(nil), "idas.endpoint.GetPagesResponse")
	proto.RegisterType((*GetPageRequest)(nil), "idas.endpoint.GetPageRequest")
	proto.RegisterType((*GetPageResponse)(nil), "idas.endpoint.GetPageResponse")
	proto.RegisterType((*CreatePageRequest)(nil), "idas.endpoint.CreatePageRequest")
	proto.RegisterType((*UpdatePageRequest)(nil), "idas.endpoint.UpdatePageRequest")
	proto.RegisterType((*PatchPageRequest)(nil), "idas.endpoint.PatchPageRequest")
	proto.RegisterType((*DeletePageRequest)(nil), "idas.endpoint.DeletePageRequest")
	proto.RegisterType((*PageData)(nil), "idas.endpoint.PageData")
	proto.RegisterType((*GetPageDatasRequest)(nil), "idas.endpoint.GetPageDatasRequest")
	proto.RegisterMapType((map[string]string)(nil), "idas.endpoint.GetPageDatasRequest.FiltersEntry")
	proto.RegisterType((*GetPageDatasResponse)(nil), "idas.endpoint.GetPageDatasResponse")
	proto.RegisterType((*GetPageDataRequest)(nil), "idas.endpoint.GetPageDataRequest")
	proto.RegisterType((*GetPageDataResponse)(nil), "idas.endpoint.GetPageDataResponse")
	proto.RegisterType((*CreatePageDataRequest)(nil), "idas.endpoint.CreatePageDataRequest")
	proto.RegisterType((*UpdatePageDataRequest)(nil), "idas.endpoint.UpdatePageDataRequest")
	proto.RegisterType((*PatchPageDataRequest)(nil), "idas.endpoint.PatchPageDataRequest")
	proto.RegisterType((*DeletePageDataRequest)(nil), "idas.endpoint.DeletePageDataRequest")
}

func init() { proto.RegisterFile("endpoints/pages.proto", fileDescriptor_6d737b23da87684a) }

var fileDescriptor_6d737b23da87684a = []byte{
	// 990 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x41, 0x6f, 0xdc, 0x44,
	0x14, 0xae, 0xbd, 0x9b, 0xcd, 0xe6, 0xa5, 0x69, 0x93, 0xe9, 0xa6, 0x2c, 0xa1, 0x5a, 0xaf, 0x7c,
	0x8a, 0x68, 0xe2, 0x85, 0xe4, 0xd0, 0x2a, 0x45, 0xa0, 0x6e, 0x42, 0x51, 0x25, 0x2a, 0x22, 0x03,
	0x12, 0xe2, 0xb2, 0x1a, 0xdb, 0x13, 0x77, 0xda, 0x5d, 0x8f, 0xeb, 0x99, 0x0d, 0x5a, 0x89, 0xff,
	0xc0, 0x81, 0x1b, 0xe2, 0x07, 0x20, 0x0e, 0xdc, 0x38, 0x20, 0x21, 0x71, 0xe5, 0xc8, 0x39, 0x07,
	0x5f, 0xb8, 0xed, 0x11, 0xee, 0x08, 0x79, 0x6c, 0xaf, 0xed, 0x95, 0xd3, 0x24, 0x6e, 0xb4, 0x97,
	0xc8, 0xfb, 0xe6, 0xbd, 0xe7, 0xf7, 0x7d, 0xcf, 0xdf, 0x7c, 0x0a, 0x6c, 0x12, 0xcf, 0xf1, 0x19,
	0xf5, 0x04, 0xef, 0xf9, 0xd8, 0x25, 0xdc, 0xf0, 0x03, 0x26, 0x18, 0x5a, 0xa3, 0x0e, 0xe6, 0x46,
	0x7a, 0xb6, 0xd5, 0x72, 0x99, 0xcb, 0xe4, 0x49, 0x2f, 0x7a, 0x8a, 0x93, 0xb6, 0x5a, 0x59, 0xad,
	0x85, 0x39, 0x49, 0xa2, 0x68, 0xc4, 0x1c, 0x32, 0x2c, 0xb4, 0xd3, 0xff, 0x53, 0x01, 0x8e, 0xb1,
	0x4b, 0x0e, 0x99, 0x77, 0x42, 0x5d, 0xf4, 0x2e, 0xa8, 0xd4, 0x69, 0x2b, 0x5d, 0x65, 0x7b, 0xa5,
	0xbf, 0x35, 0x0d, 0x35, 0x95, 0x3a, 0xff, 0x84, 0xda, 0xfa, 0x29, 0x1e, 0x52, 0xe7, 0x40, 0x0f,
	0xc8, 0xab, 0x31, 0x0d, 0x88, 0xa3, 0x9b, 0x2a, 0x75, 0xd0, 0x21, 0xac, 0x8e, 0x7d, 0x07, 0x0b,
	0x32, 0x10, 0x74, 0x44, 0xda, 0xaa, 0x2c, 0xd2, 0xa7, 0xa1, 0x06, 0x71, 0xf8, 0x0b, 0x3a, 0x22,
	0xa5, 0xc5, 0xb9, 0xf3, 0xa8, 0x89, 0x1d, 0x90, 0x59, 0x93, 0x5a, 0xd6, 0x24, 0x0e, 0x9f, 0xdf,
	0x24, 0x3b, 0x47, 0xf7, 0xa0, 0xee, 0xe1, 0x11, 0x69, 0xd7, 0x65, 0x75, 0x73, 0x1a, 0x6a, 0xf2,
	0xb7, 0x29, 0xff, 0xa2, 0x2e, 0xac, 0x3a, 0x84, 0xdb, 0x01, 0xf5, 0x05, 0x65, 0x5e, 0x7b, 0x29,
	0x4a, 0x32, 0xf3, 0x21, 0xf4, 0x10, 0x1a, 0x27, 0x94, 0x0c, 0x1d, 0xde, 0x6e, 0x74, 0x6b, 0xdb,
	0xab, 0x7b, 0x5d, 0x43, 0x92, 0xcc, 0x49, 0x70, 0x4a, 0x6d, 0x62, 0xc4, 0xb4, 0x19, 0x4f, 0xa2,
	0x94, 0x98, 0x27, 0x33, 0xc9, 0x47, 0x08, 0xea, 0xd4, 0x66, 0x5e, 0x7b, 0x59, 0x36, 0x95, 0xcf,
	0x68, 0x07, 0x80, 0xf2, 0x81, 0x43, 0x39, 0xb6, 0x86, 0xa4, 0xdd, 0xec, 0x2a, 0xdb, 0xcd, 0xfe,
	0xda, 0x34, 0xd4, 0x56, 0x28, 0x3f, 0x8a, 0x83, 0x66, 0xf6, 0xa8, 0xff, 0xa2, 0xc0, 0xed, 0x4f,
	0x88, 0x88, 0x76, 0xc0, 0x4d, 0xf2, 0x6a, 0x4c, 0xb8, 0x40, 0x16, 0x6c, 0x44, 0x6b, 0x1b, 0x0c,
	0x29, 0x17, 0x83, 0x20, 0x0e, 0xca, 0xa5, 0xac, 0xee, 0x75, 0x8c, 0xc2, 0xfe, 0x8d, 0x3e, 0xe6,
	0xe4, 0x53, 0xca, 0x45, 0x52, 0xda, 0xbf, 0xfb, 0x67, 0xa8, 0xdd, 0xf8, 0x2b, 0xd4, 0x94, 0x88,
	0xc2, 0x1d, 0x36, 0xa2, 0x82, 0x8c, 0x7c, 0x31, 0x31, 0x6f, 0x5b, 0xc5, 0x44, 0xf4, 0x00, 0x1a,
	0x5c, 0x60, 0x31, 0xe6, 0x72, 0x71, 0xb7, 0xf6, 0xb4, 0x52, 0xcc, 0xd1, 0x58, 0x9f, 0xcb, 0x34,
	0x33, 0x49, 0xd7, 0x7f, 0x52, 0x60, 0x3d, 0x1b, 0x98, 0xfb, 0xcc, 0xe3, 0x04, 0x11, 0x40, 0xf9,
	0x89, 0xe3, 0x68, 0x32, 0xb2, 0x76, 0xee, 0xc8, 0x71, 0xda, 0xb9, 0x33, 0xaf, 0x5b, 0x73, 0x99,
	0x68, 0x17, 0xea, 0x0e, 0x16, 0xb8, 0xad, 0xca, 0x35, 0xbd, 0x3d, 0xd7, 0x38, 0xfb, 0x8e, 0x4d,
	0x99, 0xa6, 0x7f, 0x00, 0xb7, 0x92, 0x49, 0x53, 0xd4, 0x57, 0xf8, 0xbe, 0xf5, 0x1f, 0xb2, 0xcd,
	0xcc, 0x06, 0xf8, 0x0a, 0xd6, 0x24, 0xce, 0x39, 0x88, 0xef, 0x94, 0x40, 0xbc, 0x10, 0xde, 0x4d,
	0x2b, 0x97, 0x95, 0x83, 0xa6, 0x5c, 0x06, 0xda, 0xaf, 0x0a, 0x6c, 0x1c, 0x4a, 0x05, 0xe4, 0xe1,
	0xbd, 0x97, 0x08, 0x21, 0x06, 0x78, 0x2f, 0x15, 0x42, 0x29, 0xc4, 0x52, 0x71, 0xa8, 0xaf, 0x13,
	0x47, 0xad, 0xa2, 0x38, 0xea, 0x99, 0x38, 0xf4, 0xef, 0x54, 0xd8, 0xf8, 0x52, 0xca, 0xbf, 0xe2,
	0x5a, 0x66, 0x18, 0xd5, 0xaa, 0x18, 0x6b, 0xaf, 0xc3, 0x58, 0xaf, 0x88, 0x71, 0xa9, 0xf2, 0x05,
	0xf0, 0xb7, 0x0a, 0xeb, 0xc7, 0x58, 0xd8, 0xcf, 0xab, 0x12, 0xd2, 0x29, 0x10, 0x02, 0x67, 0xa1,
	0xd6, 0xe0, 0x22, 0xa0, 0x9e, 0x9b, 0xc0, 0xdf, 0x29, 0x81, 0x5f, 0x48, 0xbb, 0x26, 0x2a, 0x3a,
	0x79, 0x2a, 0x8a, 0x73, 0x48, 0x5a, 0x1e, 0xc1, 0x4a, 0x44, 0x0b, 0x19, 0x12, 0x41, 0xe4, 0x85,
	0xd9, 0xec, 0x77, 0xce, 0x42, 0xad, 0x6e, 0x31, 0x36, 0x9c, 0x86, 0x1a, 0xa2, 0xfc, 0x48, 0x9e,
	0xe5, 0x24, 0xd2, 0x4c, 0x63, 0xe8, 0xc3, 0x12, 0x4e, 0xb5, 0x5c, 0xf5, 0x9d, 0x19, 0xa1, 0xb9,
	0xf2, 0x1c, 0xcb, 0x1f, 0xc1, 0x46, 0xdc, 0xa9, 0xea, 0x6d, 0xf0, 0xbb, 0x0a, 0xcd, 0xa8, 0xf6,
	0x08, 0x0b, 0x7c, 0xa5, 0xf5, 0x3c, 0x80, 0xe5, 0xc8, 0x70, 0x07, 0xd4, 0x49, 0x36, 0xd4, 0x99,
	0x86, 0x5a, 0x23, 0x0a, 0x3d, 0x2d, 0x2f, 0x4a, 0xce, 0xe6, 0xfd, 0xb5, 0x76, 0x1d, 0xfe, 0x5a,
	0xaf, 0xe4, 0xaf, 0x8f, 0x93, 0xbb, 0x29, 0xde, 0xec, 0xee, 0x59, 0xa8, 0xb5, 0x89, 0x67, 0x33,
	0x87, 0x7a, 0x6e, 0xef, 0x05, 0x67, 0x9e, 0x61, 0xe2, 0x6f, 0x9e, 0x11, 0xce, 0xb1, 0x1b, 0xf5,
	0x5a, 0x13, 0x13, 0x9f, 0x1c, 0xe8, 0xcc, 0x7a, 0x41, 0x6c, 0xa1, 0x27, 0xf7, 0xd5, 0x6f, 0x2a,
	0xdc, 0x49, 0x2e, 0xd3, 0x88, 0xc1, 0x05, 0x5b, 0x5d, 0xc5, 0x0d, 0x3c, 0x85, 0xe5, 0x13, 0x3a,
	0x14, 0x24, 0x48, 0xc5, 0xd0, 0x9b, 0x1b, 0xa9, 0x04, 0x91, 0xf1, 0x24, 0xae, 0xf8, 0xd8, 0x13,
	0xc1, 0xc4, 0x4c, 0xeb, 0xb7, 0x0e, 0xe0, 0x66, 0xfe, 0x00, 0xad, 0x43, 0xed, 0x25, 0x99, 0xc4,
	0x9f, 0x90, 0x19, 0x3d, 0xa2, 0x16, 0x2c, 0x9d, 0xe2, 0xe1, 0x38, 0xd1, 0xb1, 0x19, 0xff, 0x38,
	0x50, 0x1f, 0x2a, 0xfa, 0xcf, 0x0a, 0xb4, 0x8a, 0x6f, 0x5a, 0xac, 0xeb, 0xde, 0x2f, 0xb8, 0xee,
	0x5b, 0x25, 0xd6, 0x14, 0x8d, 0x95, 0x2c, 0x7a, 0x02, 0x28, 0x37, 0xeb, 0x1b, 0xaf, 0x20, 0x56,
	0x5a, 0xed, 0x52, 0x12, 0xfd, 0x51, 0x29, 0x7c, 0x63, 0x0b, 0x30, 0xed, 0xfb, 0x05, 0xd3, 0xbe,
	0x80, 0x99, 0xef, 0x15, 0xd8, 0xcc, 0x2c, 0xfb, 0x1c, 0x76, 0x94, 0x2b, 0xb1, 0xf3, 0x38, 0xf7,
	0xfe, 0x8a, 0xc2, 0xfc, 0x43, 0x81, 0xcd, 0xcc, 0x90, 0xaf, 0x65, 0xaa, 0x78, 0x67, 0xea, 0xa5,
	0x6e, 0xc7, 0x14, 0x41, 0xad, 0x3a, 0x82, 0x7f, 0x15, 0x68, 0xcd, 0x0c, 0x74, 0xe1, 0x00, 0xf6,
	0xf3, 0xae, 0x56, 0x93, 0xbe, 0x74, 0xf7, 0x42, 0x37, 0x4b, 0x51, 0xd7, 0xab, 0xa3, 0xfe, 0x16,
	0x36, 0x33, 0x43, 0x5b, 0x34, 0xea, 0xfe, 0xfe, 0xd7, 0xef, 0xbb, 0x54, 0x3c, 0x1f, 0x5b, 0x86,
	0xcd, 0x46, 0xbd, 0x67, 0xd4, 0x0e, 0xd8, 0x67, 0x3e, 0xdf, 0xb5, 0xbd, 0x5e, 0x24, 0x81, 0x9e,
	0xff, 0xd2, 0xed, 0xa5, 0x32, 0x78, 0x94, 0x3e, 0x1c, 0xdf, 0xb0, 0x1a, 0xf2, 0x9f, 0xce, 0xfd,
	0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x93, 0xc9, 0x5b, 0xf6, 0xdc, 0x0e, 0x00, 0x00,
}
