// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: v1/sessions.proto

package endpoint

import (
	fmt "fmt"
	models "github.com/MicroOps-cn/idas/pkg/service/models"
	github_com_MicroOps_cn_idas_pkg_utils_sign "github.com/MicroOps-cn/idas/pkg/utils/sign"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetSessionsRequest struct {
	BaseListRequest      `protobuf:"bytes,1,opt,name=base_list_request,json=baseListRequest,proto3,embedded=base_list_request" json:"base_list_request"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"userId,omitempty" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionsRequest) Reset()         { *m = GetSessionsRequest{} }
func (m *GetSessionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSessionsRequest) ProtoMessage()    {}
func (*GetSessionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f5a3ba79a772164, []int{0}
}
func (m *GetSessionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionsRequest.Unmarshal(m, b)
}
func (m *GetSessionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionsRequest.Marshal(b, m, deterministic)
}
func (m *GetSessionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionsRequest.Merge(m, src)
}
func (m *GetSessionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSessionsRequest.Size(m)
}
func (m *GetSessionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionsRequest proto.InternalMessageInfo

func (m *GetSessionsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SessionInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	CreateTime           string   `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"createTime,omitempty" valid:"required"`
	Expiry               string   `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry" valid:"required"`
	LastSeen             string   `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"lastSeen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionInfo) Reset()         { *m = SessionInfo{} }
func (m *SessionInfo) String() string { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()    {}
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f5a3ba79a772164, []int{1}
}
func (m *SessionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionInfo.Unmarshal(m, b)
}
func (m *SessionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionInfo.Marshal(b, m, deterministic)
}
func (m *SessionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionInfo.Merge(m, src)
}
func (m *SessionInfo) XXX_Size() int {
	return xxx_messageInfo_SessionInfo.Size(m)
}
func (m *SessionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SessionInfo proto.InternalMessageInfo

func (m *SessionInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SessionInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *SessionInfo) GetExpiry() string {
	if m != nil {
		return m.Expiry
	}
	return ""
}

func (m *SessionInfo) GetLastSeen() string {
	if m != nil {
		return m.LastSeen
	}
	return ""
}

type GetSessionsResponse struct {
	BaseListRequest      `protobuf:"bytes,1,opt,name=base_list_request,json=baseListRequest,proto3,embedded=base_list_request" json:"base_list_request"`
	Data                 []*SessionInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetSessionsResponse) Reset()         { *m = GetSessionsResponse{} }
func (m *GetSessionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetSessionsResponse) ProtoMessage()    {}
func (*GetSessionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f5a3ba79a772164, []int{2}
}
func (m *GetSessionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionsResponse.Unmarshal(m, b)
}
func (m *GetSessionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionsResponse.Marshal(b, m, deterministic)
}
func (m *GetSessionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionsResponse.Merge(m, src)
}
func (m *GetSessionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetSessionsResponse.Size(m)
}
func (m *GetSessionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionsResponse proto.InternalMessageInfo

func (m *GetSessionsResponse) GetData() []*SessionInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteSessionRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSessionRequest) Reset()         { *m = DeleteSessionRequest{} }
func (m *DeleteSessionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionRequest) ProtoMessage()    {}
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f5a3ba79a772164, []int{3}
}
func (m *DeleteSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSessionRequest.Unmarshal(m, b)
}
func (m *DeleteSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSessionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSessionRequest.Merge(m, src)
}
func (m *DeleteSessionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSessionRequest.Size(m)
}
func (m *DeleteSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSessionRequest proto.InternalMessageInfo

func (m *DeleteSessionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AuthenticationRequest struct {
	Username             string                                                   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string                                                   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	AuthMethod           models.AuthMeta_Method                                   `protobuf:"varint,3,opt,name=auth_method,json=authMethod,proto3,enum=idas.service.models.AuthMeta_Method" json:"authMethod,omitempty"`
	AuthAlgorithm        github_com_MicroOps_cn_idas_pkg_utils_sign.AuthAlgorithm `protobuf:"bytes,4,opt,name=auth_algorithm,json=authAlgorithm,proto3,customtype=github.com/MicroOps-cn/idas/pkg/utils/sign.AuthAlgorithm" json:"authAlgorithm,omitempty"`
	AuthKey              string                                                   `protobuf:"bytes,5,opt,name=auth_key,json=authKey,proto3" json:"authKey,omitempty"`
	AuthSecret           string                                                   `protobuf:"bytes,6,opt,name=auth_secret,json=authSecret,proto3" json:"authSecret,omitempty"`
	AuthSign             string                                                   `protobuf:"bytes,7,opt,name=auth_sign,json=authSign,proto3" json:"authSign,omitempty"`
	Payload              string                                                   `protobuf:"bytes,8,opt,name=payload,proto3" json:"-"`
	XXX_NoUnkeyedLiteral struct{}                                                 `json:"-"`
	XXX_unrecognized     []byte                                                   `json:"-"`
	XXX_sizecache        int32                                                    `json:"-"`
}

func (m *AuthenticationRequest) Reset()         { *m = AuthenticationRequest{} }
func (m *AuthenticationRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticationRequest) ProtoMessage()    {}
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f5a3ba79a772164, []int{4}
}
func (m *AuthenticationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationRequest.Unmarshal(m, b)
}
func (m *AuthenticationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationRequest.Merge(m, src)
}
func (m *AuthenticationRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticationRequest.Size(m)
}
func (m *AuthenticationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationRequest proto.InternalMessageInfo

func (m *AuthenticationRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthenticationRequest) GetAuthMethod() models.AuthMeta_Method {
	if m != nil {
		return m.AuthMethod
	}
	return models.AuthMeta_basic
}

func (m *AuthenticationRequest) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

func (m *AuthenticationRequest) GetAuthSecret() string {
	if m != nil {
		return m.AuthSecret
	}
	return ""
}

func (m *AuthenticationRequest) GetAuthSign() string {
	if m != nil {
		return m.AuthSign
	}
	return ""
}

func (m *AuthenticationRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type UserLoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username" valid:"required"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password" valid:"required"`
	AutoLogin            bool     `protobuf:"varint,3,opt,name=auto_login,json=autoLogin,proto3" json:"autoLogin,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f5a3ba79a772164, []int{5}
}
func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserLoginRequest) GetAutoLogin() bool {
	if m != nil {
		return m.AutoLogin
	}
	return false
}

func (m *UserLoginRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSessionsRequest)(nil), "idas.endpoint.GetSessionsRequest")
	proto.RegisterType((*SessionInfo)(nil), "idas.endpoint.SessionInfo")
	proto.RegisterType((*GetSessionsResponse)(nil), "idas.endpoint.GetSessionsResponse")
	proto.RegisterType((*DeleteSessionRequest)(nil), "idas.endpoint.DeleteSessionRequest")
	proto.RegisterType((*AuthenticationRequest)(nil), "idas.endpoint.AuthenticationRequest")
	proto.RegisterType((*UserLoginRequest)(nil), "idas.endpoint.UserLoginRequest")
}

func init() { proto.RegisterFile("v1/sessions.proto", fileDescriptor_4f5a3ba79a772164) }

var fileDescriptor_4f5a3ba79a772164 = []byte{
	// 727 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcd, 0x4e, 0xdc, 0x48,
	0x10, 0xc6, 0x03, 0xcc, 0x4f, 0x8f, 0x60, 0xa1, 0x81, 0xc5, 0x9a, 0x03, 0x1e, 0x59, 0x7b, 0x18,
	0xad, 0xc0, 0x5e, 0x40, 0x42, 0xfb, 0xc3, 0x05, 0x6b, 0xa5, 0x15, 0x5a, 0x46, 0xbb, 0x32, 0xec,
	0x65, 0x73, 0xb0, 0x7a, 0xc6, 0x15, 0x4f, 0x0b, 0xdb, 0xed, 0xb8, 0x7b, 0x26, 0x99, 0x6b, 0x5e,
	0x23, 0xcf, 0x90, 0xf7, 0xc8, 0x31, 0x67, 0x0e, 0x7e, 0x00, 0x1f, 0x23, 0x45, 0xca, 0x31, 0xea,
	0xb6, 0x3d, 0x7f, 0x1a, 0x09, 0xe5, 0x90, 0x5b, 0xf7, 0x57, 0xf5, 0x55, 0x7d, 0xd5, 0xf5, 0xd9,
	0x68, 0x7f, 0x72, 0x6e, 0x73, 0xe0, 0x9c, 0xb2, 0x98, 0x5b, 0x49, 0xca, 0x04, 0xc3, 0x3b, 0xd4,
	0x27, 0xdc, 0x82, 0xd8, 0x4f, 0x18, 0x8d, 0x45, 0xe7, 0x30, 0x60, 0x01, 0x53, 0x11, 0x5b, 0x9e,
	0x8a, 0xa4, 0xce, 0xce, 0xe4, 0xdc, 0x1e, 0x10, 0x0e, 0xe5, 0x15, 0x8b, 0x69, 0x02, 0xdc, 0x8e,
	0x98, 0x0f, 0x61, 0x59, 0xc7, 0x7c, 0xaf, 0x21, 0xfc, 0x17, 0x88, 0xfb, 0xb2, 0xba, 0x0b, 0xaf,
	0xc6, 0xc0, 0x05, 0x7e, 0x40, 0xfb, 0x92, 0xe8, 0x85, 0x94, 0x0b, 0x2f, 0x2d, 0x40, 0x5d, 0xeb,
	0x6a, 0xbd, 0xf6, 0xc5, 0x89, 0xb5, 0xd4, 0xda, 0x72, 0x08, 0x87, 0x3b, 0xca, 0x45, 0x49, 0x75,
	0x9a, 0x1f, 0x32, 0x63, 0xe3, 0x63, 0x66, 0x68, 0xee, 0x0f, 0x83, 0xe5, 0x10, 0xbe, 0x41, 0x8d,
	0x31, 0x87, 0xd4, 0xa3, 0xbe, 0x5e, 0xeb, 0x6a, 0xbd, 0x96, 0xd3, 0xcb, 0x33, 0x63, 0x4f, 0x42,
	0xb7, 0xfe, 0x29, 0x8b, 0xa8, 0x80, 0x28, 0x11, 0xd3, 0x4f, 0x99, 0xb1, 0x37, 0x21, 0x21, 0xf5,
	0x7f, 0x37, 0x65, 0x67, 0x9a, 0x82, 0x6f, 0xba, 0xf5, 0x22, 0xcb, 0xfc, 0xac, 0xa1, 0x76, 0x29,
	0xf6, 0x36, 0x7e, 0xc9, 0xf0, 0xcf, 0xa8, 0x46, 0x7d, 0xa5, 0xac, 0xe5, 0x74, 0xf2, 0xcc, 0xa8,
	0x51, 0x7f, 0x2d, 0xbf, 0x46, 0x7d, 0xdc, 0x47, 0xed, 0x61, 0x0a, 0x44, 0x80, 0x27, 0x68, 0x04,
	0xa5, 0x84, 0xd3, 0x3c, 0x33, 0x0e, 0x0b, 0xf8, 0x81, 0x46, 0xf0, 0x8c, 0x0c, 0x34, 0xcf, 0xc4,
	0x57, 0xa8, 0x0e, 0x6f, 0x12, 0x9a, 0x4e, 0xf5, 0x4d, 0x55, 0xe9, 0x24, 0xcf, 0x8c, 0x12, 0x59,
	0x3f, 0x42, 0x11, 0xc3, 0x97, 0xa8, 0x15, 0x12, 0x2e, 0x3c, 0x0e, 0x10, 0xeb, 0x5b, 0x8a, 0xfa,
	0x63, 0x9e, 0x19, 0x58, 0x82, 0xf7, 0x00, 0xf1, 0x5c, 0x82, 0xdb, 0xac, 0x30, 0xf3, 0x9d, 0x86,
	0x0e, 0x96, 0xf6, 0xc4, 0x13, 0x16, 0x73, 0xf8, 0x4e, 0x8b, 0xb2, 0xd0, 0x96, 0x4f, 0x04, 0xd1,
	0x6b, 0xdd, 0xcd, 0x5e, 0xfb, 0xa2, 0xb3, 0x52, 0x68, 0xe1, 0xfd, 0x5d, 0x95, 0x67, 0x3a, 0xe8,
	0xf0, 0x4f, 0x08, 0x41, 0x40, 0x19, 0xaa, 0xea, 0x7c, 0xc3, 0x76, 0xcc, 0x2f, 0x9b, 0xe8, 0xe8,
	0x66, 0x2c, 0x46, 0x10, 0x0b, 0x3a, 0x24, 0x62, 0xa1, 0x4a, 0x07, 0x35, 0xe5, 0xf6, 0x63, 0x12,
	0x41, 0x51, 0xcb, 0x9d, 0xdd, 0x65, 0x2c, 0x21, 0x9c, 0xbf, 0x66, 0x69, 0xe9, 0x29, 0x77, 0x76,
	0xc7, 0x1e, 0x6a, 0x93, 0xb1, 0x18, 0x79, 0x11, 0x88, 0x11, 0xf3, 0xd5, 0x96, 0x76, 0x2f, 0x7e,
	0x2a, 0x86, 0xe1, 0x90, 0x4e, 0xe8, 0x10, 0xac, 0xf2, 0x63, 0x90, 0x8d, 0xfb, 0x20, 0x88, 0xd5,
	0x57, 0xb9, 0x8e, 0x2e, 0x5d, 0x41, 0x0a, 0x70, 0xc4, 0x16, 0xcc, 0xe9, 0xa2, 0x39, 0x8a, 0xdf,
	0x6a, 0x68, 0x57, 0x75, 0x20, 0x61, 0xc0, 0x52, 0x2a, 0x46, 0x51, 0xb9, 0xcf, 0x17, 0xf2, 0x69,
	0x9f, 0x32, 0xe3, 0xd7, 0x80, 0x8a, 0xd1, 0x78, 0x60, 0x0d, 0x59, 0x64, 0xf7, 0xe9, 0x30, 0x65,
	0xff, 0x24, 0xfc, 0x6c, 0x18, 0xdb, 0x52, 0x82, 0x9d, 0x3c, 0x06, 0xf6, 0x58, 0xd0, 0x90, 0xdb,
	0x9c, 0x06, 0xb1, 0x92, 0x70, 0x53, 0xd5, 0xc9, 0x33, 0xe3, 0x98, 0x2c, 0x02, 0x0b, 0x0a, 0x76,
	0x96, 0x02, 0xf8, 0x17, 0xd4, 0x54, 0x1a, 0x1e, 0x61, 0xaa, 0x6f, 0xab, 0xee, 0x47, 0x79, 0x66,
	0xec, 0x4b, 0xec, 0x6f, 0x98, 0x2e, 0xf0, 0x1a, 0x25, 0x84, 0x7f, 0x2b, 0xdf, 0x85, 0xc3, 0x30,
	0x05, 0xa1, 0xd7, 0x15, 0x69, 0x36, 0xf1, 0xbd, 0x42, 0x57, 0x27, 0x2e, 0x50, 0xe9, 0xdd, 0x82,
	0x4a, 0x83, 0x58, 0x6f, 0xcc, 0xbd, 0xab, 0x52, 0x68, 0xb0, 0xe4, 0xdd, 0x0a, 0xc3, 0x06, 0x6a,
	0x24, 0x64, 0x1a, 0x32, 0xe2, 0xeb, 0x4d, 0x45, 0xd9, 0xce, 0x33, 0x43, 0x3b, 0x73, 0x2b, 0xd4,
	0x7c, 0xd2, 0xd0, 0xde, 0x7f, 0x1c, 0xd2, 0x3b, 0x16, 0xd0, 0xd9, 0xd6, 0xaf, 0x57, 0xb7, 0xee,
	0x74, 0xf3, 0xcc, 0x98, 0x61, 0x6b, 0x7d, 0x34, 0xf7, 0xc5, 0xf5, 0xaa, 0x2f, 0x0a, 0x76, 0x85,
	0xad, 0x67, 0xcf, 0x9c, 0x73, 0x85, 0xe4, 0xd0, 0xcc, 0x0b, 0xa5, 0x20, 0x65, 0x9c, 0xa6, 0x73,
	0x9c, 0x67, 0xc6, 0x81, 0x44, 0x95, 0xca, 0x85, 0x41, 0x5b, 0x33, 0x10, 0x63, 0xb4, 0x25, 0xff,
	0xb1, 0x85, 0x0b, 0x5c, 0x75, 0x76, 0x2e, 0xff, 0x3f, 0x7f, 0xce, 0x05, 0xd5, 0x97, 0xf5, 0x47,
	0x75, 0xf8, 0x77, 0x63, 0x50, 0x57, 0xff, 0xe7, 0xcb, 0xaf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x47,
	0xd8, 0x0e, 0x37, 0xfc, 0x05, 0x00, 0x00,
}
