// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: v1/users.proto

package endpoint

import (
	fmt "fmt"
	gogoproto "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

var E_GoprotoEnumPrefix = gogoproto.E_GoprotoEnumPrefix

var E_GoprotoEnumStringer = gogoproto.E_GoprotoEnumStringer

var E_EnumStringer = gogoproto.E_EnumStringer

var E_EnumCustomname = gogoproto.E_EnumCustomname

var E_Enumdecl = gogoproto.E_Enumdecl

var E_EnumvalueCustomname = gogoproto.E_EnumvalueCustomname

var E_GoprotoGettersAll = gogoproto.E_GoprotoGettersAll

var E_GoprotoEnumPrefixAll = gogoproto.E_GoprotoEnumPrefixAll

var E_GoprotoStringerAll = gogoproto.E_GoprotoStringerAll

var E_VerboseEqualAll = gogoproto.E_VerboseEqualAll

var E_FaceAll = gogoproto.E_FaceAll

var E_GostringAll = gogoproto.E_GostringAll

var E_PopulateAll = gogoproto.E_PopulateAll

var E_StringerAll = gogoproto.E_StringerAll

var E_OnlyoneAll = gogoproto.E_OnlyoneAll

var E_EqualAll = gogoproto.E_EqualAll

var E_DescriptionAll = gogoproto.E_DescriptionAll

var E_TestgenAll = gogoproto.E_TestgenAll

var E_BenchgenAll = gogoproto.E_BenchgenAll

var E_MarshalerAll = gogoproto.E_MarshalerAll

var E_UnmarshalerAll = gogoproto.E_UnmarshalerAll

var E_StableMarshalerAll = gogoproto.E_StableMarshalerAll

var E_SizerAll = gogoproto.E_SizerAll

var E_GoprotoEnumStringerAll = gogoproto.E_GoprotoEnumStringerAll

var E_EnumStringerAll = gogoproto.E_EnumStringerAll

var E_UnsafeMarshalerAll = gogoproto.E_UnsafeMarshalerAll

var E_UnsafeUnmarshalerAll = gogoproto.E_UnsafeUnmarshalerAll

var E_GoprotoExtensionsMapAll = gogoproto.E_GoprotoExtensionsMapAll

var E_GoprotoUnrecognizedAll = gogoproto.E_GoprotoUnrecognizedAll

var E_GogoprotoImport = gogoproto.E_GogoprotoImport

var E_ProtosizerAll = gogoproto.E_ProtosizerAll

var E_CompareAll = gogoproto.E_CompareAll

var E_TypedeclAll = gogoproto.E_TypedeclAll

var E_EnumdeclAll = gogoproto.E_EnumdeclAll

var E_GoprotoRegistration = gogoproto.E_GoprotoRegistration

var E_MessagenameAll = gogoproto.E_MessagenameAll

var E_GoprotoSizecacheAll = gogoproto.E_GoprotoSizecacheAll

var E_GoprotoUnkeyedAll = gogoproto.E_GoprotoUnkeyedAll

var E_GoprotoGetters = gogoproto.E_GoprotoGetters

var E_GoprotoStringer = gogoproto.E_GoprotoStringer

var E_VerboseEqual = gogoproto.E_VerboseEqual

var E_Face = gogoproto.E_Face

var E_Gostring = gogoproto.E_Gostring

var E_Populate = gogoproto.E_Populate

var E_Stringer = gogoproto.E_Stringer

var E_Onlyone = gogoproto.E_Onlyone

var E_Equal = gogoproto.E_Equal

var E_Description = gogoproto.E_Description

var E_Testgen = gogoproto.E_Testgen

var E_Benchgen = gogoproto.E_Benchgen

var E_Marshaler = gogoproto.E_Marshaler

var E_Unmarshaler = gogoproto.E_Unmarshaler

var E_StableMarshaler = gogoproto.E_StableMarshaler

var E_Sizer = gogoproto.E_Sizer

var E_UnsafeMarshaler = gogoproto.E_UnsafeMarshaler

var E_UnsafeUnmarshaler = gogoproto.E_UnsafeUnmarshaler

var E_GoprotoExtensionsMap = gogoproto.E_GoprotoExtensionsMap

var E_GoprotoUnrecognized = gogoproto.E_GoprotoUnrecognized

var E_Protosizer = gogoproto.E_Protosizer

var E_Compare = gogoproto.E_Compare

var E_Typedecl = gogoproto.E_Typedecl

var E_Messagename = gogoproto.E_Messagename

var E_GoprotoSizecache = gogoproto.E_GoprotoSizecache

var E_GoprotoUnkeyed = gogoproto.E_GoprotoUnkeyed

var E_Nullable = gogoproto.E_Nullable

var E_Embed = gogoproto.E_Embed

var E_Customtype = gogoproto.E_Customtype

var E_Customname = gogoproto.E_Customname

var E_Jsontag = gogoproto.E_Jsontag

var E_Moretags = gogoproto.E_Moretags

var E_Casttype = gogoproto.E_Casttype

var E_Castkey = gogoproto.E_Castkey

var E_Castvalue = gogoproto.E_Castvalue

var E_Stdtime = gogoproto.E_Stdtime

var E_Stdduration = gogoproto.E_Stdduration

var E_Wktpointer = gogoproto.E_Wktpointer

type UserStatus int32

const (
	UserStatus_unknown UserStatus = 0
	UserStatus_normal  UserStatus = 1
	UserStatus_disable UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "unknown",
	1: "normal",
	2: "disable",
}

var UserStatus_value = map[string]int32{
	"unknown": 0,
	"normal":  1,
	"disable": 2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a1692e5bd11bd6b, []int{0}
}

type GetUsersRequest struct {
	BaseListRequest      `protobuf:"bytes,1,opt,name=BaseListRequest,proto3,embedded=BaseListRequest" json:"BaseListRequest"`
	App                  string     `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Storage              string     `protobuf:"bytes,3,opt,name=storage,proto3" json:"storage"`
	Status               UserStatus `protobuf:"varint,4,opt,name=status,proto3,enum=idas.endpoint.users.UserStatus" json:"status,omitempty" enum:"Unknown|Normal|Disable"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a1692e5bd11bd6b, []int{0}
}
func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

func (m *GetUsersRequest) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *GetUsersRequest) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *GetUsersRequest) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_unknown
}

type UserInfo struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Username             string     `protobuf:"bytes,2,opt,name=username,proto3" json:"username"`
	Status               UserStatus `protobuf:"varint,3,opt,name=status,proto3,enum=idas.endpoint.users.UserStatus" json:"status" enum:"Unknown|Normal|Disable"`
	Storage              string     `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage"`
	Email                string     `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	FullName             string     `protobuf:"bytes,6,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Avatar               string     `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	PhoneNumber          string     `protobuf:"bytes,8,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Role                 string     `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`
	RoleId               string     `protobuf:"bytes,10,opt,name=roleId,proto3" json:"roleId,omitempty"`
	LoginTime            string     `protobuf:"bytes,11,opt,name=loginTime,proto3" json:"loginTime,omitempty"`
	UpdateTime           string     `protobuf:"bytes,12,opt,name=updateTime,proto3" json:"updateTime"`
	CreateTime           string     `protobuf:"bytes,13,opt,name=createTime,proto3" json:"createTime"`
	IsDelete             bool       `protobuf:"varint,14,opt,name=isDelete,proto3" json:"isDelete"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a1692e5bd11bd6b, []int{1}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfo) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_unknown
}

func (m *UserInfo) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserInfo) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UserInfo) GetRoleId() string {
	if m != nil {
		return m.RoleId
	}
	return ""
}

func (m *UserInfo) GetLoginTime() string {
	if m != nil {
		return m.LoginTime
	}
	return ""
}

func (m *UserInfo) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

func (m *UserInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *UserInfo) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

type GetUserResponse struct {
	Success              bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Data                 *UserInfo `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ErrorCode            string    `protobuf:"bytes,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string    `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	TraceId              string    `protobuf:"bytes,5,opt,name=traceId,proto3" json:"traceId"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a1692e5bd11bd6b, []int{2}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetUserResponse) GetData() *UserInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUserResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *GetUserResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetUserResponse) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

type GetUsersResponse struct {
	Success              bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Data                 []*UserInfo `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	ErrorCode            string      `protobuf:"bytes,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string      `protobuf:"bytes,4,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	TraceId              string      `protobuf:"bytes,5,opt,name=traceId,proto3" json:"traceId"`
	Current              int64       `protobuf:"varint,6,opt,name=current,proto3" json:"current,omitempty"`
	PageSize             int64       `protobuf:"varint,7,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Total                int64       `protobuf:"varint,8,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a1692e5bd11bd6b, []int{3}
}
func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetUsersResponse) GetData() []*UserInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUsersResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *GetUsersResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetUsersResponse) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *GetUsersResponse) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *GetUsersResponse) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetUsersResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PatchUserRequest struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               UserStatus `protobuf:"varint,2,opt,name=status,proto3,enum=idas.endpoint.users.UserStatus" json:"status,omitempty" enum:"Unknown|Normal|Disable"`
	IsDelete             bool       `protobuf:"varint,3,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	Storage              string     `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PatchUserRequest) Reset()         { *m = PatchUserRequest{} }
func (m *PatchUserRequest) String() string { return proto.CompactTextString(m) }
func (*PatchUserRequest) ProtoMessage()    {}
func (*PatchUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a1692e5bd11bd6b, []int{4}
}
func (m *PatchUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchUserRequest.Unmarshal(m, b)
}
func (m *PatchUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchUserRequest.Marshal(b, m, deterministic)
}
func (m *PatchUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchUserRequest.Merge(m, src)
}
func (m *PatchUserRequest) XXX_Size() int {
	return xxx_messageInfo_PatchUserRequest.Size(m)
}
func (m *PatchUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchUserRequest proto.InternalMessageInfo

func (m *PatchUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PatchUserRequest) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_unknown
}

func (m *PatchUserRequest) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *PatchUserRequest) GetStorage() string {
	if m != nil {
		return m.Storage
	}
	return ""
}

type PatchUsersResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	ErrorCode            string   `protobuf:"bytes,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	TraceId              string   `protobuf:"bytes,4,opt,name=traceId,proto3" json:"traceId"`
	Total                int64    `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchUsersResponse) Reset()         { *m = PatchUsersResponse{} }
func (m *PatchUsersResponse) String() string { return proto.CompactTextString(m) }
func (*PatchUsersResponse) ProtoMessage()    {}
func (*PatchUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a1692e5bd11bd6b, []int{5}
}
func (m *PatchUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchUsersResponse.Unmarshal(m, b)
}
func (m *PatchUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchUsersResponse.Marshal(b, m, deterministic)
}
func (m *PatchUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchUsersResponse.Merge(m, src)
}
func (m *PatchUsersResponse) XXX_Size() int {
	return xxx_messageInfo_PatchUsersResponse.Size(m)
}
func (m *PatchUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PatchUsersResponse proto.InternalMessageInfo

func (m *PatchUsersResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PatchUsersResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *PatchUsersResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *PatchUsersResponse) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *PatchUsersResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterEnum("idas.endpoint.users.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterType((*GetUsersRequest)(nil), "idas.endpoint.users.GetUsersRequest")
	proto.RegisterType((*UserInfo)(nil), "idas.endpoint.users.UserInfo")
	proto.RegisterType((*GetUserResponse)(nil), "idas.endpoint.users.GetUserResponse")
	proto.RegisterType((*GetUsersResponse)(nil), "idas.endpoint.users.GetUsersResponse")
	proto.RegisterType((*PatchUserRequest)(nil), "idas.endpoint.users.PatchUserRequest")
	proto.RegisterType((*PatchUsersResponse)(nil), "idas.endpoint.users.PatchUsersResponse")
}

func init() { proto.RegisterFile("v1/users.proto", fileDescriptor_5a1692e5bd11bd6b) }

var fileDescriptor_5a1692e5bd11bd6b = []byte{
	// 727 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcf, 0x6e, 0xd3, 0x4c,
	0x10, 0xaf, 0xed, 0xfc, 0x9d, 0xb4, 0x69, 0xb4, 0x5f, 0x55, 0x59, 0x51, 0x2b, 0xe7, 0xf3, 0xa7,
	0x4f, 0x8a, 0x40, 0x4a, 0xd4, 0x70, 0x83, 0x5b, 0xa8, 0x84, 0x2a, 0x41, 0x55, 0x6d, 0xa9, 0x90,
	0x7a, 0xdb, 0xc4, 0xd3, 0xd4, 0xaa, 0xe3, 0x35, 0xde, 0x75, 0x91, 0x50, 0x5f, 0x84, 0x23, 0xaf,
	0xc1, 0x0b, 0xd0, 0x23, 0x07, 0xce, 0x7e, 0x80, 0x1c, 0x79, 0x01, 0xd0, 0xae, 0x63, 0x3b, 0xad,
	0xa0, 0x14, 0xc4, 0x81, 0x53, 0x66, 0x7e, 0x33, 0xbb, 0x9e, 0xf9, 0xfd, 0x66, 0x27, 0xd0, 0xbe,
	0xdc, 0x1b, 0x26, 0x02, 0x63, 0x31, 0x88, 0x62, 0x2e, 0x39, 0xf9, 0xc7, 0xf7, 0x98, 0x18, 0x60,
	0xe8, 0x45, 0xdc, 0x0f, 0xe5, 0x40, 0x87, 0xba, 0x5b, 0x33, 0x3e, 0xe3, 0x3a, 0x3e, 0x54, 0x56,
	0x96, 0xda, 0xdd, 0xb8, 0xdc, 0x1b, 0x4e, 0x98, 0xc0, 0xcc, 0x75, 0xbf, 0x1a, 0xb0, 0xf9, 0x0c,
	0xe5, 0x89, 0x3a, 0x41, 0xf1, 0x75, 0x82, 0x42, 0x92, 0x57, 0xb0, 0x39, 0x66, 0x02, 0x9f, 0xfb,
	0x42, 0x2e, 0x21, 0xdb, 0xe8, 0x19, 0xfd, 0xd6, 0xe8, 0xbf, 0xc1, 0xcd, 0xef, 0xe8, 0x7b, 0x6e,
	0xa5, 0x8e, 0x1b, 0xd7, 0xa9, 0xb3, 0xf6, 0x29, 0x75, 0x0c, 0x7a, 0xfb, 0x16, 0xd2, 0x01, 0x8b,
	0x45, 0x91, 0x6d, 0xf6, 0x8c, 0x7e, 0x93, 0x2a, 0x93, 0xfc, 0x0f, 0x75, 0x21, 0x79, 0xcc, 0x66,
	0x68, 0x5b, 0x0a, 0x1d, 0xb7, 0x16, 0xa9, 0x93, 0x43, 0x34, 0x37, 0xc8, 0x29, 0xd4, 0x84, 0x64,
	0x32, 0x11, 0x76, 0xa5, 0x67, 0xf4, 0xdb, 0x23, 0x67, 0xf0, 0x9d, 0x86, 0x07, 0xaa, 0x89, 0x63,
	0x9d, 0x36, 0xfe, 0xf7, 0x4b, 0xea, 0xec, 0x62, 0x98, 0xcc, 0x1f, 0xbb, 0x27, 0xe1, 0x45, 0xc8,
	0xdf, 0x84, 0x57, 0x87, 0x3c, 0x9e, 0xb3, 0xe0, 0x6a, 0xdf, 0x17, 0x6c, 0x12, 0xa0, 0x4b, 0x97,
	0x37, 0xba, 0xef, 0x2a, 0xd0, 0x50, 0x27, 0x0f, 0xc2, 0x33, 0x4e, 0xb6, 0xc1, 0xf4, 0x3d, 0xdd,
	0x6d, 0x73, 0x5c, 0x5b, 0xa4, 0x8e, 0xe9, 0x7b, 0xd4, 0xf4, 0x3d, 0xd2, 0x87, 0x86, 0xfa, 0x46,
	0xc8, 0xe6, 0x98, 0x95, 0x3f, 0x5e, 0x5f, 0xa4, 0x4e, 0x81, 0xd1, 0xc2, 0x22, 0x5e, 0x51, 0xaa,
	0x75, 0xbf, 0x52, 0x1f, 0x2e, 0x52, 0x67, 0x79, 0xe4, 0xde, 0x45, 0xaf, 0xf2, 0x56, 0xb9, 0x83,
	0xb7, 0x2d, 0xa8, 0xe2, 0x9c, 0xf9, 0x81, 0x5d, 0xd5, 0x94, 0x67, 0x0e, 0xe9, 0x42, 0xe3, 0x2c,
	0x09, 0x82, 0x43, 0xd5, 0x4c, 0x4d, 0x07, 0x0a, 0x9f, 0x6c, 0x43, 0x8d, 0x5d, 0x32, 0xc9, 0x62,
	0xbb, 0xae, 0x23, 0x4b, 0x8f, 0xf4, 0xa0, 0x15, 0x9d, 0xf3, 0x10, 0x0f, 0x93, 0xf9, 0x04, 0x63,
	0xbb, 0xa1, 0x83, 0xab, 0x10, 0x21, 0x50, 0x89, 0x79, 0x80, 0x76, 0x53, 0x87, 0xb4, 0xad, 0x6e,
	0x53, 0xbf, 0x07, 0x9e, 0x0d, 0xd9, 0x6d, 0x99, 0x47, 0x76, 0xa0, 0x19, 0xf0, 0x99, 0x1f, 0xbe,
	0xf4, 0xe7, 0x68, 0xb7, 0x74, 0xa8, 0x04, 0xc8, 0x00, 0x20, 0x89, 0x3c, 0x26, 0x51, 0x87, 0xd7,
	0x75, 0x7f, 0xed, 0x45, 0xea, 0xac, 0xa0, 0x74, 0xc5, 0x56, 0xf9, 0xd3, 0x18, 0xf3, 0xfc, 0x8d,
	0x32, 0xbf, 0x44, 0xe9, 0x8a, 0xad, 0xc4, 0xf4, 0xc5, 0x3e, 0x06, 0x28, 0xd1, 0x6e, 0xf7, 0x8c,
	0x7e, 0x23, 0x13, 0x33, 0xc7, 0x68, 0x61, 0xb9, 0x9f, 0xcb, 0xd7, 0x41, 0x51, 0x44, 0x3c, 0x14,
	0xa8, 0xa9, 0x4f, 0xa6, 0x53, 0x14, 0x42, 0xcf, 0x49, 0x63, 0x49, 0x7d, 0x06, 0xd1, 0xdc, 0x20,
	0x7b, 0x50, 0xf1, 0x98, 0x64, 0x7a, 0x5a, 0x5a, 0xa3, 0xdd, 0x1f, 0x4e, 0x81, 0x1a, 0x3b, 0xaa,
	0x53, 0x15, 0x2b, 0x18, 0xc7, 0x3c, 0x7e, 0xca, 0xbd, 0xe5, 0x73, 0xa0, 0x25, 0x40, 0x5c, 0x58,
	0xd7, 0xce, 0x0b, 0x14, 0xa2, 0xd0, 0x9d, 0xde, 0xc0, 0x54, 0x6d, 0x32, 0x66, 0x53, 0x45, 0x78,
	0xb5, 0x1c, 0x8b, 0x25, 0x44, 0x73, 0xc3, 0x7d, 0x6f, 0x42, 0xa7, 0x7c, 0xf4, 0xbf, 0xdb, 0x97,
	0xf5, 0xb7, 0xf5, 0x45, 0x6c, 0xa8, 0x4f, 0x93, 0x38, 0xc6, 0x50, 0xea, 0xb9, 0xb6, 0x68, 0xee,
	0xaa, 0x91, 0x8f, 0xd8, 0x0c, 0x8f, 0xfd, 0xb7, 0xa8, 0x07, 0xdb, 0xa2, 0x85, 0xaf, 0x1e, 0x89,
	0xe4, 0x92, 0x05, 0x7a, 0xa8, 0x2d, 0x9a, 0x39, 0xee, 0x47, 0x03, 0x3a, 0x47, 0x4c, 0x4e, 0xcf,
	0x33, 0xf1, 0xb3, 0x05, 0xd6, 0x2e, 0xd7, 0x83, 0x5e, 0x0b, 0xe5, 0x5e, 0x32, 0xff, 0xf4, 0x5e,
	0x22, 0xbd, 0x95, 0x29, 0xb5, 0xb4, 0x20, 0x95, 0x6b, 0xb5, 0x55, 0x0b, 0xf4, 0x9e, 0x4b, 0xc0,
	0xfd, 0x60, 0x00, 0x29, 0x3a, 0xf9, 0x65, 0xbd, 0x6f, 0x88, 0x67, 0xfe, 0x4c, 0x3c, 0xeb, 0x6e,
	0xf1, 0x2a, 0x77, 0x88, 0x57, 0xc8, 0x50, 0x5d, 0x91, 0xe1, 0xc1, 0x08, 0xa0, 0xa4, 0x8f, 0xb4,
	0xa0, 0x9e, 0x64, 0xb4, 0x75, 0xd6, 0x08, 0x40, 0x2d, 0xd4, 0xdc, 0x75, 0x0c, 0x15, 0xf0, 0x32,
	0x02, 0x3b, 0xe6, 0x78, 0xe7, 0xb4, 0xab, 0x64, 0x18, 0x46, 0x17, 0xb3, 0x61, 0x2e, 0xc5, 0x93,
	0xdc, 0x38, 0x5a, 0x9b, 0xd4, 0xf4, 0x5f, 0xdf, 0xa3, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3f,
	0x8d, 0x72, 0xdf, 0x46, 0x07, 0x00, 0x00,
}
