// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/capacity.proto

package capacity

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Capacity struct {
	Capacity             int64    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Capacity) Reset()         { *m = Capacity{} }
func (m *Capacity) String() string { return proto.CompactTextString(m) }
func (*Capacity) ProtoMessage()    {}
func (*Capacity) Descriptor() ([]byte, []int) {
	return fileDescriptor_af190551a834447c, []int{0}
}
func (m *Capacity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capacity.Unmarshal(m, b)
}
func (m *Capacity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capacity.Marshal(b, m, deterministic)
}
func (m *Capacity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capacity.Merge(m, src)
}
func (m *Capacity) XXX_Size() int {
	return xxx_messageInfo_Capacity.Size(m)
}
func (m *Capacity) XXX_DiscardUnknown() {
	xxx_messageInfo_Capacity.DiscardUnknown(m)
}

var xxx_messageInfo_Capacity proto.InternalMessageInfo

func (m *Capacity) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func init() {
	proto.RegisterType((*Capacity)(nil), "idas.pkg.utils.Capacity")
}

func init() { proto.RegisterFile("types/capacity.proto", fileDescriptor_af190551a834447c) }

var fileDescriptor_af190551a834447c = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x4f, 0x4e, 0x2c, 0x48, 0x4c, 0xce, 0x2c, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0xcb, 0x4c, 0x49, 0x2c, 0xd6, 0x2b, 0xc8, 0x4e, 0xd7, 0x2b, 0x2d, 0xc9, 0xcc, 0x29,
	0x56, 0x52, 0xe3, 0xe2, 0x70, 0x86, 0xaa, 0x10, 0x92, 0xe2, 0xe2, 0x80, 0xa9, 0x96, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0e, 0x82, 0xf3, 0x9d, 0x2c, 0xa3, 0xcc, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93,
	0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x7d, 0x33, 0x93, 0x8b, 0xf2, 0xfd, 0x0b, 0x8a, 0x75, 0x93, 0xf3,
	0xf4, 0x41, 0x06, 0xea, 0x17, 0x64, 0xa7, 0xeb, 0x83, 0x0d, 0x84, 0xdb, 0x67, 0x0d, 0x63, 0x24,
	0xb1, 0x81, 0x6d, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xdf, 0xb6, 0x15, 0x91, 0x00,
	0x00, 0x00,
}
