// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/ldap.proto

package ldap

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LdapOptions struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	ManagerDn            string   `protobuf:"bytes,2,opt,name=manager_dn,json=managerDn,proto3" json:"manager_dn,omitempty"`
	ManagerPassword      string   `protobuf:"bytes,3,opt,name=manager_password,json=managerPassword,proto3" json:"manager_password,omitempty"`
	UserSearchBase       string   `protobuf:"bytes,4,opt,name=user_search_base,json=userSearchBase,proto3" json:"user_search_base,omitempty"`
	UserSearchFilter     string   `protobuf:"bytes,5,opt,name=user_search_filter,json=userSearchFilter,proto3" json:"user_search_filter,omitempty"`
	GroupSearchBase      string   `protobuf:"bytes,6,opt,name=group_search_base,json=groupSearchBase,proto3" json:"group_search_base,omitempty"`
	GroupSearchFilter    string   `protobuf:"bytes,7,opt,name=group_search_filter,json=groupSearchFilter,proto3" json:"group_search_filter,omitempty"`
	AttrUsername         string   `protobuf:"bytes,8,opt,name=attr_username,json=attrUsername,proto3" json:"attr_username,omitempty"`
	AttrEmail            string   `protobuf:"bytes,9,opt,name=attr_email,json=attrEmail,proto3" json:"attr_email,omitempty"`
	AttrUserDisplayName  string   `protobuf:"bytes,10,opt,name=attr_user_display_name,json=attrUserDisplayName,proto3" json:"attr_user_display_name,omitempty"`
	AttrUserPhoneNo      string   `protobuf:"bytes,11,opt,name=attr_user_phone_no,json=attrUserPhoneNo,proto3" json:"attr_user_phone_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LdapOptions) Reset()         { *m = LdapOptions{} }
func (m *LdapOptions) String() string { return proto.CompactTextString(m) }
func (*LdapOptions) ProtoMessage()    {}
func (*LdapOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_cce19adcf4aae021, []int{0}
}
func (m *LdapOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LdapOptions.Unmarshal(m, b)
}
func (m *LdapOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LdapOptions.Marshal(b, m, deterministic)
}
func (m *LdapOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LdapOptions.Merge(m, src)
}
func (m *LdapOptions) XXX_Size() int {
	return xxx_messageInfo_LdapOptions.Size(m)
}
func (m *LdapOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_LdapOptions.DiscardUnknown(m)
}

var xxx_messageInfo_LdapOptions proto.InternalMessageInfo

func (m *LdapOptions) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *LdapOptions) GetManagerDn() string {
	if m != nil {
		return m.ManagerDn
	}
	return ""
}

func (m *LdapOptions) GetManagerPassword() string {
	if m != nil {
		return m.ManagerPassword
	}
	return ""
}

func (m *LdapOptions) GetUserSearchBase() string {
	if m != nil {
		return m.UserSearchBase
	}
	return ""
}

func (m *LdapOptions) GetUserSearchFilter() string {
	if m != nil {
		return m.UserSearchFilter
	}
	return ""
}

func (m *LdapOptions) GetGroupSearchBase() string {
	if m != nil {
		return m.GroupSearchBase
	}
	return ""
}

func (m *LdapOptions) GetGroupSearchFilter() string {
	if m != nil {
		return m.GroupSearchFilter
	}
	return ""
}

func (m *LdapOptions) GetAttrUsername() string {
	if m != nil {
		return m.AttrUsername
	}
	return ""
}

func (m *LdapOptions) GetAttrEmail() string {
	if m != nil {
		return m.AttrEmail
	}
	return ""
}

func (m *LdapOptions) GetAttrUserDisplayName() string {
	if m != nil {
		return m.AttrUserDisplayName
	}
	return ""
}

func (m *LdapOptions) GetAttrUserPhoneNo() string {
	if m != nil {
		return m.AttrUserPhoneNo
	}
	return ""
}

func init() {
	proto.RegisterType((*LdapOptions)(nil), "idas.client.ldap.LdapOptions")
}

func init() { proto.RegisterFile("types/ldap.proto", fileDescriptor_cce19adcf4aae021) }

var fileDescriptor_cce19adcf4aae021 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4d, 0x4f, 0x02, 0x31,
	0x10, 0x86, 0x83, 0x20, 0xca, 0xe0, 0xc7, 0x52, 0x12, 0x53, 0x63, 0x4c, 0x8c, 0x5e, 0xf0, 0x23,
	0xcb, 0x81, 0xa3, 0x37, 0x82, 0x9e, 0x0c, 0x12, 0x8d, 0x17, 0x2f, 0xcd, 0xc0, 0x56, 0xd8, 0xb8,
	0xb4, 0x4d, 0x5b, 0x62, 0xf8, 0x81, 0xfe, 0x2f, 0xd3, 0xd9, 0x22, 0xcb, 0x65, 0xb3, 0x79, 0xe6,
	0xe9, 0xbb, 0xdb, 0x79, 0x21, 0xf1, 0x6b, 0x23, 0x5d, 0xbf, 0xc8, 0xd0, 0xa4, 0xc6, 0x6a, 0xaf,
	0x59, 0x92, 0x67, 0xe8, 0xd2, 0x59, 0x91, 0x4b, 0xe5, 0xd3, 0xc0, 0xaf, 0x7f, 0xeb, 0xd0, 0x7e,
	0xc9, 0xd0, 0xbc, 0x1a, 0x9f, 0x6b, 0xe5, 0x18, 0x83, 0xc6, 0x42, 0x3b, 0xcf, 0x6b, 0x57, 0xb5,
	0x5e, 0xeb, 0x8d, 0xde, 0xd9, 0x25, 0xc0, 0x12, 0x15, 0xce, 0xa5, 0x15, 0x99, 0xe2, 0x7b, 0x34,
	0x69, 0x45, 0x32, 0x52, 0xec, 0x16, 0x92, 0xcd, 0xd8, 0xa0, 0x73, 0x3f, 0xda, 0x66, 0xbc, 0x4e,
	0xd2, 0x69, 0xe4, 0x93, 0x88, 0x59, 0x0f, 0x92, 0x95, 0x93, 0x56, 0x38, 0x89, 0x76, 0xb6, 0x10,
	0x53, 0x74, 0x92, 0x37, 0x48, 0x3d, 0x09, 0xfc, 0x9d, 0xf0, 0x10, 0x9d, 0x64, 0x0f, 0xc0, 0xaa,
	0xe6, 0x57, 0x5e, 0x78, 0x69, 0xf9, 0x3e, 0xb9, 0xc9, 0xd6, 0x7d, 0x26, 0xce, 0xee, 0xa0, 0x33,
	0xb7, 0x7a, 0x65, 0x76, 0x82, 0x9b, 0xe5, 0x3f, 0xd0, 0xa0, 0x92, 0x9c, 0x42, 0x77, 0xc7, 0x8d,
	0xd1, 0x07, 0x64, 0x77, 0x2a, 0x76, 0xcc, 0xbe, 0x81, 0x63, 0xf4, 0xde, 0x8a, 0xf0, 0x51, 0x85,
	0x4b, 0xc9, 0x0f, 0xc9, 0x3c, 0x0a, 0xf0, 0x23, 0xb2, 0xb0, 0x22, 0x92, 0xe4, 0x12, 0xf3, 0x82,
	0xb7, 0xca, 0x15, 0x05, 0xf2, 0x14, 0x00, 0x1b, 0xc0, 0xd9, 0x7f, 0x86, 0xc8, 0x72, 0x67, 0x0a,
	0x5c, 0x0b, 0x0a, 0x03, 0x52, 0xbb, 0x9b, 0xb0, 0x51, 0x39, 0x1b, 0x87, 0xcc, 0x7b, 0x60, 0xdb,
	0x43, 0x66, 0xa1, 0x95, 0x14, 0x4a, 0xf3, 0x76, 0x79, 0xab, 0xcd, 0x81, 0x49, 0xe0, 0x63, 0x3d,
	0xbc, 0xf8, 0x3c, 0x0f, 0xdd, 0xf6, 0xcd, 0xf7, 0xbc, 0x5f, 0xf6, 0x4b, 0xbd, 0x3f, 0x86, 0xc7,
	0xb4, 0x49, 0xed, 0x0f, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x67, 0x3c, 0x51, 0x11, 0x02,
	0x00, 0x00,
}
