// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: models/models.proto

package models

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	gorm_io_gorm "gorm.io/gorm"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// @sync-to-public:public/src/services/idas/enums.ts:AuthMethod
type AuthMeta_Method int32

const (
	AuthMeta_basic           AuthMeta_Method = 0
	AuthMeta_signature       AuthMeta_Method = 1
	AuthMeta_token           AuthMeta_Method = 2
	AuthMeta_token_signature AuthMeta_Method = 3
)

var AuthMeta_Method_name = map[int32]string{
	0: "basic",
	1: "signature",
	2: "token",
	3: "token_signature",
}

var AuthMeta_Method_value = map[string]int32{
	"basic":           0,
	"signature":       1,
	"token":           2,
	"token_signature": 3,
}

func (x AuthMeta_Method) String() string {
	return proto.EnumName(AuthMeta_Method_name, int32(x))
}

func (AuthMeta_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{0, 0}
}

// @sync-to-public:public/src/services/idas/enums.ts:AppStatus
type AppMeta_Status int32

const (
	AppMeta_unknown AppMeta_Status = 0
	AppMeta_normal  AppMeta_Status = 1
	AppMeta_disable AppMeta_Status = 2
)

var AppMeta_Status_name = map[int32]string{
	0: "unknown",
	1: "normal",
	2: "disable",
}

var AppMeta_Status_value = map[string]int32{
	"unknown": 0,
	"normal":  1,
	"disable": 2,
}

func (x AppMeta_Status) String() string {
	return proto.EnumName(AppMeta_Status_name, int32(x))
}

func (AppMeta_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{1, 0}
}

// @sync-to-public:public/src/services/idas/enums.ts:GrantType
type AppMeta_GrantType int32

const (
	AppMeta_none               AppMeta_GrantType = 0
	AppMeta_authorization_code AppMeta_GrantType = 1
	AppMeta_implicit           AppMeta_GrantType = 2
	AppMeta_password           AppMeta_GrantType = 4
	AppMeta_client_credentials AppMeta_GrantType = 8
	AppMeta_proxy              AppMeta_GrantType = 16
	AppMeta_oidc               AppMeta_GrantType = 32
	AppMeta_radius             AppMeta_GrantType = 64
)

var AppMeta_GrantType_name = map[int32]string{
	0:  "none",
	1:  "authorization_code",
	2:  "implicit",
	4:  "password",
	8:  "client_credentials",
	16: "proxy",
	32: "oidc",
	64: "radius",
}

var AppMeta_GrantType_value = map[string]int32{
	"none":               0,
	"authorization_code": 1,
	"implicit":           2,
	"password":           4,
	"client_credentials": 8,
	"proxy":              16,
	"oidc":               32,
	"radius":             64,
}

func (x AppMeta_GrantType) String() string {
	return proto.EnumName(AppMeta_GrantType_name, int32(x))
}

func (AppMeta_GrantType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{1, 1}
}

// @sync-to-public:public/src/services/idas/enums.ts:GrantMode
type AppMeta_GrantMode int32

const (
	AppMeta_manual AppMeta_GrantMode = 0
	AppMeta_full   AppMeta_GrantMode = 1
)

var AppMeta_GrantMode_name = map[int32]string{
	0: "manual",
	1: "full",
}

var AppMeta_GrantMode_value = map[string]int32{
	"manual": 0,
	"full":   1,
}

func (x AppMeta_GrantMode) String() string {
	return proto.EnumName(AppMeta_GrantMode_name, int32(x))
}

func (AppMeta_GrantMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{1, 2}
}

// @sync-to-public:public/src/services/idas/enums.ts:JWTSignatureMethod
type AppMeta_JWTSignatureMethod int32

const (
	AppMeta_default AppMeta_JWTSignatureMethod = 0
	AppMeta_HS256   AppMeta_JWTSignatureMethod = 1
	AppMeta_HS384   AppMeta_JWTSignatureMethod = 2
	AppMeta_HS512   AppMeta_JWTSignatureMethod = 3
	AppMeta_RS256   AppMeta_JWTSignatureMethod = 4
	AppMeta_RS384   AppMeta_JWTSignatureMethod = 5
	AppMeta_RS512   AppMeta_JWTSignatureMethod = 6
	AppMeta_ES256   AppMeta_JWTSignatureMethod = 7
	AppMeta_ES384   AppMeta_JWTSignatureMethod = 8
	AppMeta_ES512   AppMeta_JWTSignatureMethod = 9
)

var AppMeta_JWTSignatureMethod_name = map[int32]string{
	0: "default",
	1: "HS256",
	2: "HS384",
	3: "HS512",
	4: "RS256",
	5: "RS384",
	6: "RS512",
	7: "ES256",
	8: "ES384",
	9: "ES512",
}

var AppMeta_JWTSignatureMethod_value = map[string]int32{
	"default": 0,
	"HS256":   1,
	"HS384":   2,
	"HS512":   3,
	"RS256":   4,
	"RS384":   5,
	"RS512":   6,
	"ES256":   7,
	"ES384":   8,
	"ES512":   9,
}

func (x AppMeta_JWTSignatureMethod) String() string {
	return proto.EnumName(AppMeta_JWTSignatureMethod_name, int32(x))
}

func (AppMeta_JWTSignatureMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{1, 3}
}

// @sync-to-public:public/src/services/idas/enums.ts:RoleType
type RoleMeta_Type int32

const (
	RoleMeta_user   RoleMeta_Type = 0
	RoleMeta_system RoleMeta_Type = 1
)

var RoleMeta_Type_name = map[int32]string{
	0: "user",
	1: "system",
}

var RoleMeta_Type_value = map[string]int32{
	"user":   0,
	"system": 1,
}

func (x RoleMeta_Type) String() string {
	return proto.EnumName(RoleMeta_Type_name, int32(x))
}

func (RoleMeta_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{2, 0}
}

// @sync-to-public:public/src/services/idas/enums.ts:UserStatus
type UserMeta_UserStatus int32

const (
	UserMeta_normal           UserMeta_UserStatus = 0
	UserMeta_disabled         UserMeta_UserStatus = 1
	UserMeta_user_inactive    UserMeta_UserStatus = 2
	UserMeta_password_expired UserMeta_UserStatus = 4
)

var UserMeta_UserStatus_name = map[int32]string{
	0: "normal",
	1: "disabled",
	2: "user_inactive",
	4: "password_expired",
}

var UserMeta_UserStatus_value = map[string]int32{
	"normal":           0,
	"disabled":         1,
	"user_inactive":    2,
	"password_expired": 4,
}

func (x UserMeta_UserStatus) String() string {
	return proto.EnumName(UserMeta_UserStatus_name, int32(x))
}

func (UserMeta_UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{3, 0}
}

type AuthMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthMeta) Reset()         { *m = AuthMeta{} }
func (m *AuthMeta) String() string { return proto.CompactTextString(m) }
func (*AuthMeta) ProtoMessage()    {}
func (*AuthMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{0}
}
func (m *AuthMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMeta.Unmarshal(m, b)
}
func (m *AuthMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMeta.Marshal(b, m, deterministic)
}
func (m *AuthMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMeta.Merge(m, src)
}
func (m *AuthMeta) XXX_Size() int {
	return xxx_messageInfo_AuthMeta.Size(m)
}
func (m *AuthMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMeta proto.InternalMessageInfo

type AppMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppMeta) Reset()         { *m = AppMeta{} }
func (m *AppMeta) String() string { return proto.CompactTextString(m) }
func (*AppMeta) ProtoMessage()    {}
func (*AppMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{1}
}
func (m *AppMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppMeta.Unmarshal(m, b)
}
func (m *AppMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppMeta.Marshal(b, m, deterministic)
}
func (m *AppMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppMeta.Merge(m, src)
}
func (m *AppMeta) XXX_Size() int {
	return xxx_messageInfo_AppMeta.Size(m)
}
func (m *AppMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AppMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AppMeta proto.InternalMessageInfo

type RoleMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleMeta) Reset()         { *m = RoleMeta{} }
func (m *RoleMeta) String() string { return proto.CompactTextString(m) }
func (*RoleMeta) ProtoMessage()    {}
func (*RoleMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{2}
}
func (m *RoleMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleMeta.Unmarshal(m, b)
}
func (m *RoleMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleMeta.Marshal(b, m, deterministic)
}
func (m *RoleMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleMeta.Merge(m, src)
}
func (m *RoleMeta) XXX_Size() int {
	return xxx_messageInfo_RoleMeta.Size(m)
}
func (m *RoleMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RoleMeta proto.InternalMessageInfo

type UserMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMeta) Reset()         { *m = UserMeta{} }
func (m *UserMeta) String() string { return proto.CompactTextString(m) }
func (*UserMeta) ProtoMessage()    {}
func (*UserMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{3}
}
func (m *UserMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMeta.Unmarshal(m, b)
}
func (m *UserMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMeta.Marshal(b, m, deterministic)
}
func (m *UserMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMeta.Merge(m, src)
}
func (m *UserMeta) XXX_Size() int {
	return xxx_messageInfo_UserMeta.Size(m)
}
func (m *UserMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMeta.DiscardUnknown(m)
}

var xxx_messageInfo_UserMeta proto.InternalMessageInfo

type Model struct {
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id" valid:"required" gorm:"primary_key;type:char(36)"`
	CreateTime time.Time              `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3,customtype=time.Time" json:"createTime,omitempty" gorm:"type:datetime;not null;omitempty"`
	UpdateTime time.Time              `protobuf:"bytes,3,opt,name=update_time,json=updateTime,proto3,customtype=time.Time" json:"updateTime,omitempty" gorm:"type:datetime;not null;omitempty"`
	IsDelete   bool                   `protobuf:"varint,4,opt,name=is_delete,json=isDelete,proto3" json:"isDelete,omitempty" gorm:"-"`
	DeleteTime gorm_io_gorm.DeletedAt `protobuf:"bytes,5,opt,name=delete_time,json=deleteTime,proto3,customtype=gorm.io/gorm.DeletedAt" json:"-" gorm:"type:datetime;omitempty"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb289c42926c4029, []int{4}
}
func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Model) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func init() {
	proto.RegisterEnum("idas.service.models.AuthMeta_Method", AuthMeta_Method_name, AuthMeta_Method_value)
	proto.RegisterEnum("idas.service.models.AppMeta_Status", AppMeta_Status_name, AppMeta_Status_value)
	proto.RegisterEnum("idas.service.models.AppMeta_GrantType", AppMeta_GrantType_name, AppMeta_GrantType_value)
	proto.RegisterEnum("idas.service.models.AppMeta_GrantMode", AppMeta_GrantMode_name, AppMeta_GrantMode_value)
	proto.RegisterEnum("idas.service.models.AppMeta_JWTSignatureMethod", AppMeta_JWTSignatureMethod_name, AppMeta_JWTSignatureMethod_value)
	proto.RegisterEnum("idas.service.models.RoleMeta_Type", RoleMeta_Type_name, RoleMeta_Type_value)
	proto.RegisterEnum("idas.service.models.UserMeta_UserStatus", UserMeta_UserStatus_name, UserMeta_UserStatus_value)
	proto.RegisterType((*AuthMeta)(nil), "idas.service.models.AuthMeta")
	proto.RegisterType((*AppMeta)(nil), "idas.service.models.AppMeta")
	proto.RegisterType((*RoleMeta)(nil), "idas.service.models.RoleMeta")
	proto.RegisterType((*UserMeta)(nil), "idas.service.models.UserMeta")
	proto.RegisterType((*Model)(nil), "idas.service.models.Model")
}

func init() { proto.RegisterFile("models/models.proto", fileDescriptor_bb289c42926c4029) }

var fileDescriptor_bb289c42926c4029 = []byte{
	// 755 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x31, 0x6f, 0x24, 0x35,
	0x14, 0x9e, 0x99, 0x6c, 0x36, 0xb3, 0xce, 0x9d, 0x30, 0x4e, 0x74, 0x8a, 0x10, 0x62, 0x16, 0x37,
	0x04, 0x89, 0xec, 0xea, 0x2e, 0xe4, 0x40, 0xd9, 0x02, 0x12, 0x71, 0xe2, 0x04, 0x0a, 0x87, 0x36,
	0x41, 0x48, 0x50, 0xac, 0x9c, 0xf1, 0xcb, 0xae, 0x15, 0x8f, 0x3d, 0xd8, 0x9e, 0xdc, 0x2d, 0x25,
	0xe2, 0x07, 0x50, 0xd2, 0x72, 0xbf, 0x86, 0x92, 0x9a, 0x62, 0x6a, 0x94, 0x32, 0x1d, 0x1d, 0x7a,
	0xe3, 0xcd, 0x05, 0x24, 0x44, 0x43, 0x35, 0xdf, 0xcc, 0xfb, 0xde, 0xfb, 0x3e, 0x7f, 0xd6, 0x3c,
	0xb2, 0x55, 0x59, 0x09, 0xda, 0x8f, 0xe3, 0x63, 0x54, 0x3b, 0x1b, 0x2c, 0xdb, 0x52, 0x52, 0xf8,
	0x91, 0x07, 0x77, 0xa5, 0x4a, 0x18, 0xc5, 0xd2, 0x1b, 0xdb, 0x73, 0x3b, 0xb7, 0x5d, 0x7d, 0x8c,
	0x28, 0x52, 0xf9, 0x17, 0x24, 0x3f, 0x6a, 0xc2, 0xe2, 0x04, 0x82, 0xe0, 0xc7, 0xa4, 0x7f, 0x02,
	0x61, 0x61, 0x25, 0x1b, 0x90, 0xf5, 0x73, 0xe1, 0x55, 0x49, 0x13, 0x76, 0x9f, 0x0c, 0xbc, 0x9a,
	0x1b, 0x11, 0x1a, 0x07, 0x34, 0xc5, 0x4a, 0xb0, 0x97, 0x60, 0x68, 0xc6, 0xb6, 0xc8, 0x6b, 0x1d,
	0x9c, 0xdd, 0xd5, 0xd7, 0xf8, 0x1f, 0x19, 0xd9, 0x38, 0xaa, 0xeb, 0x6e, 0xde, 0x88, 0xf4, 0x4f,
	0x83, 0x08, 0x8d, 0x67, 0x9b, 0x64, 0xa3, 0x31, 0x97, 0xc6, 0x3e, 0x37, 0x34, 0x61, 0x84, 0xf4,
	0x8d, 0x75, 0x95, 0xd0, 0x34, 0xc5, 0x82, 0x54, 0x5e, 0x9c, 0x6b, 0xa0, 0x19, 0xff, 0x21, 0x25,
	0x83, 0x4f, 0x9d, 0x30, 0xe1, 0x6c, 0x59, 0x03, 0xcb, 0x49, 0xcf, 0x58, 0x03, 0x34, 0x61, 0x0f,
	0x08, 0x13, 0x4d, 0x58, 0x58, 0xa7, 0xbe, 0x17, 0x41, 0x59, 0x33, 0x2b, 0xad, 0x44, 0x2f, 0xf7,
	0x48, 0xae, 0xaa, 0x5a, 0xab, 0x52, 0x05, 0x9a, 0xe1, 0x5b, 0x2d, 0xbc, 0x7f, 0x6e, 0x9d, 0xa4,
	0x3d, 0xec, 0x29, 0xb5, 0x02, 0x13, 0x66, 0xa5, 0x03, 0x09, 0x26, 0x28, 0xa1, 0x3d, 0xcd, 0xd1,
	0x7f, 0xed, 0xec, 0x8b, 0x25, 0xa5, 0x28, 0x60, 0x95, 0x2c, 0xe9, 0x10, 0x1d, 0x39, 0x21, 0x55,
	0xe3, 0xe9, 0xc7, 0xfc, 0xed, 0x95, 0x87, 0x13, 0x2b, 0x01, 0x0b, 0x95, 0x30, 0x8d, 0xd0, 0x34,
	0x41, 0xfa, 0x45, 0xa3, 0x35, 0x4d, 0xf9, 0x8f, 0x29, 0x61, 0x9f, 0x7d, 0x7d, 0x76, 0x7a, 0x7b,
	0xec, 0x55, 0x68, 0x78, 0x16, 0xb8, 0x10, 0x8d, 0x0e, 0x34, 0x41, 0x9d, 0xa7, 0xa7, 0x8f, 0x0e,
	0x1e, 0xc7, 0xc8, 0x9e, 0x9e, 0xee, 0x7f, 0xf8, 0x3e, 0xcd, 0x22, 0x3c, 0x78, 0xf8, 0x88, 0xae,
	0x21, 0x9c, 0x76, 0x84, 0x5e, 0x84, 0x48, 0x58, 0x8f, 0x10, 0x09, 0x7d, 0x84, 0x4f, 0x3a, 0xc2,
	0x46, 0x84, 0x48, 0xc8, 0x23, 0x44, 0xc2, 0x80, 0xef, 0x92, 0x7c, 0x6a, 0x35, 0x74, 0x51, 0xbf,
	0x49, 0x7a, 0xb7, 0xa1, 0x35, 0x1e, 0x5c, 0x4c, 0xd9, 0x2f, 0x7d, 0x80, 0x8a, 0xa6, 0xfc, 0x5b,
	0x92, 0x7f, 0xe5, 0xc1, 0x75, 0xcc, 0x67, 0x84, 0x20, 0x5e, 0x5d, 0xcc, 0xdd, 0x5d, 0x24, 0x18,
	0xe0, 0xea, 0x2e, 0x24, 0x4d, 0xd9, 0xeb, 0xe4, 0x3e, 0x4e, 0x9a, 0x29, 0x23, 0xca, 0xa0, 0xae,
	0x80, 0x66, 0x6c, 0x9b, 0xd0, 0xdb, 0x84, 0x67, 0xf0, 0xa2, 0x56, 0x0e, 0x24, 0xed, 0xf1, 0x3f,
	0xd7, 0xc8, 0x3a, 0x86, 0xa5, 0xd9, 0xe7, 0x24, 0x53, 0x72, 0x27, 0x1d, 0xa6, 0xbb, 0x83, 0xe3,
	0xc9, 0x75, 0x5b, 0x64, 0x4a, 0xde, 0xb4, 0xc5, 0xc3, 0x2b, 0xa1, 0x95, 0x3c, 0xe4, 0x0e, 0xbe,
	0x6b, 0xb0, 0x85, 0x0f, 0xe7, 0xd6, 0x55, 0x87, 0xbc, 0x76, 0xaa, 0x12, 0x6e, 0x39, 0xbb, 0x84,
	0xe5, 0x24, 0x2c, 0x6b, 0x38, 0x2c, 0x17, 0xc2, 0xed, 0xee, 0x3f, 0x7e, 0x97, 0x4f, 0x33, 0x25,
	0x59, 0x43, 0x36, 0x4b, 0x07, 0x22, 0xc0, 0x2c, 0xa8, 0x0a, 0x76, 0xb2, 0x6e, 0xea, 0xd9, 0xaf,
	0x6d, 0x91, 0xfc, 0xde, 0x16, 0x03, 0xfc, 0x36, 0x3a, 0x53, 0x15, 0x5c, 0xb7, 0xc5, 0x76, 0xe4,
	0xe1, 0xdb, 0x7b, 0xb6, 0x52, 0x01, 0xaa, 0x3a, 0x2c, 0x6f, 0xda, 0xe2, 0x9d, 0xa8, 0xd3, 0xcd,
	0x96, 0x22, 0x00, 0xf6, 0x4c, 0x8c, 0x0d, 0x43, 0xd3, 0x68, 0x3d, 0x79, 0xc5, 0xe4, 0x53, 0x72,
	0x37, 0x00, 0x65, 0x9b, 0x5a, 0xbe, 0x92, 0x5d, 0xfb, 0x0f, 0xd9, 0xc8, 0xfb, 0x1f, 0xb2, 0x77,
	0x03, 0xd8, 0x47, 0x64, 0xa0, 0xfc, 0x4c, 0x82, 0x86, 0x00, 0x3b, 0xbd, 0x61, 0xba, 0x9b, 0x1f,
	0xf3, 0xeb, 0xb6, 0x60, 0xca, 0x7f, 0xd2, 0x7d, 0xfb, 0x87, 0x42, 0x1e, 0x15, 0xf6, 0xf8, 0x34,
	0xbf, 0xad, 0xb3, 0x0b, 0xb2, 0x19, 0xbb, 0xa3, 0xef, 0xf5, 0xce, 0xf7, 0x93, 0x95, 0xef, 0x07,
	0xd8, 0x30, 0x52, 0xf8, 0xe3, 0xbb, 0x6a, 0x14, 0x3b, 0xe4, 0x51, 0xb8, 0x6e, 0x8b, 0x74, 0xef,
	0xa6, 0x2d, 0xde, 0xfa, 0x37, 0xc7, 0x7f, 0x37, 0x1a, 0x27, 0xa3, 0xd1, 0xc3, 0x7b, 0xbf, 0xfd,
	0x52, 0x24, 0x3f, 0xbd, 0x2c, 0x92, 0x9f, 0x5f, 0x16, 0xc9, 0xf1, 0x07, 0xdf, 0x1c, 0xcc, 0x55,
	0x58, 0x34, 0xe7, 0xa3, 0xd2, 0x56, 0xe3, 0x13, 0x55, 0x3a, 0xfb, 0xac, 0xf6, 0x7b, 0xa5, 0x19,
	0xe3, 0x06, 0x1a, 0xd7, 0x97, 0xf3, 0xf1, 0x6a, 0x0b, 0xad, 0x16, 0xd4, 0x24, 0x3e, 0xbe, 0x4c,
	0xce, 0xfb, 0xdd, 0xfe, 0xd9, 0xff, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x17, 0x4b, 0x4d, 0x89, 0xc1,
	0x04, 0x00, 0x00,
}
