// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/models.proto

package models

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AuthMeta_Method int32

const (
	AuthMeta_basic     AuthMeta_Method = 0
	AuthMeta_signature AuthMeta_Method = 1
)

var AuthMeta_Method_name = map[int32]string{
	0: "basic",
	1: "signature",
}

var AuthMeta_Method_value = map[string]int32{
	"basic":     0,
	"signature": 1,
}

func (x AuthMeta_Method) String() string {
	return proto.EnumName(AuthMeta_Method_name, int32(x))
}

func (AuthMeta_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8182e6f222cf83c8, []int{0, 0}
}

type AppMeta_Status int32

const (
	AppMeta_unknown AppMeta_Status = 0
	AppMeta_normal  AppMeta_Status = 1
	AppMeta_disable AppMeta_Status = 2
)

var AppMeta_Status_name = map[int32]string{
	0: "unknown",
	1: "normal",
	2: "disable",
}

var AppMeta_Status_value = map[string]int32{
	"unknown": 0,
	"normal":  1,
	"disable": 2,
}

func (x AppMeta_Status) String() string {
	return proto.EnumName(AppMeta_Status_name, int32(x))
}

func (AppMeta_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8182e6f222cf83c8, []int{1, 0}
}

type AppMeta_GrantType int32

const (
	AppMeta_none               AppMeta_GrantType = 0
	AppMeta_authorization_code AppMeta_GrantType = 1
)

var AppMeta_GrantType_name = map[int32]string{
	0: "none",
	1: "authorization_code",
}

var AppMeta_GrantType_value = map[string]int32{
	"none":               0,
	"authorization_code": 1,
}

func (x AppMeta_GrantType) String() string {
	return proto.EnumName(AppMeta_GrantType_name, int32(x))
}

func (AppMeta_GrantType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8182e6f222cf83c8, []int{1, 1}
}

type AppMeta_GrantMode int32

const (
	AppMeta_manual AppMeta_GrantMode = 0
	AppMeta_full   AppMeta_GrantMode = 1
)

var AppMeta_GrantMode_name = map[int32]string{
	0: "manual",
	1: "full",
}

var AppMeta_GrantMode_value = map[string]int32{
	"manual": 0,
	"full":   1,
}

func (x AppMeta_GrantMode) String() string {
	return proto.EnumName(AppMeta_GrantMode_name, int32(x))
}

func (AppMeta_GrantMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8182e6f222cf83c8, []int{1, 2}
}

type RoleMeta_Type int32

const (
	RoleMeta_user   RoleMeta_Type = 0
	RoleMeta_system RoleMeta_Type = 1
)

var RoleMeta_Type_name = map[int32]string{
	0: "user",
	1: "system",
}

var RoleMeta_Type_value = map[string]int32{
	"user":   0,
	"system": 1,
}

func (x RoleMeta_Type) String() string {
	return proto.EnumName(RoleMeta_Type_name, int32(x))
}

func (RoleMeta_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8182e6f222cf83c8, []int{2, 0}
}

type AuthMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthMeta) Reset()         { *m = AuthMeta{} }
func (m *AuthMeta) String() string { return proto.CompactTextString(m) }
func (*AuthMeta) ProtoMessage()    {}
func (*AuthMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_8182e6f222cf83c8, []int{0}
}
func (m *AuthMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthMeta.Unmarshal(m, b)
}
func (m *AuthMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthMeta.Marshal(b, m, deterministic)
}
func (m *AuthMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthMeta.Merge(m, src)
}
func (m *AuthMeta) XXX_Size() int {
	return xxx_messageInfo_AuthMeta.Size(m)
}
func (m *AuthMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AuthMeta proto.InternalMessageInfo

type AppMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppMeta) Reset()         { *m = AppMeta{} }
func (m *AppMeta) String() string { return proto.CompactTextString(m) }
func (*AppMeta) ProtoMessage()    {}
func (*AppMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_8182e6f222cf83c8, []int{1}
}
func (m *AppMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppMeta.Unmarshal(m, b)
}
func (m *AppMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppMeta.Marshal(b, m, deterministic)
}
func (m *AppMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppMeta.Merge(m, src)
}
func (m *AppMeta) XXX_Size() int {
	return xxx_messageInfo_AppMeta.Size(m)
}
func (m *AppMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_AppMeta.DiscardUnknown(m)
}

var xxx_messageInfo_AppMeta proto.InternalMessageInfo

type RoleMeta struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleMeta) Reset()         { *m = RoleMeta{} }
func (m *RoleMeta) String() string { return proto.CompactTextString(m) }
func (*RoleMeta) ProtoMessage()    {}
func (*RoleMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_8182e6f222cf83c8, []int{2}
}
func (m *RoleMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleMeta.Unmarshal(m, b)
}
func (m *RoleMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleMeta.Marshal(b, m, deterministic)
}
func (m *RoleMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleMeta.Merge(m, src)
}
func (m *RoleMeta) XXX_Size() int {
	return xxx_messageInfo_RoleMeta.Size(m)
}
func (m *RoleMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RoleMeta proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("idas.service.models.AuthMeta_Method", AuthMeta_Method_name, AuthMeta_Method_value)
	proto.RegisterEnum("idas.service.models.AppMeta_Status", AppMeta_Status_name, AppMeta_Status_value)
	proto.RegisterEnum("idas.service.models.AppMeta_GrantType", AppMeta_GrantType_name, AppMeta_GrantType_value)
	proto.RegisterEnum("idas.service.models.AppMeta_GrantMode", AppMeta_GrantMode_name, AppMeta_GrantMode_value)
	proto.RegisterEnum("idas.service.models.RoleMeta_Type", RoleMeta_Type_name, RoleMeta_Type_value)
	proto.RegisterType((*AuthMeta)(nil), "idas.service.models.AuthMeta")
	proto.RegisterType((*AppMeta)(nil), "idas.service.models.AppMeta")
	proto.RegisterType((*RoleMeta)(nil), "idas.service.models.RoleMeta")
}

func init() { proto.RegisterFile("types/models.proto", fileDescriptor_8182e6f222cf83c8) }

var fileDescriptor_8182e6f222cf83c8 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x90, 0x31, 0x4f, 0x03, 0x31,
	0x0c, 0x85, 0xef, 0x50, 0xb9, 0xb6, 0x46, 0x48, 0x51, 0x90, 0x98, 0x10, 0x82, 0x4c, 0x2c, 0x5c,
	0x07, 0x46, 0xa6, 0xb2, 0x30, 0x75, 0x01, 0x26, 0x16, 0xe4, 0x36, 0xa6, 0x8d, 0x9a, 0x8b, 0xa3,
	0xc4, 0x01, 0x95, 0xbf, 0xc0, 0x9f, 0x46, 0xd7, 0x3b, 0x26, 0x0f, 0xef, 0xf9, 0xf9, 0xf9, 0x03,
	0x2d, 0x87, 0x48, 0x79, 0xd1, 0xb1, 0x25, 0x9f, 0xdb, 0x98, 0x58, 0x58, 0x5f, 0x38, 0x8b, 0xb9,
	0xcd, 0x94, 0xbe, 0xdc, 0x86, 0xda, 0x41, 0x32, 0x2d, 0xcc, 0x96, 0x45, 0x76, 0x2b, 0x12, 0x34,
	0x06, 0x9a, 0x15, 0xc9, 0x8e, 0xad, 0x9e, 0xc3, 0xe9, 0x1a, 0xb3, 0xdb, 0xa8, 0x4a, 0x9f, 0xc3,
	0x3c, 0xbb, 0x6d, 0x40, 0x29, 0x89, 0x54, 0x6d, 0x7e, 0x6b, 0x98, 0x2e, 0x63, 0x3c, 0xfa, 0x5b,
	0x68, 0x5e, 0x05, 0xa5, 0x64, 0x7d, 0x06, 0xd3, 0x12, 0xf6, 0x81, 0xbf, 0x83, 0xaa, 0x34, 0x40,
	0x13, 0x38, 0x75, 0xe8, 0x55, 0xdd, 0x0b, 0xd6, 0x65, 0x5c, 0x7b, 0x52, 0x27, 0xe6, 0x1e, 0xe6,
	0xcf, 0x09, 0x83, 0xbc, 0x1d, 0x22, 0xe9, 0x19, 0x4c, 0x02, 0x07, 0x52, 0x95, 0xbe, 0x04, 0x8d,
	0x45, 0x76, 0x9c, 0xdc, 0x0f, 0x8a, 0xe3, 0xf0, 0xb1, 0x61, 0xdb, 0x9f, 0xba, 0x1d, 0xed, 0x2b,
	0xb6, 0xd4, 0x87, 0x76, 0x18, 0x0a, 0x7a, 0x55, 0xf5, 0xab, 0x9f, 0xc5, 0x7b, 0x55, 0x9b, 0x3b,
	0x98, 0xbd, 0xb0, 0xa7, 0x63, 0x9b, 0x2b, 0x98, 0xfc, 0x07, 0x97, 0x4c, 0x69, 0x28, 0x92, 0x0f,
	0x59, 0xa8, 0x53, 0xf5, 0xd3, 0xcd, 0xfb, 0x75, 0xff, 0xfe, 0x22, 0xee, 0xb7, 0x8b, 0x11, 0xc1,
	0x48, 0xe7, 0x71, 0x18, 0xeb, 0xe6, 0x48, 0xe9, 0xe1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xe5,
	0xce, 0x89, 0x3b, 0x01, 0x00, 0x00,
}
